/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <errorsys.prg>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\errorsys.prg /q /oc:\HTI\sismaster\errorsys.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.05.30 12:24:38 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "errorsys.prg"

HB_FUNC( ERRORSYS );
HB_FUNC_STATIC( DEFERROR );
HB_FUNC( ERRORMESSAGE );
HB_FUNC_STATIC( ERRORPREVIEW );
HB_FUNC_INITSTATICS();
HB_FUNC_EXTERN( ERRORBLOCK );
HB_FUNC_EXTERN( DTOS );
HB_FUNC_EXTERN( DATE );
HB_FUNC_EXTERN( STRTRAN );
HB_FUNC_EXTERN( TIME );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( NETERR );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( LTRIM );
HB_FUNC_EXTERN( STR );
HB_FUNC_EXTERN( PROCNAME );
HB_FUNC_EXTERN( PROCFILE );
HB_FUNC_EXTERN( PROCLINE );
HB_FUNC_EXTERN( DTOC );
HB_FUNC_EXTERN( HB_CMDARGARGV );
HB_FUNC_EXTERN( NETNAME );
HB_FUNC_EXTERN( MEMORY );
HB_FUNC_EXTERN( DISKSPACE );
HB_FUNC_EXTERN( CURDIR );
HB_FUNC_EXTERN( OS );
HB_FUNC_EXTERN( MEMOWRIT );
HB_FUNC_EXTERN( __QUIT );
HB_FUNC_EXTERN( HB_ISSTRING );
HB_FUNC_EXTERN( HB_ISNUMERIC );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( SET );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( MEMOLINE );
HB_FUNC_EXTERN( MEMOREAD );
HB_FUNC_EXTERN( MLCOUNT );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( ROW );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_ERRORSYS )
{ "ERRORSYS", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( ERRORSYS )}, NULL },
{ "ERRORBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERRORBLOCK )}, NULL },
{ "DEFERROR", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( DEFERROR )}, NULL },
{ "DTOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOS )}, NULL },
{ "DATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DATE )}, NULL },
{ "STRTRAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRTRAN )}, NULL },
{ "TIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( TIME )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "M_CFG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXEC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "GENCODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OSCODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CANDEFAULT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NETERR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETERR )}, NULL },
{ "ERRORMESSAGE", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( ERRORMESSAGE )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "LTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( LTRIM )}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "PROCNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCNAME )}, NULL },
{ "PROCFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCFILE )}, NULL },
{ "PROCLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCLINE )}, NULL },
{ "DTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOC )}, NULL },
{ "MEMP_RESA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SISTEMA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVERSAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COD_OPERADO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_CMDARGARGV", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CMDARGARGV )}, NULL },
{ "NETNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETNAME )}, NULL },
{ "MEMORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMORY )}, NULL },
{ "DISKSPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISKSPACE )}, NULL },
{ "CURDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURDIR )}, NULL },
{ "OS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS )}, NULL },
{ "MEMOWRIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOWRIT )}, NULL },
{ "ERRORPREVIEW", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( ERRORPREVIEW )}, NULL },
{ "__QUIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __QUIT )}, NULL },
{ "SEVERITY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_ISSTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISSTRING )}, NULL },
{ "SUBSYSTEM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_ISNUMERIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISNUMERIC )}, NULL },
{ "SUBCODE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DESCRIPTION", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FILENAME", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OPERATION", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTIPO_IMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MIMP_TIPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MARQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SET )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "MEMOLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOLINE )}, NULL },
{ "MEMOREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( MEMOREAD )}, NULL },
{ "MLCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MLCOUNT )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "ROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( ROW )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "(_INITSTATICS00001)", {HB_FS_INITEXIT}, {hb_INITSTATICS}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_ERRORSYS )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_ERRORSYS
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_ERRORSYS = hb_vm_SymbolInit_ERRORSYS;
   #pragma data_seg()
#endif

HB_FUNC( ERRORSYS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 19, 0,	/* 19 */
	HB_P_PUSHSYMNEAR, 1,	/* ERRORBLOCK */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 2,	/* DEFERROR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_DOSHORT, 1,
/* 00023 */ HB_P_LINEOFFSET, 1,	/* 20 */
	HB_P_ENDPROC
/* 00026 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( DEFERROR )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 1,	/* locals, params */
	HB_P_SFRAME, 65, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 27, 0,	/* 27 */
	HB_P_PUSHSYMNEAR, 3,	/* DTOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 4,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 5,	/* STRTRAN */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 6,	/* TIME */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	':', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'_', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'l', 'o', 'g', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* CLOGFILE */
/* 00048 */ HB_P_LINEOFFSET, 2,	/* 29 */
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 8, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPSTATIC, 1, 0,	/* LOGINITIALPATH */
/* 00064 */ HB_P_LINEOFFSET, 4,	/* 31 */
	HB_P_MESSAGE, 9, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 10,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'R', 'O', 'L', 'L', 'B', 'A', 'C', 'K', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00090 */ HB_P_LINEOFFSET, 7,	/* 34 */
	HB_P_MESSAGE, 11, 0,	/* GENCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00109) */
/* 00104 */ HB_P_LINEOFFSET, 8,	/* 35 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00109 */ HB_P_LINEOFFSET, 14,	/* 41 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_MESSAGE, 11, 0,	/* GENCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 00136) */
	HB_P_POP,
	HB_P_MESSAGE, 12, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00146) */
	HB_P_POP,
	HB_P_MESSAGE, 13, 0,	/* CANDEFAULT */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00161) */
/* 00148 */ HB_P_LINEOFFSET, 15,	/* 42 */
	HB_P_PUSHSYMNEAR, 14,	/* NETERR */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
/* 00156 */ HB_P_LINEOFFSET, 16,	/* 43 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00161 */ HB_P_LINEOFFSET, 21,	/* 48 */
	HB_P_FALSE,
	HB_P_MESSAGE, 11, 0,	/* GENCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00184) */
	HB_P_POP,
	HB_P_MESSAGE, 13, 0,	/* CANDEFAULT */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00199) */
/* 00186 */ HB_P_LINEOFFSET, 22,	/* 49 */
	HB_P_PUSHSYMNEAR, 14,	/* NETERR */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
/* 00194 */ HB_P_LINEOFFSET, 23,	/* 50 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00199 */ HB_P_LINEOFFSET, 25,	/* 52 */
	HB_P_PUSHSYMNEAR, 15,	/* ERRORMESSAGE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00210 */ HB_P_LINEOFFSET, 26,	/* 53 */
	HB_P_PUSHSYMNEAR, 16,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 12, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 43,	/* 43 (abs: 00267) */
/* 00226 */ HB_P_LINEOFFSET, 27,	/* 54 */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'(', 'D', 'O', 'S', ' ', 'E', 'r', 'r', 'o', 'r', ' ', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 18,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 12, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	')', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* CDOSERROR */
/* 00267 */ HB_P_LINEOFFSET, 30,	/* 57 */
	HB_P_PUSHSYMNEAR, 16,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 12, 0,	/* OSCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 16,	/* 16 (abs: 00297) */
/* 00283 */ HB_P_LINEOFFSET, 31,	/* 58 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PUSHLOCALNEAR, 3,	/* CDOSERROR */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00297 */ HB_P_LINEOFFSET, 34,	/* 61 */
	HB_P_LOCALNEARSETINT, 5, 2, 0,	/* N 2*/
/* 00303 */ HB_P_LINEOFFSET, 35,	/* 62 */
	HB_P_PUSHSYMNEAR, 16,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 19,	/* PROCNAME */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 79,	/* 79 (abs: 00396) */
/* 00319 */ HB_P_LINEOFFSET, 36,	/* 63 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	13, 10, 'F', 'u', 'n', 'c', 'o', 'e', 's', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 20,	/* PROCFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'-', '>', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 19,	/* PROCNAME */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'(', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 18,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* PROCLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* N 1*/
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	')', 0, 
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 165,	/* -91 (abs: 00303) */
/* 00396 */ HB_P_LINEOFFSET, 41,	/* 68 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 83,	/* 83 */
	13, 10, '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', '*', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00488 */ HB_P_LINEOFFSET, 43,	/* 70 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'D', 'a', 't', 'a', ' ', 'e', ' ', 'H', 'o', 'r', 'a', '.', '.', '.', '.', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 22,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 4,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '-', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 6,	/* TIME */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00545 */ HB_P_LINEOFFSET, 44,	/* 71 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'E', 'm', 'p', 'r', 'e', 's', 'a', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHVARIABLE, 23, 0,	/* MEMP_RESA */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00582 */ HB_P_LINEOFFSET, 45,	/* 72 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'S', 'i', 's', 't', 'e', 'm', 'a', '/', 'A', 't', 'u', 'a', 'l', 'i', 'z', 'a', 'c', 'a', 'o', ':', ' ', 0, 
	HB_P_PUSHVARIABLE, 24, 0,	/* SISTEMA */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '-', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 25, 0,	/* MVERSAO */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00630 */ HB_P_LINEOFFSET, 46,	/* 73 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'U', 's', 'u', 'a', 'r', 'i', 'o', ' ', 'd', 'o', ' ', 'S', 'i', 's', 't', 'e', 'm', 'a', '.', ':', ' ', 0, 
	HB_P_PUSHVARIABLE, 26, 0,	/* COD_OPERADO */
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00667 */ HB_P_LINEOFFSET, 47,	/* 74 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'N', 'o', 'm', 'e', ' ', 'd', 'o', ' ', 'E', 'x', 'e', 'c', 'u', 't', 'a', 'v', 'e', 'l', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 27,	/* HB_CMDARGARGV */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00706 */ HB_P_LINEOFFSET, 48,	/* 75 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'N', 'o', 'm', 'e', ' ', 'd', 'o', ' ', 'M', 'i', 'c', 'r', 'o', '.', '.', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* NETNAME */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	' ', '-', ' ', 'N', 'o', 'm', 'e', ' ', 'T', 'e', 'r', 'm', 'i', 'n', 'a', 'l', ':', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 28,	/* NETNAME */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00774 */ HB_P_LINEOFFSET, 49,	/* 76 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'M', 'e', 'm', 'o', 'r', 'i', 'a', ' ', 'D', 'i', 's', 'p', 'o', 'n', 'i', 'v', 'e', 'l', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 18,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 29,	/* MEMORY */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 25,	/* 25 */
	' ', '-', ' ', 'E', 's', 'p', 'a', 231, 'o', ' ', 'e', 'm', ' ', 'D', 'i', 's', 'c', 'o', '.', '.', '.', '.', ':', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 18,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 30,	/* DISKSPACE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00868 */ HB_P_LINEOFFSET, 50,	/* 77 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'P', 'a', 's', 't', 'a', ' ', 'd', 'e', ' ', 'D', 'i', 'r', 'e', 't', 'o', 'r', 'i', 'o', '.', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 31,	/* CURDIR */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00907 */ HB_P_LINEOFFSET, 51,	/* 78 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	13, 10, 'S', 'i', 's', 't', 'e', 'm', 'a', ' ', 'O', 'p', 'e', 'r', 'a', 'c', 'i', 'o', 'n', 'a', 'l', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 32,	/* OS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00946 */ HB_P_LINEOFFSET, 54,	/* 81 */
	HB_P_PUSHSYMNEAR, 33,	/* MEMOWRIT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* LOGINITIALPATH */
	HB_P_PUSHLOCALNEAR, 4,	/* CLOGFILE */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_DOSHORT, 2,
/* 00961 */ HB_P_LINEOFFSET, 56,	/* 83 */
	HB_P_PUSHSYMNEAR, 34,	/* ERRORPREVIEW */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHLOCALNEAR, 4,	/* CLOGFILE */
	HB_P_DOSHORT, 2,
/* 00972 */ HB_P_LINEOFFSET, 57,	/* 84 */
	HB_P_PUSHSYMNEAR, 35,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00979 */ HB_P_LINEOFFSET, 58,	/* 85 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00984 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( ERRORMESSAGE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 92, 0,	/* 92 */
	HB_P_MESSAGE, 36, 0,	/* SEVERITY */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00027) */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'E', 'r', 'r', 'o', 'r', 0, 
	HB_P_JUMPNEAR, 12,	/* 12 (abs: 00037) */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'W', 'a', 'r', 'n', 'i', 'n', 'g', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00044 */ HB_P_LINEOFFSET, 3,	/* 95 */
	HB_P_PUSHSYMNEAR, 37,	/* HB_ISSTRING */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 38, 0,	/* SUBSYSTEM */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00076) */
/* 00060 */ HB_P_LINEOFFSET, 4,	/* 96 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_MESSAGE, 38, 0,	/* SUBSYSTEM */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00089) */
/* 00076 */ HB_P_LINEOFFSET, 6,	/* 98 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'?', '?', '?', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00089 */ HB_P_LINEOFFSET, 10,	/* 102 */
	HB_P_PUSHSYMNEAR, 39,	/* HB_ISNUMERIC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 40, 0,	/* SUBCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 33,	/* 33 (abs: 00136) */
/* 00105 */ HB_P_LINEOFFSET, 11,	/* 103 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 18,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 40, 0,	/* SUBCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00150) */
/* 00136 */ HB_P_LINEOFFSET, 13,	/* 105 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'/', '?', '?', '?', 0, 
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00150 */ HB_P_LINEOFFSET, 17,	/* 109 */
	HB_P_PUSHSYMNEAR, 37,	/* HB_ISSTRING */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 41, 0,	/* DESCRIPTION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00186) */
/* 00166 */ HB_P_LINEOFFSET, 18,	/* 110 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_MESSAGE, 41, 0,	/* DESCRIPTION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00186 */ HB_P_LINEOFFSET, 23,	/* 115 */
	HB_P_PUSHSYMNEAR, 16,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 42, 0,	/* FILENAME */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 24,	/* 24 (abs: 00224) */
/* 00202 */ HB_P_LINEOFFSET, 24,	/* 116 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', ' ', 0, 
	HB_P_MESSAGE, 42, 0,	/* FILENAME */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_JUMPNEAR, 38,	/* 38 (abs: 00260) */
/* 00224 */ HB_P_LINEOFFSET, 25,	/* 117 */
	HB_P_PUSHSYMNEAR, 16,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 43, 0,	/* OPERATION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 22,	/* 22 (abs: 00260) */
/* 00240 */ HB_P_LINEOFFSET, 26,	/* 118 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', ' ', 0, 
	HB_P_MESSAGE, 43, 0,	/* OPERATION */
	HB_P_PUSHLOCALNEAR, 1,	/* OERROR */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CMESSAGE */
/* 00260 */ HB_P_LINEOFFSET, 34,	/* 126 */
	HB_P_PUSHLOCALNEAR, 2,	/* CMESSAGE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00266 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( ERRORPREVIEW )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 5, 2,	/* locals, params */
	HB_P_SFRAME, 65, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 130, 0,	/* 130 */
	HB_P_LOCALNEARSETINT, 3, 0, 0,	/* POINT 0*/
	HB_P_LOCALNEARSETSTR, 7, 2, 0,	/* OPCAO 2*/
	' ', 0, 
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 131 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSYMNEAR, 47,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 48,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 44,	/* MTIPO_IMP */
	HB_P_PUSHSYMNEAR, 45,	/* MIMP_TIPO */
	HB_P_PUSHSYMNEAR, 46,	/* MARQ */
	HB_P_DOSHORT, 3,
	HB_P_POPVARIABLE, 46, 0,	/* MARQ */
	HB_P_POPVARIABLE, 45, 0,	/* MIMP_TIPO */
/* 00047 */ HB_P_LINEOFFSET, 3,	/* 133 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'M', 0, 
	HB_P_POPVARIABLE, 44, 0,	/* MTIPO_IMP */
/* 00056 */ HB_P_LINEOFFSET, 5,	/* 135 */
	HB_P_PUSHSYMNEAR, 49,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'S', 'C', 'R', 'E', 'E', 'N', 0, 
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 49,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 49,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'O', 'F', 'F', 0, 
	HB_P_DOSHORT, 2,
/* 00097 */ HB_P_LINEOFFSET, 6,	/* 136 */
	HB_P_PUSHSYMNEAR, 50,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHSTRSHORT, 32,	/* 32 */
	' ', 'E', ' ', 'R', ' ', 'R', ' ', 'O', ' ', ' ', ' ', 'D', ' ', 'O', ' ', ' ', ' ', 'S', ' ', 'I', ' ', 'S', ' ', 'T', ' ', 'E', ' ', 'M', ' ', 'A', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 00145 */ HB_P_LINEOFFSET, 7,	/* 137 */
	HB_P_PUSHSYMNEAR, 51,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* MEMOREAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* LOGINITIALPATH */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHLOCALNEAR, 2,	/* CARQ */
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 95,	/* 95 */
	HB_P_ONE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* LIN */
/* 00175 */ HB_P_LINEOFFSET, 8,	/* 138 */
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* LINHA 0*/
	HB_P_PUSHLOCALNEAR, 6,	/* LINHA */
	HB_P_POPLOCALNEAR, 5,	/* LINHAS */
/* 00185 */ HB_P_LINEOFFSET, 9,	/* 139 */
	HB_P_PUSHSYMNEAR, 53,	/* MLCOUNT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* MEMOREAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* LOGINITIALPATH */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHLOCALNEAR, 2,	/* CARQ */
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 95,	/* 95 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 5,	/* LINHAS */
/* 00212 */ HB_P_LINEOFFSET, 10,	/* 140 */
	HB_P_LOCALNEARSETINT, 6, 1, 0,	/* LINHA 1*/
	HB_P_PUSHLOCALNEAR, 6,	/* LINHA */
	HB_P_PUSHLOCALNEAR, 5,	/* LINHAS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 69,	/* 69 (abs: 00292) */
/* 00225 */ HB_P_LINEOFFSET, 11,	/* 141 */
	HB_P_PUSHSYMNEAR, 51,	/* MEMOLINE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* MEMOREAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* LOGINITIALPATH */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHLOCALNEAR, 2,	/* CARQ */
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 95,	/* 95 */
	HB_P_PUSHLOCALNEAR, 6,	/* LINHA */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* LIN */
/* 00256 */ HB_P_LINEOFFSET, 12,	/* 142 */
	HB_P_PUSHSYMNEAR, 54,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 55,	/* ROW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 56,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 7,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* LIN */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 00284 */ HB_P_LINEOFFSET, 13,	/* 143 */
	HB_P_LOCALNEARADDINT, 6, 1, 0,	/* LINHA 1*/
	HB_P_JUMPNEAR, 184,	/* -72 (abs: 00218) */
/* 00292 */ HB_P_LINEOFFSET, 14,	/* 144 */
	HB_P_PUSHSYMNEAR, 57,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 43,	/* 43 */
	'P', 'r', 'e', 's', 's', 'i', 'o', 'n', 'e', ' ', 'q', 'u', 'a', 'l', 'q', 'u', 'e', 'r', ' ', 't', 'e', 'c', 'l', 'a', ' ', 'p', 'a', 'r', 'a', ' ', 'c', 'o', 'n', 't', 'i', 'n', 'u', 'a', 'r', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00344 */ HB_P_LINEOFFSET, 15,	/* 145 */
	HB_P_PUSHSYMNEAR, 58,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 59,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 60, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 61,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	7, 0,	/* OPCAO */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00382) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00387) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'p', 'c', 'a', 'o', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 62, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 60, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00415 */ HB_P_LINEOFFSET, 16,	/* 146 */
	HB_P_PUSHSYMNEAR, 63,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 60, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 60, 0,	/* GETLIST */
/* 00437 */ HB_P_LINEOFFSET, 36,	/* 166 */
	HB_P_PUSHSYMNEAR, 64,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00444 */ HB_P_LINEOFFSET, 37,	/* 167 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00449 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_INITSTATICS()
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 65, 0, 1, 0,	/* symbol (_INITSTATICS), 1 statics */
	HB_P_SFRAME, 65, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPSTATIC, 1, 0,	/* LOGINITIALPATH */
	HB_P_ENDPROC
/* 00015 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

