/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <MASTCUSTO.000>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\MASTCUSTO.000 /q /oc:\HTI\sismaster\MASTCUSTO.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.09.27 10:27:40 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "MASTCUSTO.000"

HB_FUNC( MASTCUSTO );
HB_FUNC_EXTERN( REPLICATE );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( READKILL );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( LIMPA );
HB_FUNC_EXTERN( WVW_PBSETFONT );
HB_FUNC_EXTERN( BOTAO );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( WVW_PBCREATE );
HB_FUNC_EXTERN( MAST30 );
HB_FUNC_EXTERN( EXIBI_PRG );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( DRAWLABEL );
HB_FUNC_EXTERN( WVW_DRAWBOXGET );
HB_FUNC_EXTERN( WVW_DRAWIMAGE );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( HB_ISNULL );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( STRZERO );
HB_FUNC_EXTERN( STR );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( TRANSFORM );
HB_FUNC_EXTERN( WVW_PBENABLE );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( F4_MERC );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( SR_CDBVALUE );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( WVW_DRAWLABEL );
HB_FUNC_EXTERN( FILE );
HB_FUNC_EXTERN( OP_SIMNAO );
HB_FUNC_EXTERN( SR_SHOWVECTOR );
HB_FUNC_EXTERN( SETMODE );
HB_FUNC_EXTERN( WVW_SETFONT );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_MASTCUSTO )
{ "MASTCUSTO", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( MASTCUSTO )}, NULL },
{ "MQTD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CONS_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "I", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NPBID", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPED_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTRACO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "REPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLICATE )}, NULL },
{ "MPRG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MMERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "MTIPO_IMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MIMP_TIPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MARQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_SAIR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCAMINHO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "MCOD_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CONS_PROD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_GRUPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READKILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READKILL )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "LIMPA", {HB_FS_PUBLIC}, {HB_FUNCNAME( LIMPA )}, NULL },
{ "WVW_PBSETFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBSETFONT )}, NULL },
{ "BOTAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOTAO )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "CONS_PARC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "WVW_PBCREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBCREATE )}, NULL },
{ "MAST30", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAST30 )}, NULL },
{ "MNUM_LUGAR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NPBOTAOID1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXIBI_PRG", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXIBI_PRG )}, NULL },
{ "MCOD_GARCON", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MOBS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "DRAWLABEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DRAWLABEL )}, NULL },
{ "WVW_DRAWBOXGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_DRAWBOXGET )}, NULL },
{ "WVW_DRAWIMAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_DRAWIMAGE )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "M_CFG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_ISNULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISNULL )}, NULL },
{ "MQTD_LIN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MITEM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "M_COLOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "STRZERO", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRZERO )}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "TRANSFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFORM )}, NULL },
{ "WVW_PBENABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBENABLE )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "F4_MERC", {HB_FS_PUBLIC}, {HB_FUNCNAME( F4_MERC )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "EXEC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "SR_CDBVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CDBVALUE )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "WVW_DRAWLABEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_DRAWLABEL )}, NULL },
{ "MPRE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILE )}, NULL },
{ "OP_SIMNAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_SIMNAO )}, NULL },
{ "M_QP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_SHOWVECTOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SHOWVECTOR )}, NULL },
{ "SETMODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETMODE )}, NULL },
{ "WVW_SETFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_SETFONT )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_MASTCUSTO )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_MASTCUSTO
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_MASTCUSTO = hb_vm_SymbolInit_MASTCUSTO;
   #pragma data_seg()
#endif

HB_FUNC( MASTCUSTO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 6, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 16, 0,	/* 16 */
	HB_P_LOCALNEARSETINT, 2, 0, 0,	/* Y 0*/
	HB_P_LOCALNEARSETINT, 3, 0, 0,	/* MQTD_AUX 0*/
	HB_P_LOCALNEARSETSTR, 4, 1, 0,	/* MOPCAO 1*/
	0, 
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* F 0*/
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* MSUBTOTAL 0*/
/* 00027 */ HB_P_LINEOFFSET, 4,	/* 20 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHSYMNEAR, 7,	/* REPLICATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'=', 0, 
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'U', 'S', 'T', 'O', 0, 
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'M', 0, 
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHSYMNEAR, 16,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* MQTD */
	HB_P_PUSHSYMNEAR, 2,	/* CONS_MERC */
	HB_P_PUSHSYMNEAR, 3,	/* I */
	HB_P_PUSHSYMNEAR, 4,	/* NPBID */
	HB_P_PUSHSYMNEAR, 5,	/* MPED_MERC */
	HB_P_PUSHSYMNEAR, 6,	/* MTRACO */
	HB_P_PUSHSYMNEAR, 8,	/* MPRG */
	HB_P_PUSHSYMNEAR, 9,	/* MMERC */
	HB_P_PUSHSYMNEAR, 11,	/* MTIPO_IMP */
	HB_P_PUSHSYMNEAR, 12,	/* MIMP_TIPO */
	HB_P_PUSHSYMNEAR, 13,	/* MARQ */
	HB_P_PUSHSYMNEAR, 14,	/* M_SAIR */
	HB_P_PUSHSYMNEAR, 15,	/* MCAMINHO */
	HB_P_DOSHORT, 13,
	HB_P_POPVARIABLE, 15, 0,	/* MCAMINHO */
	HB_P_POPVARIABLE, 14, 0,	/* M_SAIR */
	HB_P_POPVARIABLE, 13, 0,	/* MARQ */
	HB_P_POPVARIABLE, 12, 0,	/* MIMP_TIPO */
	HB_P_POPVARIABLE, 11, 0,	/* MTIPO_IMP */
	HB_P_POPVARIABLE, 9, 0,	/* MMERC */
	HB_P_POPVARIABLE, 8, 0,	/* MPRG */
	HB_P_POPVARIABLE, 6, 0,	/* MTRACO */
	HB_P_POPVARIABLE, 5, 0,	/* MPED_MERC */
	HB_P_POPVARIABLE, 4, 0,	/* NPBID */
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_POPVARIABLE, 2, 0,	/* CONS_MERC */
	HB_P_POPVARIABLE, 1, 0,	/* MQTD */
/* 00156 */ HB_P_LINEOFFSET, 6,	/* 22 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHSYMNEAR, 16,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 17,	/* MCOD_MERC */
	HB_P_PUSHSYMNEAR, 18,	/* CONS_PROD */
	HB_P_DOSHORT, 2,
	HB_P_POPVARIABLE, 18, 0,	/* CONS_PROD */
	HB_P_POPVARIABLE, 17, 0,	/* MCOD_MERC */
/* 00177 */ HB_P_LINEOFFSET, 10,	/* 26 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 19, 0,	/* OP_GRUPO */
/* 00183 */ HB_P_LINEOFFSET, 11,	/* 27 */
	HB_P_PUSHSYMNEAR, 20,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 21, 0,	/* GETLIST */
/* 00197 */ HB_P_LINEOFFSET, 12,	/* 28 */
	HB_P_PUSHSYMNEAR, 22,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 55,	/* 55 */
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'P', 'L', 'A', 'N', 'I', 'L', 'H', 'A', ' ', 'D', 'E', ' ', 'C', 'U', 'S', 'T', 'O', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 00231 */ HB_P_LINEOFFSET, 13,	/* 29 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_DOSHORT, 1,
/* 00240 */ HB_P_LINEOFFSET, 14,	/* 30 */
	HB_P_PUSHSYMNEAR, 24,	/* LIMPA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 55,	/* 55 */
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_DOSHORT, 4,
/* 00253 */ HB_P_LINEOFFSET, 15,	/* 31 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00261 */ HB_P_LINEOFFSET, 16,	/* 32 */
	HB_P_PUSHSYMNEAR, 25,	/* WVW_PBSETFONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ZERO,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 00287 */ HB_P_LINEOFFSET, 17,	/* 33 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 00296 */ HB_P_LINEOFFSET, 19,	/* 35 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DOSHORT, 4,
/* 00310 */ HB_P_LINEOFFSET, 20,	/* 36 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DOSHORT, 4,
/* 00325 */ HB_P_LINEOFFSET, 21,	/* 37 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'D', 'E', 'S', 'C', 'R', 'I', 'C', 'A', 'O', ' ', 'D', 'O', ' ', 'P', 'R', 'O', 'D', 'U', 'T', 'O', 0, 
	HB_P_DOSHORT, 1,
/* 00364 */ HB_P_LINEOFFSET, 22,	/* 38 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 29, 0,	/* CONS_PARC */
/* 00372 */ HB_P_LINEOFFSET, 24,	/* 40 */
	HB_P_PUSHSYMNEAR, 30,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 46,	/* 46 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	' ', ' ', ' ', ' ', 'I', 'M', 'P', 'R', 'I', 'M', 'I', 'R', ' ', ' ', ' ', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 11,	/* 11 */
	HB_P_PUSHSYMNEAR, 31,	/* MAST30 */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 32, 0,	/* MNUM_LUGAR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_POPVARIABLE, 33, 0,	/* NPBOTAOID1 */
/* 00422 */ HB_P_LINEOFFSET, 26,	/* 42 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00430 */ HB_P_LINEOFFSET, 28,	/* 44 */
	HB_P_PUSHSYMNEAR, 34,	/* EXIBI_PRG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 8, 0,	/* MPRG */
	HB_P_DOSHORT, 1,
/* 00440 */ HB_P_LINEOFFSET, 29,	/* 45 */
	HB_P_ZERO,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 35, 0,	/* MCOD_GARCON */
	HB_P_POPVARIABLE, 1, 0,	/* MQTD */
/* 00450 */ HB_P_LINEOFFSET, 30,	/* 46 */
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 9, 0,	/* MMERC */
/* 00462 */ HB_P_LINEOFFSET, 31,	/* 47 */
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 36, 0,	/* MOBS */
/* 00474 */ HB_P_LINEOFFSET, 32,	/* 48 */
	HB_P_PUSHSYMNEAR, 37,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 38,	/* 38 */
	'P', 'r', 'e', 'e', 'n', 'c', 'h', 'a', ' ', 'o', 's', ' ', 'C', 'a', 'm', 'p', 'o', 's', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', ' ', 'p', '/', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 00521 */ HB_P_LINEOFFSET, 33,	/* 49 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_DOSHORT, 4,
/* 00535 */ HB_P_LINEOFFSET, 34,	/* 50 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_DOSHORT, 4,
/* 00549 */ HB_P_LINEOFFSET, 35,	/* 51 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_DOSHORT, 4,
/* 00563 */ HB_P_LINEOFFSET, 37,	/* 53 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 8,
/* 00603 */ HB_P_LINEOFFSET, 38,	/* 54 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'Q', 'u', 'a', 'n', 't', 'i', 'd', 'a', 'd', 'e', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 8,
/* 00647 */ HB_P_LINEOFFSET, 39,	/* 55 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'V', 'a', 'l', 'o', 'r', ' ', 'U', 'n', 'i', 't', 'a', 'r', 'i', 'o', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 8,
/* 00695 */ HB_P_LINEOFFSET, 41,	/* 57 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00709 */ HB_P_LINEOFFSET, 42,	/* 58 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00723 */ HB_P_LINEOFFSET, 43,	/* 59 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00737 */ HB_P_LINEOFFSET, 44,	/* 60 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00751 */ HB_P_LINEOFFSET, 45,	/* 61 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 34,	/* 34 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_DOSHORT, 4,
/* 00765 */ HB_P_LINEOFFSET, 46,	/* 62 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 39,	/* 39 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00779 */ HB_P_LINEOFFSET, 47,	/* 63 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 44,	/* 44 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00793 */ HB_P_LINEOFFSET, 48,	/* 64 */
	HB_P_PUSHSYMNEAR, 39,	/* WVW_DRAWBOXGET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 49,	/* 49 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_DOSHORT, 4,
/* 00807 */ HB_P_LINEOFFSET, 51,	/* 67 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_DOSHORT, 4,
/* 00822 */ HB_P_LINEOFFSET, 52,	/* 68 */
	HB_P_PUSHSYMNEAR, 40,	/* WVW_DRAWIMAGE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 42, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'H', 'T', 'I', 'F', 'I', 'R', 'M', 'A', '.', 'J', 'P', 'G', 0, 
	HB_P_PLUS,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_DOSHORT, 8,
/* 00867 */ HB_P_LINEOFFSET, 54,	/* 70 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_DOSHORT, 4,
/* 00882 */ HB_P_LINEOFFSET, 55,	/* 71 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'S', 'U', 'B', '-', 'T', 'O', 'T', 'A', 'L', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 8,
/* 00925 */ HB_P_LINEOFFSET, 58,	/* 74 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 77,	/* 77 */
	HB_P_PUSHBYTE, 54,	/* 54 */
	HB_P_PUSHBYTE, 118,	/* 118 */
	HB_P_DOSHORT, 4,
/* 00940 */ HB_P_LINEOFFSET, 70,	/* 86 */
	HB_P_PUSHSYMNEAR, 43,	/* HB_ISNULL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 29, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUE, 238, 1,	/* 494 (abs: 01444) */
/* 00953 */ HB_P_LINEOFFSET, 71,	/* 87 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 1,
/* 00977 */ HB_P_LINEOFFSET, 72,	/* 88 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 44, 0,	/* MQTD_LIN */
/* 00983 */ HB_P_LINEOFFSET, 73,	/* 89 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 45, 0,	/* MITEM */
/* 00989 */ HB_P_LINEOFFSET, 74,	/* 90 */
	HB_P_PUSHSYMNEAR, 46,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 29, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 01020) */
/* 01004 */ HB_P_LINEOFFSET, 75,	/* 91 */
	HB_P_PUSHSYMNEAR, 46,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 29, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ADDINT, 236, 255,	/* -20*/
	HB_P_POPVARIABLE, 44, 0,	/* MQTD_LIN */
/* 01020 */ HB_P_LINEOFFSET, 77,	/* 93 */
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* F 0*/
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_POPVARIABLE, 3, 0,	/* I */
/* 01031 */ HB_P_LINEOFFSET, 78,	/* 94 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 78,	/* 78 */
	HB_P_PUSHSTRSHORT, 64,	/* 64 */
	'I', 't', 'e', 'm', ' ', ' ', 'C', 'o', 'd', '.', ' ', 'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Q', 'u', 'a', 'n', 't', 'd', '.', ' ', ' ', 'V', 'l', 'r', '.', 'U', 'n', 'i', 't', '.', ' ', ' ', 'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 47, 0,	/* M_COLOR */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_DOSHORT, 8,
/* 01139 */ HB_P_LINEOFFSET, 79,	/* 95 */
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* MSUBTOTAL 0*/
/* 01145 */ HB_P_LINEOFFSET, 80,	/* 96 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* F 1*/
/* 01151 */ HB_P_LINEOFFSET, 81,	/* 97 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_PUSHSYMNEAR, 46,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 29, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 11, 1,	/* 267 (abs: 01436) */
/* 01172 */ HB_P_LINEOFFSET, 82,	/* 98 */
	HB_P_PUSHVARIABLE, 44, 0,	/* MQTD_LIN */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_LESS,
	HB_P_JUMPFALSE, 243, 0,	/* 243 (abs: 01424) */
/* 01184 */ HB_P_LINEOFFSET, 83,	/* 99 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 78,	/* 78 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 49,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 51,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'9', ',', '9', '9', '9', '.', '9', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 51,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 51,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_DOSHORT, 8,
/* 01390 */ HB_P_LINEOFFSET, 84,	/* 100 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* F 1*/
/* 01396 */ HB_P_LINEOFFSET, 85,	/* 101 */
	HB_P_PUSHLOCALNEAR, 6,	/* MSUBTOTAL */
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 29, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 6,	/* MSUBTOTAL */
/* 01424 */ HB_P_LINEOFFSET, 87,	/* 103 */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_JUMP, 236, 254,	/* -276 (abs: 01157) */
/* 01436 */ HB_P_LINEOFFSET, 88,	/* 104 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01444 */ HB_P_LINEOFFSET, 90,	/* 106 */
	HB_P_PUSHSYMNEAR, 38,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* MSUBTOTAL */
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'@', 'E', ' ', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHINT, 210, 0,	/* 210 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'a', 'r', 'i', 'a', 'l', ' ', 'b', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 45,	/* 45 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 8,
/* 01515 */ HB_P_LINEOFFSET, 91,	/* 107 */
	HB_P_PUSHSYMNEAR, 52,	/* WVW_PBENABLE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* NPBID */
	HB_P_TRUE,
	HB_P_DOSHORT, 3,
/* 01527 */ HB_P_LINEOFFSET, 92,	/* 108 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 17, 0,	/* MCOD_MERC */
/* 01533 */ HB_P_LINEOFFSET, 93,	/* 109 */
	HB_P_PUSHSYMNEAR, 53,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 54,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 21, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 55,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 'c', 'o', 'd', '_', 'm', 'e', 'r', 'c', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'9', '9', '9', '9', '9', 0, 
	HB_P_PUSHBLOCKSHORT, 25,	/* 25 */
	HB_P_PUSHSYMNEAR, 56,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 17, 0,	/* MCOD_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 01597) */
	HB_P_PUSHSYMNEAR, 57,	/* F4_MERC */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 17, 0,	/* MCOD_MERC */
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 01598) */
	HB_P_TRUE,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 58, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 21, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01616 */ HB_P_LINEOFFSET, 94,	/* 110 */
	HB_P_PUSHSYMNEAR, 59,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 21, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 21, 0,	/* GETLIST */
/* 01638 */ HB_P_LINEOFFSET, 95,	/* 111 */
	HB_P_PUSHSYMNEAR, 60,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01653) */
	HB_P_JUMP, 19, 3,	/* 787 (abs: 02437) */
/* 01653 */ HB_P_LINEOFFSET, 98,	/* 114 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 5, 0,	/* MPED_MERC */
/* 01661 */ HB_P_LINEOFFSET, 99,	/* 115 */
	HB_P_MESSAGE, 61, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 62,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'S', 'E', 'L', 'E', 'C', 'T', ' ', '*', ' ', 'F', 'R', 'O', 'M', ' ', 'm', 'a', 's', 't', 'p', 'r', 'o', 'd', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'c', 'o', 'd', 'i', 'g', 'o', ' ', '=', ' ', 0, 
	HB_P_PUSHSYMNEAR, 63,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 17, 0,	/* MCOD_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHMEMVARREF, 5, 0,	/* MPED_MERC */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 01729 */ HB_P_LINEOFFSET, 100,	/* 116 */
	HB_P_MESSAGE, 61, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 62,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 01753 */ HB_P_LINEOFFSET, 101,	/* 117 */
	HB_P_PUSHSYMNEAR, 43,	/* HB_ISNULL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 5, 0,	/* MPED_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 50,	/* 50 (abs: 01813) */
/* 01765 */ HB_P_LINEOFFSET, 102,	/* 118 */
	HB_P_PUSHSYMNEAR, 64,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 36,	/* 36 */
	'C', 'o', 'd', 'i', 'g', 'o', ' ', 'd', 'a', ' ', 'm', 'e', 'r', 'c', 'a', 'd', 'o', 'r', 'i', 'a', ' ', 'n', 'a', 'o', ' ', 'c', 'a', 'd', 'a', 's', 't', 'r', 'a', 'd', 'o', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 98, 250,	/* -1438 (abs: 00372) */
/* 01813 */ HB_P_LINEOFFSET, 105,	/* 121 */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 9, 0,	/* MMERC */
/* 01826 */ HB_P_LINEOFFSET, 106,	/* 122 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 01835 */ HB_P_LINEOFFSET, 107,	/* 123 */
	HB_P_PUSHSYMNEAR, 65,	/* WVW_DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'a', 'r', 'i', 'a', 'l', ' ', 'b', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 16,
/* 01882 */ HB_P_LINEOFFSET, 109,	/* 125 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_POPVARIABLE, 66, 0,	/* MPRE */
/* 01891 */ HB_P_LINEOFFSET, 110,	/* 126 */
	HB_P_PUSHSYMNEAR, 24,	/* LIMPA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_DOSHORT, 4,
/* 01906 */ HB_P_LINEOFFSET, 111,	/* 127 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_DOSHORT, 4,
/* 01921 */ HB_P_LINEOFFSET, 112,	/* 128 */
	HB_P_PUSHSYMNEAR, 67,	/* FILE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 42, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'j', 'p', 'g', 0, 
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 54,	/* 54 (abs: 02014) */
/* 01962 */ HB_P_LINEOFFSET, 113,	/* 129 */
	HB_P_PUSHSYMNEAR, 40,	/* WVW_DRAWIMAGE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 42, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'j', 'p', 'g', 0, 
	HB_P_PLUS,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_DOSHORT, 8,
	HB_P_JUMPNEAR, 93,	/* 93 (abs: 02105) */
/* 02014 */ HB_P_LINEOFFSET, 114,	/* 130 */
	HB_P_PUSHSYMNEAR, 67,	/* FILE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 42, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'b', 'm', 'p', 0, 
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 52,	/* 52 (abs: 02105) */
/* 02055 */ HB_P_LINEOFFSET, 115,	/* 131 */
	HB_P_PUSHSYMNEAR, 40,	/* WVW_DRAWIMAGE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_PUSHSYMNEAR, 41,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 42, 0,	/* M_CFG */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'b', 'm', 'p', 0, 
	HB_P_PLUS,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_DOSHORT, 8,
/* 02105 */ HB_P_LINEOFFSET, 117,	/* 133 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_DOSHORT, 1,
/* 02147 */ HB_P_LINEOFFSET, 118,	/* 134 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 1, 0,	/* MQTD */
/* 02153 */ HB_P_LINEOFFSET, 119,	/* 135 */
	HB_P_PUSHSYMNEAR, 53,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 54,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 21, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 55,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'q', 't', 'd', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'9', ',', '9', '9', '9', '.', '9', '9', '9', 0, 
	HB_P_PUSHBLOCKSHORT, 26,	/* 26 */
	HB_P_PUSHSYMNEAR, 56,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 02212) */
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_ZERO,
	HB_P_LESS,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02217) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 02218) */
	HB_P_TRUE,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 58, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 21, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02236 */ HB_P_LINEOFFSET, 120,	/* 136 */
	HB_P_PUSHSYMNEAR, 59,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 21, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 21, 0,	/* GETLIST */
/* 02258 */ HB_P_LINEOFFSET, 121,	/* 137 */
	HB_P_PUSHSYMNEAR, 60,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02273) */
	HB_P_JUMP, 150, 248,	/* -1898 (abs: 00372) */
/* 02273 */ HB_P_LINEOFFSET, 124,	/* 140 */
	HB_P_PUSHSYMNEAR, 68,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'a', ' ', 'I', 'n', 'c', 'l', 'u', 's', 'a', 'o', ' ', 'd', 'o', ' ', 'P', 'R', 'O', 'D', 'U', 'T', 'O', 0, 
	HB_P_PUSHVARIABLE, 69, 0,	/* M_QP */
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 69, 0,	/* M_QP */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	' ', 'Q', 'u', 'a', 'n', 't', 'i', 'd', 'a', 'd', 'e', ':', ' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 49,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 4,	/* MOPCAO */
/* 02354 */ HB_P_LINEOFFSET, 125,	/* 141 */
	HB_P_PUSHLOCALNEAR, 4,	/* MOPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 02375) */
	HB_P_PUSHSYMNEAR, 60,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02380) */
	HB_P_JUMP, 43, 248,	/* -2005 (abs: 00372) */
/* 02380 */ HB_P_LINEOFFSET, 128,	/* 144 */
	HB_P_PUSHSYMNEAR, 54,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 29, 0,	/* CONS_PARC */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYGEN, 4, 0,	/* 4 */
	HB_P_DOSHORT, 2,
/* 02419 */ HB_P_LINEOFFSET, 129,	/* 145 */
	HB_P_PUSHSYMNEAR, 64,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 70,	/* SR_SHOWVECTOR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 29, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 242, 247,	/* -2062 (abs: 00372) */
/* 02437 */ HB_P_LINEOFFSET, 132,	/* 148 */
	HB_P_PUSHSYMNEAR, 71,	/* SETMODE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_DOSHORT, 2,
/* 02448 */ HB_P_LINEOFFSET, 133,	/* 149 */
	HB_P_PUSHSYMNEAR, 72,	/* WVW_SETFONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHINT, 132, 3,	/* 900 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 6,
/* 02482 */ HB_P_LINEOFFSET, 134,	/* 150 */
	HB_P_PUSHSYMNEAR, 73,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02489 */ HB_P_LINEOFFSET, 135,	/* 151 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 02494 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

