/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <mastercdx.prg>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\mastercdx.prg /q /oc:\HTI\sismaster\mastercdx.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.05.30 12:24:38 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "mastercdx.prg"

HB_FUNC( MASTERCDX );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( TRANSFORM );
HB_FUNC_EXTERN( WVW_DRAWPROGRESSBAR );
HB_FUNC_EXTERN( INKEY );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( APAGA_HTI );
HB_FUNC_EXTERN( __QUIT );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( SR_EXISTINDEX );
HB_FUNC_EXTERN( ABRIARQ );
HB_FUNC_EXTERN( ORDCONDSET );
HB_FUNC_EXTERN( RECNO );
HB_FUNC_EXTERN( ORDCREATE );
HB_FUNC_EXTERN( DBCLOSEAREA );
HB_FUNC_EXTERN( PROG );
HB_FUNC_EXTERN( DBCLOSEALL );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( __SETFORMAT );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_MASTERCDX )
{ "MASTERCDX", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( MASTERCDX )}, NULL },
{ "LCI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CCI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LBA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CBA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MATRIZ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "I", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OPCAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCONT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCONT1", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MALIAS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MREINDEX", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MQTD_IND", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "ARET", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "TRANSFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFORM )}, NULL },
{ "WVW_DRAWPROGRESSBAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_DRAWPROGRESSBAR )}, NULL },
{ "INKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INKEY )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "APAGA_HTI", {HB_FS_PUBLIC}, {HB_FUNCNAME( APAGA_HTI )}, NULL },
{ "__QUIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __QUIT )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "SR_EXISTINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_EXISTINDEX )}, NULL },
{ "ABRIARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( ABRIARQ )}, NULL },
{ "ORDCONDSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDCONDSET )}, NULL },
{ "RECNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( RECNO )}, NULL },
{ "ORDCREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDCREATE )}, NULL },
{ "SEN", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "SNOME", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SCOD_OP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBCLOSEAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCLOSEAREA )}, NULL },
{ "PROG", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROG )}, NULL },
{ "CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "COD_CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "RAZAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "CODIGO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DESCRI", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MESA", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "TIPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NUMERO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FORN", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CONF", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "MODULO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CID", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "CIDADE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "UF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COD_CID", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CAR", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "CARTAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "OPERACAO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBCLOSEALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCLOSEALL )}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "__SETFORMAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __SETFORMAT )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_MASTERCDX )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_MASTERCDX
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_MASTERCDX = hb_vm_SymbolInit_MASTERCDX;
   #pragma data_seg()
#endif

HB_FUNC( MASTERCDX )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 9, 0,	/* 9 */
	HB_P_LOCALNEARSETSTR, 3, 7, 0,	/* MPRG 7*/
	'S', 'A', 'C', 'C', 'D', 'X', 0, 
/* 00017 */ HB_P_LINEOFFSET, 3,	/* 12 */
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ZERO,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHSYMNEAR, 14,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* LCI */
	HB_P_PUSHSYMNEAR, 2,	/* CCI */
	HB_P_PUSHSYMNEAR, 3,	/* LBA */
	HB_P_PUSHSYMNEAR, 4,	/* CBA */
	HB_P_PUSHSYMNEAR, 5,	/* COR */
	HB_P_PUSHSYMNEAR, 6,	/* MATRIZ */
	HB_P_PUSHSYMNEAR, 7,	/* I */
	HB_P_PUSHSYMNEAR, 8,	/* OPCAO */
	HB_P_PUSHSYMNEAR, 9,	/* MCONT */
	HB_P_PUSHSYMNEAR, 10,	/* MCONT1 */
	HB_P_PUSHSYMNEAR, 11,	/* MALIAS */
	HB_P_PUSHSYMNEAR, 12,	/* MREINDEX */
	HB_P_PUSHSYMNEAR, 13,	/* MQTD_IND */
	HB_P_DOSHORT, 13,
	HB_P_POPVARIABLE, 13, 0,	/* MQTD_IND */
	HB_P_POPVARIABLE, 10, 0,	/* MCONT1 */
	HB_P_POPVARIABLE, 9, 0,	/* MCONT */
	HB_P_POPVARIABLE, 8, 0,	/* OPCAO */
	HB_P_POPVARIABLE, 7, 0,	/* I */
	HB_P_POPVARIABLE, 6, 0,	/* MATRIZ */
	HB_P_POPVARIABLE, 4, 0,	/* CBA */
	HB_P_POPVARIABLE, 3, 0,	/* LBA */
	HB_P_POPVARIABLE, 2, 0,	/* CCI */
	HB_P_POPVARIABLE, 1, 0,	/* LCI */
/* 00097 */ HB_P_LINEOFFSET, 5,	/* 14 */
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'P', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 246, 0,	/* 246 (abs: 00352) */
/* 00109 */ HB_P_LINEOFFSET, 6,	/* 15 */
	HB_P_PUSHSYMNEAR, 15,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00117 */ HB_P_LINEOFFSET, 7,	/* 16 */
	HB_P_PUSHSYMNEAR, 16,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHBYTE, 91,	/* 91 */
	HB_P_PUSHSTRSHORT, 36,	/* 36 */
	'V', 'E', 'R', 'I', 'F', 'I', 'C', 'A', 'N', 'D', 'O', ' ', 'I', 'N', 'T', 'E', 'G', 'R', 'I', 'D', 'A', 'D', 'E', ' ', 'D', 'A', 'S', ' ', 'T', 'A', 'B', 'E', 'L', 'A', 'S', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_DOSHORT, 6,
/* 00174 */ HB_P_LINEOFFSET, 8,	/* 17 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 17, 0,	/* ARET */
/* 00182 */ HB_P_LINEOFFSET, 9,	/* 18 */
	HB_P_PUSHSYMNEAR, 18,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 17, 0,	/* ARET */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_ARRAYGEN, 4, 0,	/* 4 */
	HB_P_DOSHORT, 2,
/* 00202 */ HB_P_LINEOFFSET, 10,	/* 19 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 7, 0,	/* I */
/* 00208 */ HB_P_LINEOFFSET, 11,	/* 20 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 7, 0,	/* I */
	HB_P_PUSHVARIABLE, 7, 0,	/* I */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 109,	/* 109 (abs: 00329) */
/* 00222 */ HB_P_LINEOFFSET, 12,	/* 21 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 39,	/* 39 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 7, 0,	/* I */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'9', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', '%', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00257 */ HB_P_LINEOFFSET, 13,	/* 22 */
	HB_P_PUSHSYMNEAR, 22,	/* WVW_DRAWPROGRESSBAR */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_PUSHVARIABLE, 17, 0,	/* ARET */
	HB_P_PUSHVARIABLE, 7, 0,	/* I */
	HB_P_PUSHBYTE, 102,	/* 102 */
	HB_P_PUSHINT, 155, 0,	/* 155 */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_ZERO,
	HB_P_DOSHORT, 12,
/* 00286 */ HB_P_LINEOFFSET, 14,	/* 23 */
	HB_P_PUSHSYMNEAR, 23,	/* INKEY */
	HB_P_PUSHNIL,
	HB_P_PUSHDOUBLE, 154, 153, 153, 153, 153, 153, 185, 63, 10, 1,	/* 0.1, 10, 1 */
	HB_P_DOSHORT, 1,
/* 00304 */ HB_P_LINEOFFSET, 15,	/* 24 */
	HB_P_PUSHSYMNEAR, 24,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 4,	/* 4 (abs: 00318) */
	HB_P_JUMPNEAR, 13,	/* 13 (abs: 00329) */
/* 00318 */ HB_P_LINEOFFSET, 18,	/* 27 */
	HB_P_PUSHVARIABLE, 7, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 7, 0,	/* I */
	HB_P_JUMPNEAR, 143,	/* -113 (abs: 00214) */
/* 00329 */ HB_P_LINEOFFSET, 19,	/* 28 */
	HB_P_PUSHSYMNEAR, 25,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00336 */ HB_P_LINEOFFSET, 20,	/* 29 */
	HB_P_PUSHSYMNEAR, 26,	/* APAGA_HTI */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00343 */ HB_P_LINEOFFSET, 21,	/* 30 */
	HB_P_PUSHSYMNEAR, 27,	/* __QUIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 70,	/* 70 (abs: 00420) */
/* 00352 */ HB_P_LINEOFFSET, 23,	/* 32 */
	HB_P_PUSHSYMNEAR, 16,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHBYTE, 99,	/* 99 */
	HB_P_PUSHSTRSHORT, 48,	/* 48 */
	' ', 'I', ' ', 'N', ' ', 'D', ' ', 'E', ' ', 'X', ' ', 'A', ' ', 'C', ' ', 'A', ' ', 'O', ' ', ' ', ' ', ' ', 'D', ' ', 'O', ' ', 'S', ' ', ' ', ' ', ' ', 'A', ' ', 'R', ' ', 'Q', ' ', 'U', ' ', 'I', ' ', 'V', ' ', 'O', ' ', 'S', ' ', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_DOSHORT, 6,
/* 00420 */ HB_P_LINEOFFSET, 25,	/* 34 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'0', '2', '>', ' ', 'I', 'N', 'S', 'O', 'P', 'E', 'R', 'A', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 00496 */ HB_P_LINEOFFSET, 26,	/* 35 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'i', 'n', 's', 'o', 'p', 'e', 'r', 'a', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 00531) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00530) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 17,	/* 17 (abs: 00549) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'i', 'n', 's', 'o', 'p', 'e', 'r', 'a', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 212, 0,	/* 212 (abs: 00761) */
/* 00552 */ HB_P_LINEOFFSET, 27,	/* 36 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'i', 'n', 's', 'o', 'p', 'e', 'r', 'a', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	's', 'e', 'n', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00585) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00585 */ HB_P_LINEOFFSET, 28,	/* 37 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'i', 'n', 's', 'o', 'p', 'e', 'r', 'a', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	's', 'e', 'n', 'h', 'a', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	's', 'e', 'n', '-', '>', 's', 'n', 'o', 'm', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 34,	/* SEN */
	HB_P_PUSHALIASEDFIELDNEAR, 35,	/* SNOME */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 00666 */ HB_P_LINEOFFSET, 29,	/* 38 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'i', 'n', 's', 'o', 'p', 'e', 'r', 'a', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'c', 'o', 'd', 'o', 'p', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	's', 'e', 'n', '-', '>', 's', 'c', 'o', 'd', '_', 'o', 'p', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 34,	/* SEN */
	HB_P_PUSHALIASEDFIELDNEAR, 36,	/* SCOD_OP */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 00749 */ HB_P_LINEOFFSET, 30,	/* 39 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 34,	/* SEN */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 00761 */ HB_P_LINEOFFSET, 33,	/* 42 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'0', '9', '>', ' ', 'M', 'A', 'S', 'T', 'C', 'L', 'I', ' ', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 00838 */ HB_P_LINEOFFSET, 34,	/* 43 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'M', 'A', 'S', 'T', 'C', 'L', 'I', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 00872) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00871) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 16,	/* 16 (abs: 00889) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'M', 'A', 'S', 'T', 'C', 'L', 'I', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 12, 1,	/* 268 (abs: 01157) */
/* 00892 */ HB_P_LINEOFFSET, 35,	/* 44 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'M', 'A', 'S', 'T', 'C', 'L', 'I', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00924) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00924 */ HB_P_LINEOFFSET, 36,	/* 45 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_POPVARIABLE, 13, 0,	/* MQTD_IND */
/* 00931 */ HB_P_LINEOFFSET, 37,	/* 46 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_ZERO,
	HB_P_DOSHORT, 3,
/* 00948 */ HB_P_LINEOFFSET, 38,	/* 47 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'M', 'A', 'S', 'T', 'C', 'L', 'I', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'c', 'l', 'i', '-', '>', 'c', 'o', 'd', '_', 'c', 'l', 'i', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 39,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 40,	/* COD_CLI */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 01031 */ HB_P_LINEOFFSET, 39,	/* 48 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_DOSHORT, 3,
/* 01049 */ HB_P_LINEOFFSET, 40,	/* 49 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'M', 'A', 'S', 'T', 'C', 'L', 'I', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'r', 'a', 'z', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'c', 'l', 'i', '-', '>', 'r', 'a', 'z', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 39,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 41,	/* RAZAO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 01127 */ HB_P_LINEOFFSET, 41,	/* 50 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DOSHORT, 3,
/* 01145 */ HB_P_LINEOFFSET, 42,	/* 51 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 39,	/* CLI */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 01157 */ HB_P_LINEOFFSET, 45,	/* 54 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'1', '2', '>', ' ', 'M', 'A', 'S', 'T', 'P', 'R', 'O', 'D', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 01234 */ HB_P_LINEOFFSET, 46,	/* 55 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'P', 'R', 'O', 'D', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 01269) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 01268) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 17,	/* 17 (abs: 01287) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'P', 'R', 'O', 'D', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 19, 1,	/* 275 (abs: 01562) */
/* 01290 */ HB_P_LINEOFFSET, 47,	/* 56 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'P', 'R', 'O', 'D', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'e', 'r', 'c', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 01324) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01324 */ HB_P_LINEOFFSET, 48,	/* 57 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_POPVARIABLE, 13, 0,	/* MQTD_IND */
/* 01331 */ HB_P_LINEOFFSET, 49,	/* 58 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_ZERO,
	HB_P_DOSHORT, 3,
/* 01348 */ HB_P_LINEOFFSET, 50,	/* 59 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'P', 'R', 'O', 'D', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'm', 'e', 'r', 'c', '-', '>', 'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 42,	/* MERC */
	HB_P_PUSHALIASEDFIELDNEAR, 43,	/* CODIGO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 01432 */ HB_P_LINEOFFSET, 51,	/* 60 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_DOSHORT, 3,
/* 01450 */ HB_P_LINEOFFSET, 52,	/* 61 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'P', 'R', 'O', 'D', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'd', 'e', 's', 'c', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'm', 'e', 'r', 'c', '-', '>', 'd', 'e', 's', 'c', 'r', 'i', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 42,	/* MERC */
	HB_P_PUSHALIASEDFIELDNEAR, 44,	/* DESCRI */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 01532 */ HB_P_LINEOFFSET, 53,	/* 62 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DOSHORT, 3,
/* 01550 */ HB_P_LINEOFFSET, 54,	/* 63 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 42,	/* MERC */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 01562 */ HB_P_LINEOFFSET, 57,	/* 66 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'1', '2', '>', ' ', 'M', 'A', 'S', 'T', 'M', 'E', 'S', 'A', 'S', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 01640 */ HB_P_LINEOFFSET, 58,	/* 67 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'M', 'E', 'S', 'A', 'S', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 01676) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 01675) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 18,	/* 18 (abs: 01695) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'M', 'E', 'S', 'A', 'S', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 193, 0,	/* 193 (abs: 01888) */
/* 01698 */ HB_P_LINEOFFSET, 59,	/* 68 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'M', 'E', 'S', 'A', 'S', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'e', 's', 'a', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 01733) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01733 */ HB_P_LINEOFFSET, 60,	/* 69 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_POPVARIABLE, 13, 0,	/* MQTD_IND */
/* 01740 */ HB_P_LINEOFFSET, 61,	/* 70 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_ZERO,
	HB_P_DOSHORT, 3,
/* 01757 */ HB_P_LINEOFFSET, 62,	/* 71 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'M', 'E', 'S', 'A', 'S', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	't', 'i', 'p', 'n', 'u', 'm', 0, 
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	'm', 'e', 's', 'a', '-', '>', 't', 'i', 'p', 'o', '+', 'm', 'e', 's', 'a', '-', '>', 'n', 'u', 'm', 'e', 'r', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 45,	/* MESA */
	HB_P_PUSHALIASEDFIELDNEAR, 46,	/* TIPO */
	HB_P_PUSHSYMNEAR, 45,	/* MESA */
	HB_P_PUSHALIASEDFIELDNEAR, 47,	/* NUMERO */
	HB_P_PLUS,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 01858 */ HB_P_LINEOFFSET, 63,	/* 72 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DOSHORT, 3,
/* 01876 */ HB_P_LINEOFFSET, 64,	/* 73 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 45,	/* MESA */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 01888 */ HB_P_LINEOFFSET, 66,	/* 75 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'1', '2', '>', ' ', 'M', 'A', 'S', 'T', 'F', 'O', 'R', 'N', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 01965 */ HB_P_LINEOFFSET, 67,	/* 76 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'F', 'O', 'R', 'N', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 02000) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 01999) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 17,	/* 17 (abs: 02018) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'F', 'O', 'R', 'N', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 220, 0,	/* 220 (abs: 02238) */
/* 02021 */ HB_P_LINEOFFSET, 68,	/* 77 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'A', 'S', 'T', 'F', 'O', 'R', 'N', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'f', 'o', 'r', 'n', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 02055) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02055 */ HB_P_LINEOFFSET, 69,	/* 78 */
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'a', 's', 't', 'f', 'o', 'r', 'n', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'f', 'o', 'r', 'n', '-', '>', 'c', 'o', 'd', '_', 'f', 'o', 'r', 'n', 0, 
	HB_P_DOSHORT, 3,
/* 02099 */ HB_P_LINEOFFSET, 70,	/* 79 */
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'a', 's', 't', 'f', 'o', 'r', 'n', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'n', 'o', 'm', 'e', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'f', 'o', 'r', 'n', '-', '>', 'r', 'a', 'z', 'a', 'o', 0, 
	HB_P_DOSHORT, 3,
/* 02138 */ HB_P_LINEOFFSET, 71,	/* 80 */
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'a', 's', 't', 'f', 'o', 'r', 'n', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'g', 'c', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'f', 'o', 'r', 'n', '-', '>', 'c', 'g', 'c', 0, 
	HB_P_DOSHORT, 3,
/* 02174 */ HB_P_LINEOFFSET, 72,	/* 81 */
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'a', 's', 't', 'f', 'o', 'r', 'n', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'l', 'o', 'c', 'a', 'l', 0, 
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	'f', 'o', 'r', 'n', '-', '>', 'l', 'o', 'c', 'a', 'l', '+', 'f', 'o', 'r', 'n', '-', '>', 'r', 'a', 'z', 'a', 'o', 0, 
	HB_P_DOSHORT, 3,
/* 02226 */ HB_P_LINEOFFSET, 73,	/* 82 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 48,	/* FORN */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 02238 */ HB_P_LINEOFFSET, 93,	/* 102 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'3', '4', '>', ' ', 'S', 'A', 'C', 'C', 'O', 'N', 'F', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 02314 */ HB_P_LINEOFFSET, 94,	/* 103 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	's', 'a', 'c', 'c', 'o', 'n', 'f', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 02340) */
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 234, 0,	/* 234 (abs: 02574) */
/* 02343 */ HB_P_LINEOFFSET, 95,	/* 104 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'S', 'A', 'C', 'C', 'O', 'N', 'F', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'c', 'o', 'n', 'f', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 02376) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02376 */ HB_P_LINEOFFSET, 96,	/* 105 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	's', 'a', 'c', 'c', 'o', 'n', 'f', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'd', 'e', 's', 'c', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'c', 'o', 'n', 'f', '-', '>', 'd', 'e', 's', 'c', 'r', 'i', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 49,	/* CONF */
	HB_P_PUSHALIASEDFIELDNEAR, 44,	/* DESCRI */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 02457 */ HB_P_LINEOFFSET, 97,	/* 106 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	's', 'a', 'c', 'c', 'o', 'n', 'f', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'o', 'd', 'u', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'c', 'o', 'n', 'f', '-', '>', 'm', 'o', 'd', 'u', 'l', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 49,	/* CONF */
	HB_P_PUSHALIASEDFIELDNEAR, 50,	/* MODULO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 02538 */ HB_P_LINEOFFSET, 98,	/* 107 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', 'O', 'K', 0, 
	HB_P_DOSHORT, 4,
/* 02562 */ HB_P_LINEOFFSET, 99,	/* 108 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 49,	/* CONF */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 02574 */ HB_P_LINEOFFSET, 101,	/* 110 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'4', '9', '>', ' ', 'S', 'A', 'C', 'C', 'I', 'D', ' ', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 02650 */ HB_P_LINEOFFSET, 102,	/* 111 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 'a', 'c', 'c', 'i', 'd', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 02683) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 02682) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 02699) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 'a', 'c', 'c', 'i', 'd', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 245, 0,	/* 245 (abs: 02944) */
/* 02702 */ HB_P_LINEOFFSET, 103,	/* 112 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 'a', 'c', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 02733) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02733 */ HB_P_LINEOFFSET, 104,	/* 113 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 'a', 'c', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'c', 'i', 'd', 'a', 0, 
	HB_P_PUSHSTRSHORT, 20,	/* 20 */
	'c', 'i', 'd', '-', '>', 'c', 'i', 'd', 'a', 'd', 'e', '+', 'c', 'i', 'd', '-', '>', 'u', 'f', 0, 
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 51,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 52,	/* CIDADE */
	HB_P_PUSHSYMNEAR, 51,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 53,	/* UF */
	HB_P_PLUS,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 02825 */ HB_P_LINEOFFSET, 105,	/* 114 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 'a', 'c', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 'o', 'd', 'c', 'i', 'd', 'a', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'c', 'i', 'd', '-', '>', 'c', 'o', 'd', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 51,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 54,	/* COD_CID */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 02908 */ HB_P_LINEOFFSET, 106,	/* 115 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', 'O', 'K', 0, 
	HB_P_DOSHORT, 4,
/* 02932 */ HB_P_LINEOFFSET, 107,	/* 116 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 51,	/* CID */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 02944 */ HB_P_LINEOFFSET, 111,	/* 120 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'2', '1', '>', ' ', 'M', 'A', 'S', 'T', 'C', 'A', 'R', 'T', 'A', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 03021 */ HB_P_LINEOFFSET, 112,	/* 121 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'A', 'R', 'T', 'A', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 15,	/* 15 (abs: 03057) */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 03056) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 18,	/* 18 (abs: 03076) */
	HB_P_PUSHLOCALNEAR, 2,	/* MFILE */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'A', 'R', 'T', 'A', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 239, 0,	/* 239 (abs: 03315) */
/* 03079 */ HB_P_LINEOFFSET, 113,	/* 122 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'A', 'R', 'T', 'A', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'a', 'r', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 03113) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 03113 */ HB_P_LINEOFFSET, 114,	/* 123 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'A', 'R', 'T', 'A', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'c', 'a', 'r', '-', '>', 'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 55,	/* CAR */
	HB_P_PUSHALIASEDFIELDNEAR, 43,	/* CODIGO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 03197 */ HB_P_LINEOFFSET, 115,	/* 124 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'A', 'R', 'T', 'A', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'c', 'a', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'c', 'a', 'r', '-', '>', 'c', 'a', 'r', 't', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 55,	/* CAR */
	HB_P_PUSHALIASEDFIELDNEAR, 56,	/* CARTAO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 03279 */ HB_P_LINEOFFSET, 116,	/* 125 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_PUSHVARIABLE, 2, 0,	/* CCI */
	HB_P_ADDINT, 17, 0,	/* 17*/
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', 'O', 'K', 0, 
	HB_P_DOSHORT, 4,
/* 03303 */ HB_P_LINEOFFSET, 117,	/* 126 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 55,	/* CAR */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 03315 */ HB_P_LINEOFFSET, 119,	/* 128 */
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'2', '7', '>', ' ', 'S', 'A', 'C', 'O', 'P', ' ', ' ', ' ', ' ', '=', '>', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 19,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 20,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 28,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 1,
/* 03376 */ HB_P_LINEOFFSET, 120,	/* 129 */
	HB_P_PUSHSYMNEAR, 29,	/* SR_EXISTINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	's', 'a', 'c', 'o', 'p', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 03400) */
	HB_P_PUSHLOCALNEAR, 1,	/* INDEXAR */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 148, 0,	/* 148 (abs: 03548) */
/* 03403 */ HB_P_LINEOFFSET, 121,	/* 130 */
	HB_P_PUSHSYMNEAR, 30,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'S', 'A', 'C', 'O', 'P', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'o', 'p', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 03432) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 03432 */ HB_P_LINEOFFSET, 122,	/* 131 */
	HB_P_PUSHSYMNEAR, 31,	/* ORDCONDSET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 20,
	HB_P_PUSHSYMNEAR, 33,	/* ORDCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	's', 'a', 'c', 'o', 'p', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'o', 'd', '_', 'o', 'p', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'o', 'p', '-', '>', 'o', 'p', 'e', 'r', 'a', 'c', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 57,	/* OP */
	HB_P_PUSHALIASEDFIELDNEAR, 58,	/* OPERACAO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_DOSHORT, 8,
/* 03513 */ HB_P_LINEOFFSET, 123,	/* 132 */
	HB_P_PUSHSYMNEAR, 38,	/* PROG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* LCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', 'O', 'K', 0, 
	HB_P_DOSHORT, 4,
/* 03536 */ HB_P_LINEOFFSET, 124,	/* 133 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 57,	/* OP */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 37,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 03548 */ HB_P_LINEOFFSET, 127,	/* 136 */
	HB_P_PUSHSYMNEAR, 59,	/* DBCLOSEALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 60,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 61,	/* __SETFORMAT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 1,
/* 03570 */ HB_P_LINEOFFSET, 128,	/* 137 */
	HB_P_PUSHSYMNEAR, 25,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03577 */ HB_P_LINEOFFSET, 129,	/* 138 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 03582 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

