/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <MASTCUSTO.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\MASTCUSTO.PRG /q /oc:\HTI\sismaster\MASTCUSTO.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.12.14 10:06:51 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "MASTCUSTO.PRG"

HB_FUNC( MASTCUSTO );
HB_FUNC_EXTERN( REPLICATE );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( READKILL );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( LIMPA );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( WVW_PBSETFONT );
HB_FUNC_EXTERN( BOTAO );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( EXIBI_PRG );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( DRAWLABEL );
HB_FUNC_EXTERN( HB_ISNULL );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( STRZERO );
HB_FUNC_EXTERN( STR );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( TRANSFORM );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( WVW_PBENABLE );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( F4_MERC );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( SR_CDBVALUE );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( OP_SIMNAO );
HB_FUNC_EXTERN( SETMODE );
HB_FUNC_EXTERN( WVW_SETFONT );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_MASTCUSTO )
{ "MASTCUSTO", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( MASTCUSTO )}, NULL },
{ "MQTD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CONS_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "I", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NPBID", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MPED_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MTRACO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "REPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLICATE )}, NULL },
{ "MPRG", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MMERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "MTIPO_IMP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MIMP_TIPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MARQ", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "M_SAIR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MCAMINHO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "MCOD_MERC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CONS_PROD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READKILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READKILL )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "LIMPA", {HB_FS_PUBLIC}, {HB_FUNCNAME( LIMPA )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "WVW_PBSETFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBSETFONT )}, NULL },
{ "CONS_PARC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BOTAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOTAO )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXIBI_PRG", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXIBI_PRG )}, NULL },
{ "MCOD_GARCON", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MOBS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "DRAWLABEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DRAWLABEL )}, NULL },
{ "M_COLOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "HB_ISNULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISNULL )}, NULL },
{ "MQTD_LIN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MITEM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "STRZERO", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRZERO )}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "TRANSFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFORM )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "WVW_PBENABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBENABLE )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "F4_MERC", {HB_FS_PUBLIC}, {HB_FUNCNAME( F4_MERC )}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "EXEC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "SR_CDBVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CDBVALUE )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "MPRE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "OP_SIMNAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_SIMNAO )}, NULL },
{ "M_QP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETMODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETMODE )}, NULL },
{ "WVW_SETFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_SETFONT )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_MASTCUSTO )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_MASTCUSTO
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_MASTCUSTO = hb_vm_SymbolInit_MASTCUSTO;
   #pragma data_seg()
#endif

HB_FUNC( MASTCUSTO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 16, 0,	/* 16 */
	HB_P_LOCALNEARSETINT, 2, 0, 0,	/* Y 0*/
	HB_P_LOCALNEARSETINT, 3, 0, 0,	/* MQTD_AUX 0*/
	HB_P_LOCALNEARSETSTR, 4, 1, 0,	/* MOPCAO 1*/
	0, 
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* F 0*/
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* MSUBTOTAL 0*/
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* MCUSTO 0*/
/* 00031 */ HB_P_LINEOFFSET, 4,	/* 20 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHSYMNEAR, 7,	/* REPLICATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'=', 0, 
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'S', 'T', 'C', 'U', 'S', 'T', 'O', 0, 
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'M', 0, 
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHSYMNEAR, 16,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 1,	/* MQTD */
	HB_P_PUSHSYMNEAR, 2,	/* CONS_MERC */
	HB_P_PUSHSYMNEAR, 3,	/* I */
	HB_P_PUSHSYMNEAR, 4,	/* NPBID */
	HB_P_PUSHSYMNEAR, 5,	/* MPED_MERC */
	HB_P_PUSHSYMNEAR, 6,	/* MTRACO */
	HB_P_PUSHSYMNEAR, 8,	/* MPRG */
	HB_P_PUSHSYMNEAR, 9,	/* MMERC */
	HB_P_PUSHSYMNEAR, 11,	/* MTIPO_IMP */
	HB_P_PUSHSYMNEAR, 12,	/* MIMP_TIPO */
	HB_P_PUSHSYMNEAR, 13,	/* MARQ */
	HB_P_PUSHSYMNEAR, 14,	/* M_SAIR */
	HB_P_PUSHSYMNEAR, 15,	/* MCAMINHO */
	HB_P_DOSHORT, 13,
	HB_P_POPVARIABLE, 15, 0,	/* MCAMINHO */
	HB_P_POPVARIABLE, 14, 0,	/* M_SAIR */
	HB_P_POPVARIABLE, 13, 0,	/* MARQ */
	HB_P_POPVARIABLE, 12, 0,	/* MIMP_TIPO */
	HB_P_POPVARIABLE, 11, 0,	/* MTIPO_IMP */
	HB_P_POPVARIABLE, 9, 0,	/* MMERC */
	HB_P_POPVARIABLE, 8, 0,	/* MPRG */
	HB_P_POPVARIABLE, 6, 0,	/* MTRACO */
	HB_P_POPVARIABLE, 5, 0,	/* MPED_MERC */
	HB_P_POPVARIABLE, 4, 0,	/* NPBID */
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_POPVARIABLE, 2, 0,	/* CONS_MERC */
	HB_P_POPVARIABLE, 1, 0,	/* MQTD */
/* 00160 */ HB_P_LINEOFFSET, 6,	/* 22 */
	HB_P_ZERO,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHSYMNEAR, 16,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 17,	/* MCOD_MERC */
	HB_P_PUSHSYMNEAR, 18,	/* CONS_PROD */
	HB_P_DOSHORT, 2,
	HB_P_POPVARIABLE, 18, 0,	/* CONS_PROD */
	HB_P_POPVARIABLE, 17, 0,	/* MCOD_MERC */
/* 00181 */ HB_P_LINEOFFSET, 9,	/* 25 */
	HB_P_PUSHSYMNEAR, 19,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 20, 0,	/* GETLIST */
/* 00195 */ HB_P_LINEOFFSET, 10,	/* 26 */
	HB_P_PUSHSYMNEAR, 21,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 55,	/* 55 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'P', 'L', 'A', 'N', 'I', 'L', 'H', 'A', ' ', 'D', 'E', ' ', 'C', 'U', 'S', 'T', 'O', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 00229 */ HB_P_LINEOFFSET, 11,	/* 27 */
	HB_P_PUSHSYMNEAR, 22,	/* LIMPA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 55,	/* 55 */
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_DOSHORT, 4,
/* 00242 */ HB_P_LINEOFFSET, 12,	/* 28 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00250 */ HB_P_LINEOFFSET, 13,	/* 29 */
	HB_P_PUSHSYMNEAR, 24,	/* WVW_PBSETFONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ZERO,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 5,
/* 00276 */ HB_P_LINEOFFSET, 14,	/* 30 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 00285 */ HB_P_LINEOFFSET, 15,	/* 31 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 25, 0,	/* CONS_PARC */
/* 00293 */ HB_P_LINEOFFSET, 16,	/* 32 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_DOSHORT, 4,
/* 00306 */ HB_P_LINEOFFSET, 17,	/* 33 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'O', 'u', 't', 'r', 'o', 's', ' ', 'C', 'u', 's', 't', 'o', ' ', '(', '%', ')', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00342 */ HB_P_LINEOFFSET, 18,	/* 34 */
	HB_P_PUSHSYMNEAR, 29,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 30,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 31,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	7, 0,	/* MCUSTO */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00381) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00386) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'm', 'c', 'u', 's', 't', 'o', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'9', '9', '9', '.', '9', '9', '9', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 32, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00424 */ HB_P_LINEOFFSET, 22,	/* 38 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00432 */ HB_P_LINEOFFSET, 24,	/* 40 */
	HB_P_PUSHSYMNEAR, 33,	/* EXIBI_PRG */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 8, 0,	/* MPRG */
	HB_P_DOSHORT, 1,
/* 00442 */ HB_P_LINEOFFSET, 25,	/* 41 */
	HB_P_ZERO,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 34, 0,	/* MCOD_GARCON */
	HB_P_POPVARIABLE, 1, 0,	/* MQTD */
/* 00452 */ HB_P_LINEOFFSET, 26,	/* 42 */
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 9, 0,	/* MMERC */
/* 00464 */ HB_P_LINEOFFSET, 27,	/* 43 */
	HB_P_PUSHSYMNEAR, 10,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 35, 0,	/* MOBS */
/* 00476 */ HB_P_LINEOFFSET, 28,	/* 44 */
	HB_P_PUSHSYMNEAR, 36,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 38,	/* 38 */
	'P', 'r', 'e', 'e', 'n', 'c', 'h', 'a', ' ', 'o', 's', ' ', 'C', 'a', 'm', 'p', 'o', 's', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', ' ', 'p', '/', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 00523 */ HB_P_LINEOFFSET, 30,	/* 46 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_DOSHORT, 4,
/* 00537 */ HB_P_LINEOFFSET, 31,	/* 47 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'C', 'o', 'd', '.', 'P', 'r', 'o', 'd', 'u', 't', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00568 */ HB_P_LINEOFFSET, 32,	/* 48 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00599 */ HB_P_LINEOFFSET, 33,	/* 49 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'Q', 'u', 'a', 'n', 't', 'i', 'd', 'a', 'd', 'e', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00630 */ HB_P_LINEOFFSET, 34,	/* 50 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'P', 'r', 'e', 'c', 'o', '.', '.', '.', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00661 */ HB_P_LINEOFFSET, 35,	/* 51 */
	HB_P_PUSHSYMNEAR, 26,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 48,	/* 48 */
	HB_P_DOSHORT, 4,
/* 00675 */ HB_P_LINEOFFSET, 36,	/* 52 */
	HB_P_PUSHSYMNEAR, 37,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSTRSHORT, 64,	/* 64 */
	'I', 't', 'e', 'm', ' ', ' ', 'C', 'o', 'd', '.', ' ', 'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Q', 'u', 'a', 'n', 't', 'd', '.', ' ', ' ', 'V', 'l', 'r', '.', 'U', 'n', 'i', 't', '.', ' ', ' ', 'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 38, 0,	/* M_COLOR */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_DOSHORT, 8,
/* 00783 */ HB_P_LINEOFFSET, 37,	/* 53 */
	HB_P_PUSHSYMNEAR, 39,	/* HB_ISNULL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 25, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUE, 214, 1,	/* 470 (abs: 01263) */
/* 00796 */ HB_P_LINEOFFSET, 38,	/* 54 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 40, 0,	/* MQTD_LIN */
/* 00802 */ HB_P_LINEOFFSET, 39,	/* 55 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 41, 0,	/* MITEM */
/* 00808 */ HB_P_LINEOFFSET, 40,	/* 56 */
	HB_P_PUSHSYMNEAR, 42,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 25, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00839) */
/* 00823 */ HB_P_LINEOFFSET, 41,	/* 57 */
	HB_P_PUSHSYMNEAR, 42,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 25, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ADDINT, 240, 255,	/* -16*/
	HB_P_POPVARIABLE, 40, 0,	/* MQTD_LIN */
/* 00839 */ HB_P_LINEOFFSET, 43,	/* 59 */
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* F 0*/
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_POPVARIABLE, 3, 0,	/* I */
/* 00850 */ HB_P_LINEOFFSET, 44,	/* 60 */
	HB_P_PUSHSYMNEAR, 37,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSTRSHORT, 64,	/* 64 */
	'I', 't', 'e', 'm', ' ', ' ', 'C', 'o', 'd', '.', ' ', 'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Q', 'u', 'a', 'n', 't', 'd', '.', ' ', ' ', 'V', 'l', 'r', '.', 'U', 'n', 'i', 't', '.', ' ', ' ', 'V', 'l', 'r', '.', 'T', 'o', 't', 'a', 'l', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 38, 0,	/* M_COLOR */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_DOSHORT, 8,
/* 00958 */ HB_P_LINEOFFSET, 45,	/* 61 */
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* MSUBTOTAL 0*/
/* 00964 */ HB_P_LINEOFFSET, 46,	/* 62 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* F 1*/
/* 00970 */ HB_P_LINEOFFSET, 47,	/* 63 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_PUSHSYMNEAR, 42,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 25, 0,	/* CONS_PARC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 11, 1,	/* 267 (abs: 01255) */
/* 00991 */ HB_P_LINEOFFSET, 48,	/* 64 */
	HB_P_PUSHVARIABLE, 40, 0,	/* MQTD_LIN */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_LESS,
	HB_P_JUMPFALSE, 243, 0,	/* 243 (abs: 01243) */
/* 01003 */ HB_P_LINEOFFSET, 49,	/* 65 */
	HB_P_PUSHSYMNEAR, 37,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHLOCALNEAR, 5,	/* F */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSYMNEAR, 43,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 44,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 45,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 46,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'9', ',', '9', '9', '9', '.', '9', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 46,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 46,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_DOSHORT, 8,
/* 01209 */ HB_P_LINEOFFSET, 50,	/* 66 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* F 1*/
/* 01215 */ HB_P_LINEOFFSET, 51,	/* 67 */
	HB_P_PUSHLOCALNEAR, 6,	/* MSUBTOTAL */
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 25, 0,	/* CONS_PARC */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_MULT,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 6,	/* MSUBTOTAL */
/* 01243 */ HB_P_LINEOFFSET, 53,	/* 69 */
	HB_P_PUSHVARIABLE, 3, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 3, 0,	/* I */
	HB_P_JUMP, 236, 254,	/* -276 (abs: 00976) */
/* 01255 */ HB_P_LINEOFFSET, 54,	/* 70 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01263 */ HB_P_LINEOFFSET, 56,	/* 72 */
	HB_P_PUSHLOCALNEAR, 6,	/* MSUBTOTAL */
	HB_P_PUSHLOCALNEAR, 7,	/* MCUSTO */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_DIVIDE,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_MULT,
	HB_P_POPLOCALNEAR, 6,	/* MSUBTOTAL */
/* 01278 */ HB_P_LINEOFFSET, 57,	/* 73 */
	HB_P_PUSHSYMNEAR, 37,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'T', ' ', 'O', ' ', 'T', ' ', 'A', ' ', 'L', ':', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 8,
/* 01323 */ HB_P_LINEOFFSET, 58,	/* 74 */
	HB_P_PUSHSYMNEAR, 37,	/* DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHSYMNEAR, 47,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 47,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* MSUBTOTAL */
	HB_P_PUSHSYMNEAR, 47,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'@', 'E', ' ', '9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHINT, 210, 0,	/* 210 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'a', 'r', 'i', 'a', 'l', ' ', 'b', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 45,	/* 45 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 8,
/* 01394 */ HB_P_LINEOFFSET, 59,	/* 75 */
	HB_P_PUSHSYMNEAR, 48,	/* WVW_PBENABLE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 4, 0,	/* NPBID */
	HB_P_TRUE,
	HB_P_DOSHORT, 3,
/* 01406 */ HB_P_LINEOFFSET, 60,	/* 76 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 17, 0,	/* MCOD_MERC */
/* 01412 */ HB_P_LINEOFFSET, 61,	/* 77 */
	HB_P_PUSHSYMNEAR, 29,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 30,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 31,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 'c', 'o', 'd', '_', 'm', 'e', 'r', 'c', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'9', '9', '9', '9', '9', 0, 
	HB_P_PUSHBLOCKSHORT, 25,	/* 25 */
	HB_P_PUSHSYMNEAR, 49,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 17, 0,	/* MCOD_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 01476) */
	HB_P_PUSHSYMNEAR, 50,	/* F4_MERC */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 17, 0,	/* MCOD_MERC */
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 01477) */
	HB_P_TRUE,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 32, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01495 */ HB_P_LINEOFFSET, 62,	/* 78 */
	HB_P_PUSHSYMNEAR, 51,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 20, 0,	/* GETLIST */
/* 01517 */ HB_P_LINEOFFSET, 63,	/* 79 */
	HB_P_PUSHSYMNEAR, 52,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01532) */
	HB_P_JUMP, 23, 2,	/* 535 (abs: 02064) */
/* 01532 */ HB_P_LINEOFFSET, 66,	/* 82 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 5, 0,	/* MPED_MERC */
/* 01540 */ HB_P_LINEOFFSET, 67,	/* 83 */
	HB_P_MESSAGE, 53, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 54,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'S', 'E', 'L', 'E', 'C', 'T', ' ', '*', ' ', 'F', 'R', 'O', 'M', ' ', 'm', 'a', 's', 't', 'p', 'r', 'o', 'd', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'c', 'o', 'd', 'i', 'g', 'o', ' ', '=', ' ', 0, 
	HB_P_PUSHSYMNEAR, 55,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 17, 0,	/* MCOD_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHMEMVARREF, 5, 0,	/* MPED_MERC */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 01608 */ HB_P_LINEOFFSET, 68,	/* 84 */
	HB_P_MESSAGE, 53, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 54,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 01632 */ HB_P_LINEOFFSET, 69,	/* 85 */
	HB_P_PUSHSYMNEAR, 39,	/* HB_ISNULL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 5, 0,	/* MPED_MERC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 50,	/* 50 (abs: 01692) */
/* 01644 */ HB_P_LINEOFFSET, 70,	/* 86 */
	HB_P_PUSHSYMNEAR, 56,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 36,	/* 36 */
	'C', 'o', 'd', 'i', 'g', 'o', ' ', 'd', 'a', ' ', 'm', 'e', 'r', 'c', 'a', 'd', 'o', 'r', 'i', 'a', ' ', 'n', 'a', 'o', ' ', 'c', 'a', 'd', 'a', 's', 't', 'r', 'a', 'd', 'o', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 15, 251,	/* -1265 (abs: 00424) */
/* 01692 */ HB_P_LINEOFFSET, 73,	/* 89 */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 9, 0,	/* MMERC */
/* 01705 */ HB_P_LINEOFFSET, 74,	/* 90 */
	HB_P_PUSHSYMNEAR, 23,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 01714 */ HB_P_LINEOFFSET, 75,	/* 91 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 1,
/* 01738 */ HB_P_LINEOFFSET, 77,	/* 93 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_POPVARIABLE, 57, 0,	/* MPRE */
/* 01747 */ HB_P_LINEOFFSET, 78,	/* 94 */
	HB_P_PUSHSYMNEAR, 27,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 28,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* TRANSFORM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'9', '9', '9', ',', '9', '9', '9', '.', '9', '9', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_DOSHORT, 1,
/* 01789 */ HB_P_LINEOFFSET, 79,	/* 95 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 1, 0,	/* MQTD */
/* 01795 */ HB_P_LINEOFFSET, 80,	/* 96 */
	HB_P_PUSHSYMNEAR, 29,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 30,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 31,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'q', 't', 'd', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'9', ',', '9', '9', '9', '.', '9', '9', '9', 0, 
	HB_P_PUSHBLOCKSHORT, 26,	/* 26 */
	HB_P_PUSHSYMNEAR, 49,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 01854) */
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_ZERO,
	HB_P_LESS,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01859) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 01860) */
	HB_P_TRUE,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 32, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01878 */ HB_P_LINEOFFSET, 81,	/* 97 */
	HB_P_PUSHSYMNEAR, 51,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 20, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 20, 0,	/* GETLIST */
/* 01900 */ HB_P_LINEOFFSET, 82,	/* 98 */
	HB_P_PUSHSYMNEAR, 52,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01915) */
	HB_P_JUMP, 48, 250,	/* -1488 (abs: 00424) */
/* 01915 */ HB_P_LINEOFFSET, 85,	/* 101 */
	HB_P_PUSHSYMNEAR, 58,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'a', ' ', 'I', 'n', 'c', 'l', 'u', 's', 'a', 'o', ' ', 'd', 'o', ' ', 'P', 'R', 'O', 'D', 'U', 'T', 'O', 0, 
	HB_P_PUSHVARIABLE, 59, 0,	/* M_QP */
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 59, 0,	/* M_QP */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	' ', 'Q', 'u', 'a', 'n', 't', 'i', 'd', 'a', 'd', 'e', ':', ' ', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 44,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 4,	/* MOPCAO */
/* 01996 */ HB_P_LINEOFFSET, 86,	/* 102 */
	HB_P_PUSHLOCALNEAR, 4,	/* MOPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 02017) */
	HB_P_PUSHSYMNEAR, 52,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02022) */
	HB_P_JUMP, 197, 249,	/* -1595 (abs: 00424) */
/* 02022 */ HB_P_LINEOFFSET, 89,	/* 105 */
	HB_P_PUSHSYMNEAR, 30,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 25, 0,	/* CONS_PARC */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHVARIABLE, 1, 0,	/* MQTD */
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHMEMVAR, 5, 0,	/* MPED_MERC */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYGEN, 4, 0,	/* 4 */
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 155, 249,	/* -1637 (abs: 00424) */
/* 02064 */ HB_P_LINEOFFSET, 93,	/* 109 */
	HB_P_PUSHSYMNEAR, 60,	/* SETMODE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHBYTE, 120,	/* 120 */
	HB_P_DOSHORT, 2,
/* 02075 */ HB_P_LINEOFFSET, 94,	/* 110 */
	HB_P_PUSHSYMNEAR, 61,	/* WVW_SETFONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'l', 'u', 'c', 'i', 'd', 'a', ' ', 'c', 'o', 'n', 's', 'o', 'l', 'e', 0, 
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHINT, 132, 3,	/* 900 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 6,
/* 02109 */ HB_P_LINEOFFSET, 95,	/* 111 */
	HB_P_PUSHSYMNEAR, 62,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02116 */ HB_P_LINEOFFSET, 96,	/* 112 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 02121 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

