/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <mastgrupo.prg>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\mastgrupo.prg /q /oc:\HTI\sismaster\mastgrupo.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.09.27 10:14:48 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "mastgrupo.prg"

HB_FUNC( MASTGRUPO );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( EXIBI_PRG );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( SELECT );
HB_FUNC_EXTERN( INDEXORD );
HB_FUNC_EXTERN( ABRIARQ );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( DBGOTOP );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( TBROWSEDB );
HB_FUNC_EXTERN( TBCOLUMNNEW );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( INKEY );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( ORDSETFOCUS );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( VAL );
HB_FUNC_EXTERN( MENSAGEM1 );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( DEVOUTPICT );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( OP_SIMNAO );
HB_FUNC_EXTERN( SR_CDBVALUE );
HB_FUNC_EXTERN( DBCLOSEAREA );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( CALCU );
HB_FUNC_EXTERN( DBCOMMIT );
HB_FUNC_EXTERN( GENKEY );
HB_FUNC_EXTERN( __MVRELEASE );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_MASTGRUPO )
{ "MASTGRUPO", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( MASTGRUPO )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "LOCAL4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "F4", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "EXIBI_PRG", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXIBI_PRG )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "EXEC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "SELECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SELECT )}, NULL },
{ "INDEXORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( INDEXORD )}, NULL },
{ "ABRIARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( ABRIARQ )}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "DBGOTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTOP )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "TBROWSEDB", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBROWSEDB )}, NULL },
{ "TBCOLUMNNEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBCOLUMNNEW )}, NULL },
{ "GRUPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CODIGO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "ADDCOLUMN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_HEADSEP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_COLSEP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "FORCESTABLE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "NKEY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "INKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INKEY )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "ORDSETFOCUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSETFOCUS )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "VAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VAL )}, NULL },
{ "MGRUPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM1", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM1 )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "DEVOUTPICT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUTPICT )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "OP_SIMNAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_SIMNAO )}, NULL },
{ "SR_CDBVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CDBVALUE )}, NULL },
{ "DBCLOSEAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCLOSEAREA )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "_CARGO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CALCU", {HB_FS_PUBLIC}, {HB_FUNCNAME( CALCU )}, NULL },
{ "MSUB_GRUPO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MDATA_SIS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBCOMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOMMIT )}, NULL },
{ "GENKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( GENKEY )}, NULL },
{ "__MVRELEASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVRELEASE )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_MASTGRUPO )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_MASTGRUPO
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_MASTGRUPO = hb_vm_SymbolInit_MASTGRUPO;
   #pragma data_seg()
#endif

HB_FUNC( MASTGRUPO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 19, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 7, 0,	/* 7 */
	HB_P_LOCALNEARSETSTR, 3, 10, 0,	/* MPRG 10*/
	'M', 'A', 'S', 'T', 'G', 'R', 'U', 'P', 'O', 0, 
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 13,	/* MCONS_GRU */
	HB_P_LOCALNEARSETINT, 15, 0, 0,	/* POINT 0*/
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYDIM, 1, 0,	/* 1 */
	HB_P_POPLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_PUSHSYMNEAR, 1,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 18,	/* MDESCRI */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 20,	/* MC_GRU */
	HB_P_LOCALNEARSETSTR, 21, 2, 0,	/* OPCAO 2*/
	' ', 0, 
/* 00056 */ HB_P_LINEOFFSET, 4,	/* 11 */
	HB_P_PUSHSYMNEAR, 1,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 2, 0,	/* LOCAL4 */
/* 00067 */ HB_P_LINEOFFSET, 5,	/* 12 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_POPVARIABLE, 3, 0,	/* F4 */
/* 00076 */ HB_P_LINEOFFSET, 6,	/* 13 */
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* F4CCI 0*/
	HB_P_PUSHLOCALNEAR, 7,	/* F4CCI */
	HB_P_POPLOCALNEAR, 6,	/* F4LCI */
/* 00086 */ HB_P_LINEOFFSET, 7,	/* 14 */
	HB_P_LOCALNEARSETINT, 8, 30, 0,	/* F4LBA 30*/
/* 00092 */ HB_P_LINEOFFSET, 8,	/* 15 */
	HB_P_LOCALNEARSETINT, 9, 42, 0,	/* F4CBA 42*/
/* 00098 */ HB_P_LINEOFFSET, 9,	/* 16 */
	HB_P_PUSHSYMNEAR, 4,	/* EXIBI_PRG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MPRG */
	HB_P_DOSHORT, 1,
/* 00107 */ HB_P_LINEOFFSET, 10,	/* 17 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 13,	/* MCONS_GRU */
/* 00114 */ HB_P_LINEOFFSET, 11,	/* 18 */
	HB_P_PUSHSYMNEAR, 5,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_PUSHBYTE, 73,	/* 73 */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'C', 'A', 'D', 'A', 'S', 'T', 'R', 'O', ' ', 'D', 'E', ' ', 'G', 'R', 'U', 'P', 'O', 'S', 0, 
	HB_P_DOSHORT, 5,
/* 00150 */ HB_P_LINEOFFSET, 12,	/* 19 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 40,	/* 40 */
	'S', 'E', 'L', 'E', 'C', 'T', ' ', '*', ' ', 'F', 'R', 'O', 'M', ' ', 'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', ' ', 'O', 'R', 'D', 'E', 'R', ' ', 'B', 'Y', ' ', 'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHLOCALREF, 13, 0,	/* MCONS_GRU */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00210 */ HB_P_LINEOFFSET, 13,	/* 20 */
	HB_P_PUSHSYMNEAR, 8,	/* SELECT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 10,	/* MPRE_SELE */
/* 00219 */ HB_P_LINEOFFSET, 14,	/* 21 */
	HB_P_PUSHSYMNEAR, 9,	/* INDEXORD */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 11,	/* MPRE_ORDE */
/* 00228 */ HB_P_LINEOFFSET, 15,	/* 22 */
	HB_P_PUSHSYMNEAR, 10,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00260) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00260 */ HB_P_LINEOFFSET, 17,	/* 24 */
	HB_P_PUSHSYMNEAR, 11,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 00275 */ HB_P_LINEOFFSET, 18,	/* 25 */
	HB_P_PUSHSYMNEAR, 12,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00282 */ HB_P_LINEOFFSET, 20,	/* 27 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00290 */ HB_P_LINEOFFSET, 21,	/* 28 */
	HB_P_PUSHSYMNEAR, 14,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* F4LCI */
	HB_P_PUSHLOCALNEAR, 7,	/* F4CCI */
	HB_P_PUSHLOCALNEAR, 8,	/* F4LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 9,	/* F4CBA */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 16,	/* OCONSPROD */
/* 00310 */ HB_P_LINEOFFSET, 22,	/* 29 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 00338 */ HB_P_LINEOFFSET, 23,	/* 30 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* GRUPO */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 00370 */ HB_P_LINEOFFSET, 24,	/* 31 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* I 0*/
/* 00376 */ HB_P_LINEOFFSET, 25,	/* 32 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 00417) */
/* 00394 */ HB_P_LINEOFFSET, 26,	/* 33 */
	HB_P_MESSAGE, 19, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00409 */ HB_P_LINEOFFSET, 27,	/* 34 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 00382) */
/* 00417 */ HB_P_LINEOFFSET, 28,	/* 35 */
	HB_P_MESSAGE, 20, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00431 */ HB_P_LINEOFFSET, 29,	/* 36 */
	HB_P_MESSAGE, 21, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00445 */ HB_P_LINEOFFSET, 30,	/* 37 */
	HB_P_MESSAGE, 22, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00455 */ HB_P_LINEOFFSET, 32,	/* 39 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 42,	/* 42 */
	'<', 'I', '>', 'n', 'c', 'l', 'u', 's', 'a', 'o', ' ', '-', ' ', '<', 'E', 'N', 'T', 'E', 'R', '>', ' ', 'p', '/', 'A', 'l', 't', 'e', 'r', 'a', 'r', ' ', 'o', 'u', ' ', 'E', 'x', 'c', 'l', 'u', 'i', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 00506 */ HB_P_LINEOFFSET, 33,	/* 40 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 24, 0,	/* NKEY */
/* 00512 */ HB_P_LINEOFFSET, 34,	/* 41 */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 00544) */
/* 00521 */ HB_P_LINEOFFSET, 35,	/* 42 */
	HB_P_MESSAGE, 22, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00531 */ HB_P_LINEOFFSET, 36,	/* 43 */
	HB_P_PUSHSYMNEAR, 25,	/* INKEY */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 24, 0,	/* NKEY */
	HB_P_JUMPNEAR, 226,	/* -30 (abs: 00512) */
/* 00544 */ HB_P_LINEOFFSET, 38,	/* 45 */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 43,	/* 43 (abs: 00595) */
/* 00554 */ HB_P_LINEOFFSET, 39,	/* 46 */
	HB_P_PUSHSYMNEAR, 26,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00561 */ HB_P_LINEOFFSET, 40,	/* 47 */
	HB_P_PUSHSYMNEAR, 11,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* MPRE_SELE */
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 11,	/* MPRE_ORDE */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00585) */
	HB_P_PUSHSYMNEAR, 27,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 11,	/* MPRE_ORDE */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 00586) */
	HB_P_PUSHNIL,
	HB_P_POP,
/* 00587 */ HB_P_LINEOFFSET, 41,	/* 48 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00595 */ HB_P_LINEOFFSET, 42,	/* 49 */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 46, 5,	/* 1326 (abs: 01929) */
/* 00606 */ HB_P_LINEOFFSET, 43,	/* 50 */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* MSUBGRU */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 00636) */
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 28,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	' ', ' ', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 94,	/* 94 (abs: 00730) */
/* 00638 */ HB_P_LINEOFFSET, 44,	/* 51 */
	HB_P_PUSHSYMNEAR, 29,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 80,	/* 80 */
	'E', 's', 't', 'a', 'r', ' ', 'f', 'a', 'z', 'e', 'n', 'd', 'o', ' ', 'a', 'l', 't', 'e', 'r', 'a', 'c', 'a', 'o', ' ', 'n', 'o', ' ', 'S', 'U', 'B', '-', 'G', 'R', 'U', 'P', 'O', ' ', 'p', 'o', 'r', ' ', 'i', 's', 's', 'o', ' ', 'n', 'a', 'o', ' ', 'p', 'o', 'd', 'e', ' ', 'a', 'l', 't', 'e', 'r', 'a', 'r', ' ', 'e', 's', 't', 'e', ' ', 'r', 'e', 'g', 'i', 's', 't', 'r', 'o', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 240, 254,	/* -272 (abs: 00455) */
/* 00730 */ HB_P_LINEOFFSET, 47,	/* 54 */
	HB_P_PUSHSYMNEAR, 30,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPMEMVAR, 31, 0,	/* MGRUPO */
/* 00744 */ HB_P_LINEOFFSET, 48,	/* 55 */
	HB_P_PUSHLOCALNEAR, 2,	/* MOP */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 112, 4,	/* 1136 (abs: 01889) */
/* 00756 */ HB_P_LINEOFFSET, 49,	/* 56 */
	HB_P_PUSHSYMNEAR, 32,	/* MENSAGEM1 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 28,	/* 28 */
	'D', 'e', 's', 'e', 'j', 'a', ' ', '<', 'A', '>', 'l', 't', 'e', 'r', 'a', 'r', ' ', '<', 'E', '>', 'x', 'c', 'l', 'u', 'i', 'r', ':', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'A', ',', 'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 21,	/* OPCAO */
/* 00805 */ HB_P_LINEOFFSET, 50,	/* 57 */
	HB_P_PUSHSYMNEAR, 33,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00820) */
	HB_P_JUMP, 150, 254,	/* -362 (abs: 00455) */
/* 00820 */ HB_P_LINEOFFSET, 52,	/* 59 */
	HB_P_PUSHLOCALNEAR, 21,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 180, 1,	/* 436 (abs: 01265) */
/* 00832 */ HB_P_LINEOFFSET, 53,	/* 60 */
	HB_P_PUSHSYMNEAR, 5,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 76,	/* 76 */
	HB_P_PUSHSTRSHORT, 20,	/* 20 */
	' ', 'A', ' ', 'L', ' ', 'T', ' ', 'E', ' ', 'R', ' ', 'A', ' ', 'C', ' ', 'A', ' ', 'O', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 00869 */ HB_P_LINEOFFSET, 55,	/* 62 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* GRUPO */
	HB_P_POPMEMVAR, 31, 0,	/* MGRUPO */
/* 00878 */ HB_P_LINEOFFSET, 56,	/* 63 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00886 */ HB_P_LINEOFFSET, 57,	/* 64 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'C', 'o', 'd', 'i', 'g', 'o', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00913 */ HB_P_LINEOFFSET, 58,	/* 65 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00940 */ HB_P_LINEOFFSET, 59,	/* 66 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 00949 */ HB_P_LINEOFFSET, 60,	/* 67 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 36,	/* DEVOUTPICT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'@', '@', 'R', ' ', '9', '9', '9', 0, 
	HB_P_DOSHORT, 2,
/* 00978 */ HB_P_LINEOFFSET, 61,	/* 68 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00986 */ HB_P_LINEOFFSET, 62,	/* 69 */
	HB_P_PUSHSYMNEAR, 37,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 38,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 40,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 01023) */
	HB_P_PUSHMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 01029) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'm', 'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 41, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 39, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01062 */ HB_P_LINEOFFSET, 63,	/* 70 */
	HB_P_PUSHSYMNEAR, 42,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 39, 0,	/* GETLIST */
/* 01084 */ HB_P_LINEOFFSET, 64,	/* 71 */
	HB_P_PUSHSYMNEAR, 33,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01099) */
	HB_P_JUMP, 159, 0,	/* 159 (abs: 01255) */
/* 01099 */ HB_P_LINEOFFSET, 67,	/* 74 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSYMNEAR, 43,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'a', ' ', 'A', 'L', 'T', 'E', 'R', 'A', 'C', 'A', 'O', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01144) */
	HB_P_JUMP, 240, 254,	/* -272 (abs: 00869) */
/* 01144 */ HB_P_LINEOFFSET, 70,	/* 77 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'U', 'P', 'D', 'A', 'T', 'E', ' ', 'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', ' ', 'S', 'E', 'T', ' ', 'g', 'r', 'u', 'p', 'o', ' ', ' ', '=', ' ', 0, 
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	' ', 'W', 'H', 'E', 'R', 'E', ' ', 'c', 'o', 'd', 'i', 'g', 'o', ' ', '=', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 01231 */ HB_P_LINEOFFSET, 71,	/* 78 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 01255 */ HB_P_LINEOFFSET, 74,	/* 81 */
	HB_P_PUSHSYMNEAR, 26,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 53, 1,	/* 309 (abs: 01571) */
/* 01265 */ HB_P_LINEOFFSET, 75,	/* 82 */
	HB_P_PUSHLOCALNEAR, 21,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 41, 1,	/* 297 (abs: 01571) */
/* 01277 */ HB_P_LINEOFFSET, 76,	/* 83 */
	HB_P_PUSHSYMNEAR, 5,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 76,	/* 76 */
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	' ', 'E', ' ', 'X', ' ', 'C', ' ', 'L', ' ', 'U', ' ', 'S', ' ', 'A', ' ', 'O', ' ', 0, 
	HB_P_DOSHORT, 5,
/* 01312 */ HB_P_LINEOFFSET, 77,	/* 84 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01320 */ HB_P_LINEOFFSET, 78,	/* 85 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'C', 'o', 'd', 'i', 'g', 'o', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 01347 */ HB_P_LINEOFFSET, 79,	/* 86 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 01374 */ HB_P_LINEOFFSET, 80,	/* 87 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 01383 */ HB_P_LINEOFFSET, 81,	/* 88 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 36,	/* DEVOUTPICT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'@', '@', 'R', ' ', '9', '9', '9', '-', '9', '9', 0, 
	HB_P_DOSHORT, 2,
/* 01415 */ HB_P_LINEOFFSET, 82,	/* 89 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* GRUPO */
	HB_P_DOSHORT, 1,
/* 01434 */ HB_P_LINEOFFSET, 83,	/* 90 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSYMNEAR, 43,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'a', ' ', 'E', 'X', 'C', 'L', 'U', 'S', 'A', 'O', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 01478) */
	HB_P_JUMP, 4, 252,	/* -1020 (abs: 00455) */
/* 01478 */ HB_P_LINEOFFSET, 86,	/* 93 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'D', 'E', 'L', 'E', 'T', 'E', ' ', 'F', 'R', 'O', 'M', ' ', 'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', ' ', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'c', 'o', 'd', 'i', 'g', 'o', ' ', '=', ' ', 0, 
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 01544 */ HB_P_LINEOFFSET, 87,	/* 94 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_JUMP, 126, 6,	/* 1662 (abs: 03230) */
/* 01571 */ HB_P_LINEOFFSET, 92,	/* 99 */
	HB_P_PUSHSYMNEAR, 45,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 01586 */ HB_P_LINEOFFSET, 93,	/* 100 */
	HB_P_PUSHSYMNEAR, 10,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 01618) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01618 */ HB_P_LINEOFFSET, 94,	/* 101 */
	HB_P_PUSHSYMNEAR, 11,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 01633 */ HB_P_LINEOFFSET, 95,	/* 102 */
	HB_P_PUSHSYMNEAR, 12,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01640 */ HB_P_LINEOFFSET, 97,	/* 104 */
	HB_P_PUSHSYMNEAR, 14,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* F4LCI */
	HB_P_PUSHLOCALNEAR, 7,	/* F4CCI */
	HB_P_PUSHLOCALNEAR, 8,	/* F4LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 9,	/* F4CBA */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 16,	/* OCONSPROD */
/* 01668 */ HB_P_LINEOFFSET, 98,	/* 105 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 62,	/* 62 */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 01714) */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_JUMPNEAR, 31,	/* 31 (abs: 01743) */
	HB_P_PUSHSYMNEAR, 28,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'-', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 28,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 01751 */ HB_P_LINEOFFSET, 99,	/* 106 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* GRUPO */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 01783 */ HB_P_LINEOFFSET, 100,	/* 107 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* I 0*/
/* 01789 */ HB_P_LINEOFFSET, 101,	/* 108 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 01830) */
/* 01807 */ HB_P_LINEOFFSET, 102,	/* 109 */
	HB_P_MESSAGE, 19, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01822 */ HB_P_LINEOFFSET, 103,	/* 110 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 01795) */
/* 01830 */ HB_P_LINEOFFSET, 104,	/* 111 */
	HB_P_MESSAGE, 20, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01844 */ HB_P_LINEOFFSET, 105,	/* 112 */
	HB_P_MESSAGE, 21, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01858 */ HB_P_LINEOFFSET, 106,	/* 113 */
	HB_P_MESSAGE, 47, 0,	/* _CARGO */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'*', '*', '*', '*', '*', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01876 */ HB_P_LINEOFFSET, 107,	/* 114 */
	HB_P_MESSAGE, 22, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 61, 5,	/* 1341 (abs: 03227) */
/* 01889 */ HB_P_LINEOFFSET, 109,	/* 116 */
	HB_P_PUSHSYMNEAR, 26,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01896 */ HB_P_LINEOFFSET, 110,	/* 117 */
	HB_P_PUSHSYMNEAR, 11,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* MPRE_SELE */
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 11,	/* MPRE_ORDE */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 01920) */
	HB_P_PUSHSYMNEAR, 27,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 11,	/* MPRE_ORDE */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 01921) */
	HB_P_PUSHNIL,
	HB_P_POP,
/* 01922 */ HB_P_LINEOFFSET, 111,	/* 118 */
	HB_P_PUSHMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01929 */ HB_P_LINEOFFSET, 113,	/* 120 */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_PUSHBYTE, 215,	/* -41 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 01949) */
/* 01939 */ HB_P_LINEOFFSET, 114,	/* 121 */
	HB_P_PUSHSYMNEAR, 48,	/* CALCU */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 45, 250,	/* -1491 (abs: 00455) */
/* 01949 */ HB_P_LINEOFFSET, 131,	/* 138 */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_PUSHBYTE, 73,	/* 73 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 9,	/* 9 (abs: 01967) */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 220, 3,	/* 988 (abs: 02955) */
/* 01970 */ HB_P_LINEOFFSET, 132,	/* 139 */
	HB_P_PUSHSYMNEAR, 5,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 76,	/* 76 */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'I', ' ', 'N', ' ', 'C', ' ', 'L', ' ', 'U', ' ', 'S', ' ', 'A', ' ', 'O', 0, 
	HB_P_DOSHORT, 5,
/* 02003 */ HB_P_LINEOFFSET, 134,	/* 141 */
	HB_P_PUSHSYMNEAR, 1,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPMEMVAR, 49, 0,	/* MSUB_GRUPO */
/* 02015 */ HB_P_LINEOFFSET, 135,	/* 142 */
	HB_P_PUSHSYMNEAR, 1,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPMEMVAR, 31, 0,	/* MGRUPO */
/* 02027 */ HB_P_LINEOFFSET, 136,	/* 143 */
	HB_P_PUSHSYMNEAR, 13,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 02035 */ HB_P_LINEOFFSET, 137,	/* 144 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'C', 'o', 'd', 'i', 'g', 'o', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 02062 */ HB_P_LINEOFFSET, 138,	/* 145 */
	HB_P_PUSHSYMNEAR, 34,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 35,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 02089 */ HB_P_LINEOFFSET, 139,	/* 146 */
	HB_P_PUSHSYMNEAR, 37,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 38,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 40,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 02126) */
	HB_P_PUSHMEMVAR, 49, 0,	/* MSUB_GRUPO */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 02132) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 49, 0,	/* MSUB_GRUPO */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'm', 's', 'u', 'b', '_', 'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'9', '9', '9', 0, 
	HB_P_PUSHBLOCKSHORT, 25,	/* 25 */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 49, 0,	/* MSUB_GRUPO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_LESS,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02175) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 02176) */
	HB_P_TRUE,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 41, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 39, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02194 */ HB_P_LINEOFFSET, 140,	/* 147 */
	HB_P_PUSHSYMNEAR, 42,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 39, 0,	/* GETLIST */
/* 02216 */ HB_P_LINEOFFSET, 141,	/* 148 */
	HB_P_PUSHSYMNEAR, 33,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02231) */
	HB_P_JUMP, 194, 1,	/* 450 (abs: 02678) */
/* 02231 */ HB_P_LINEOFFSET, 144,	/* 151 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 20,	/* MC_GRU */
/* 02238 */ HB_P_LINEOFFSET, 145,	/* 152 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 41,	/* 41 */
	'S', 'E', 'L', 'E', 'C', 'T', ' ', '*', ' ', 'F', 'R', 'O', 'M', ' ', 'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', ' ', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'c', 'o', 'd', 'i', 'g', 'o', ' ', '=', ' ', 0, 
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 49, 0,	/* MSUB_GRUPO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHLOCALREF, 20, 0,	/* MC_GRU */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 02308 */ HB_P_LINEOFFSET, 146,	/* 153 */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 20,	/* MC_GRU */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 49,	/* 49 (abs: 02368) */
/* 02321 */ HB_P_LINEOFFSET, 147,	/* 154 */
	HB_P_PUSHSYMNEAR, 29,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 35,	/* 35 */
	'J', 'a', ' ', 'e', 'x', 'i', 's', 't', 'e', ' ', 'e', 's', 't', 'e', ' ', 'G', 'R', 'U', 'P', 'O', '/', 'S', 'U', 'B', '-', 'G', 'R', 'U', 'P', 'O', '.', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 150, 254,	/* -362 (abs: 02003) */
/* 02368 */ HB_P_LINEOFFSET, 150,	/* 157 */
	HB_P_PUSHSYMNEAR, 37,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 38,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 40,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 02405) */
	HB_P_PUSHMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 02411) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'm', 'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 41, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 39, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02444 */ HB_P_LINEOFFSET, 151,	/* 158 */
	HB_P_PUSHSYMNEAR, 42,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 39, 0,	/* GETLIST */
/* 02466 */ HB_P_LINEOFFSET, 152,	/* 159 */
	HB_P_PUSHSYMNEAR, 33,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02481) */
	HB_P_JUMP, 37, 254,	/* -475 (abs: 02003) */
/* 02481 */ HB_P_LINEOFFSET, 155,	/* 162 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSYMNEAR, 43,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'a', ' ', 'I', 'n', 'c', 'l', 'u', 's', 'a', 'o', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 02525) */
	HB_P_JUMP, 249, 253,	/* -519 (abs: 02003) */
/* 02525 */ HB_P_LINEOFFSET, 158,	/* 165 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 66,	/* 66 */
	'I', 'N', 'S', 'E', 'R', 'T', ' ', 'I', 'N', 'T', 'O', ' ', 'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', ' ', '(', 'c', 'o', 'd', 'i', 'g', 'o', ',', 'g', 'r', 'u', 'p', 'o', ',', 'd', 'a', 't', 'a', '_', 'c', 'a', 'd', ',', 's', 'r', '_', 'd', 'e', 'l', 'e', 't', 'e', 'd', ')', ' ', 'V', 'A', 'L', 'U', 'E', 'S', ' ', '(', 0, 
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 49, 0,	/* MSUB_GRUPO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	',', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 31, 0,	/* MGRUPO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	',', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 44,	/* SR_CDBVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 50, 0,	/* MDATA_SIS */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	',', 39, ' ', 39, ')', 0, 
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02654 */ HB_P_LINEOFFSET, 159,	/* 166 */
	HB_P_MESSAGE, 6, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 7,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02678 */ HB_P_LINEOFFSET, 162,	/* 169 */
	HB_P_PUSHSYMNEAR, 26,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02685 */ HB_P_LINEOFFSET, 164,	/* 171 */
	HB_P_PUSHSYMNEAR, 45,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 02700 */ HB_P_LINEOFFSET, 165,	/* 172 */
	HB_P_PUSHSYMNEAR, 10,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'm', 'a', 's', 't', 'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 02732) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 02732 */ HB_P_LINEOFFSET, 166,	/* 173 */
	HB_P_PUSHSYMNEAR, 11,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_DOSHORT, 1,
/* 02747 */ HB_P_LINEOFFSET, 167,	/* 174 */
	HB_P_PUSHSYMNEAR, 51,	/* DBCOMMIT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02754 */ HB_P_LINEOFFSET, 168,	/* 175 */
	HB_P_PUSHSYMNEAR, 12,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02761 */ HB_P_LINEOFFSET, 170,	/* 177 */
	HB_P_PUSHSYMNEAR, 14,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* F4LCI */
	HB_P_PUSHLOCALNEAR, 7,	/* F4CCI */
	HB_P_PUSHLOCALNEAR, 8,	/* F4LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 9,	/* F4CBA */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 16,	/* OCONSPROD */
/* 02789 */ HB_P_LINEOFFSET, 171,	/* 178 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 02817 */ HB_P_LINEOFFSET, 172,	/* 179 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* GRUPO */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 02849 */ HB_P_LINEOFFSET, 173,	/* 180 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* I 0*/
/* 02855 */ HB_P_LINEOFFSET, 174,	/* 181 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 02896) */
/* 02873 */ HB_P_LINEOFFSET, 175,	/* 182 */
	HB_P_MESSAGE, 19, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 02888 */ HB_P_LINEOFFSET, 176,	/* 183 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 02861) */
/* 02896 */ HB_P_LINEOFFSET, 177,	/* 184 */
	HB_P_MESSAGE, 20, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 02910 */ HB_P_LINEOFFSET, 178,	/* 185 */
	HB_P_MESSAGE, 21, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 02924 */ HB_P_LINEOFFSET, 179,	/* 186 */
	HB_P_MESSAGE, 47, 0,	/* _CARGO */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'*', '*', '*', '*', '*', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 02942 */ HB_P_LINEOFFSET, 180,	/* 187 */
	HB_P_MESSAGE, 22, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 63, 246,	/* -2497 (abs: 00455) */
/* 02955 */ HB_P_LINEOFFSET, 182,	/* 189 */
	HB_P_PUSHSYMNEAR, 52,	/* GENKEY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHVARIABLE, 24, 0,	/* NKEY */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPFALSE, 40, 246,	/* -2520 (abs: 00455) */
/* 02978 */ HB_P_LINEOFFSET, 183,	/* 190 */
	HB_P_PUSHSYMNEAR, 14,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* F4LCI */
	HB_P_PUSHLOCALNEAR, 7,	/* F4CCI */
	HB_P_PUSHLOCALNEAR, 8,	/* F4LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 9,	/* F4CBA */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'g', 'r', 'u', 'p', 'o', 0, 
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 16,	/* OCONSPROD */
/* 03006 */ HB_P_LINEOFFSET, 184,	/* 191 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 62,	/* 62 */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 03052) */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_JUMPNEAR, 31,	/* 31 (abs: 03081) */
	HB_P_PUSHSYMNEAR, 28,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_ONE,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'-', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 28,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* CODIGO */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 03089 */ HB_P_LINEOFFSET, 185,	/* 192 */
	HB_P_PUSHSYMNEAR, 15,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'D', 'e', 's', 'c', 'r', 'i', 'c', 'a', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 16,	/* GRUPO */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* GRUPO */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 17, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 03121 */ HB_P_LINEOFFSET, 186,	/* 193 */
	HB_P_LOCALNEARSETINT, 12, 0, 0,	/* I 0*/
/* 03127 */ HB_P_LINEOFFSET, 187,	/* 194 */
	HB_P_LOCALNEARSETINT, 12, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 03168) */
/* 03145 */ HB_P_LINEOFFSET, 188,	/* 195 */
	HB_P_MESSAGE, 19, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 17,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 12,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03160 */ HB_P_LINEOFFSET, 189,	/* 196 */
	HB_P_LOCALNEARADDINT, 12, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 03133) */
/* 03168 */ HB_P_LINEOFFSET, 190,	/* 197 */
	HB_P_MESSAGE, 20, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03182 */ HB_P_LINEOFFSET, 191,	/* 198 */
	HB_P_MESSAGE, 21, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03196 */ HB_P_LINEOFFSET, 192,	/* 199 */
	HB_P_MESSAGE, 47, 0,	/* _CARGO */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'*', '*', '*', '*', '*', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03214 */ HB_P_LINEOFFSET, 193,	/* 200 */
	HB_P_MESSAGE, 22, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 16,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 47, 245,	/* -2769 (abs: 00455) */
	HB_P_JUMP, 44, 245,	/* -2772 (abs: 00455) */
/* 03230 */ HB_P_LINEOFFSET, 197,	/* 204 */
	HB_P_PUSHSYMNEAR, 11,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* MPRE_SELE */
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 11,	/* MPRE_ORDE */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 03254) */
	HB_P_PUSHSYMNEAR, 27,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 11,	/* MPRE_ORDE */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 03255) */
	HB_P_PUSHNIL,
	HB_P_POP,
/* 03256 */ HB_P_LINEOFFSET, 198,	/* 205 */
	HB_P_PUSHSYMNEAR, 53,	/* __MVRELEASE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
/* 03268 */ HB_P_LINEOFFSET, 199,	/* 206 */
	HB_P_PUSHSYMNEAR, 26,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03275 */ HB_P_LINEOFFSET, 200,	/* 207 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 03280 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

