/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <SACCID.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\SACCID.PRG /q /oc:\HTI\sismaster\SACCID.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.09.27 10:14:44 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "SACCID.PRG"

HB_FUNC( SACCID );
HB_FUNC_EXTERN( VER_NIVEL );
HB_FUNC_EXTERN( ABRIARQ );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( SELECT );
HB_FUNC_EXTERN( INDEXORD );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( ORDSETFOCUS );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( DBSEEK );
HB_FUNC_EXTERN( EOF );
HB_FUNC_EXTERN( TBROWSEDB );
HB_FUNC_EXTERN( TBCOLUMNNEW );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( BOTAO );
HB_FUNC_EXTERN( INKEY );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( SAVESCREEN );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( VER_CIDADE );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( RESTSCREEN );
HB_FUNC_EXTERN( DBGOTOP );
HB_FUNC_EXTERN( OP_SIMNAO );
HB_FUNC_EXTERN( ADIREG );
HB_FUNC_EXTERN( DBCOMMITALL );
HB_FUNC_EXTERN( DBUNLOCK );
HB_FUNC_EXTERN( RECNO );
HB_FUNC_EXTERN( DBGOTO );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( MENSAGEM1 );
HB_FUNC_EXTERN( BLOQREG );
HB_FUNC_EXTERN( DBSKIP );
HB_FUNC_EXTERN( DBUNLOCKALL );
HB_FUNC_EXTERN( SETCOR );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( BLOQARQ );
HB_FUNC_EXTERN( DBDELETE );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( READKILL );
HB_FUNC_EXTERN( GENKEY );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( __MVRELEASE );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SACCID )
{ "SACCID", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( SACCID )}, NULL },
{ "VER_NIVEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VER_NIVEL )}, NULL },
{ "NIVEL_ACESS", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ABRIARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( ABRIARQ )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "SELECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SELECT )}, NULL },
{ "INDEXORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( INDEXORD )}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "ORDSETFOCUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSETFOCUS )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "CID", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "DBSEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSEEK )}, NULL },
{ "EOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOF )}, NULL },
{ "TBROWSEDB", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBROWSEDB )}, NULL },
{ "TBCOLUMNNEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBCOLUMNNEW )}, NULL },
{ "CIDADE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "CEP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "UF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COD_CID", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "ADDCOLUMN", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_HEADSEP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_COLSEP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "BOTAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOTAO )}, NULL },
{ "FORCESTABLE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "INKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INKEY )}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "SAVESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVESCREEN )}, NULL },
{ "MUF", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "VER_CIDADE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VER_CIDADE )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "RESTSCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESTSCREEN )}, NULL },
{ "DBGOTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTOP )}, NULL },
{ "OP_SIMNAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_SIMNAO )}, NULL },
{ "ADIREG", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADIREG )}, NULL },
{ "COD_OPERADO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COD_OPE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "DBCOMMITALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOMMITALL )}, NULL },
{ "DBUNLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCK )}, NULL },
{ "RECNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( RECNO )}, NULL },
{ "DBGOTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTO )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "MCIDADE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MENSAGEM1", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM1 )}, NULL },
{ "BLOQREG", {HB_FS_PUBLIC}, {HB_FUNCNAME( BLOQREG )}, NULL },
{ "CLI", {HB_FS_PUBLIC | HB_FS_MEMVAR}, {NULL}, NULL },
{ "DBSKIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSKIP )}, NULL },
{ "DBUNLOCKALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUNLOCKALL )}, NULL },
{ "SETCOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCOR )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "BLOQARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( BLOQARQ )}, NULL },
{ "DBDELETE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBDELETE )}, NULL },
{ "EXEC", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "READKILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READKILL )}, NULL },
{ "GENKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( GENKEY )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "__MVRELEASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVRELEASE )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_SACCID )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_SACCID
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_SACCID = hb_vm_SymbolInit_SACCID;
   #pragma data_seg()
#endif

HB_FUNC( SACCID )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 24, 5,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 12, 0,	/* 12 */
	HB_P_LOCALNEARSETSTR, 6, 7, 0,	/* MPRG 7*/
	'S', 'A', 'C', 'C', 'I', 'D', 0, 
	HB_P_LOCALNEARSETSTR, 7, 20, 0,	/* MTITULO 20*/
	'C', 'A', 'D', 'A', 'S', 'T', 'R', 'O', ' ', 'D', 'E', ' ', 'C', 'I', 'D', 'A', 'D', 'E', 'S', 0, 
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYDIM, 1, 0,	/* 1 */
	HB_P_POPLOCALNEAR, 18,	/* OCOLPROD */
/* 00048 */ HB_P_LINEOFFSET, 4,	/* 16 */
	HB_P_PUSHSYMNEAR, 1,	/* VER_NIVEL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* MPRG */
	HB_P_PUSHLOCALNEAR, 7,	/* MTITULO */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'1', '5', 0, 
	HB_P_PUSHMEMVAR, 2, 0,	/* NIVEL_ACESS */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'M', 'B', 'I', 'E', 0, 
	HB_P_FUNCTIONSHORT, 6,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00083) */
/* 00078 */ HB_P_LINEOFFSET, 5,	/* 17 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00083 */ HB_P_LINEOFFSET, 7,	/* 19 */
	HB_P_LOCALNEARSETINT, 11, 0, 0,	/* F7CCI 0*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_POPLOCALNEAR, 10,	/* F7LCI */
/* 00093 */ HB_P_LINEOFFSET, 8,	/* 20 */
	HB_P_LOCALNEARSETINT, 12, 22, 0,	/* F7LBA 22*/
/* 00099 */ HB_P_LINEOFFSET, 9,	/* 21 */
	HB_P_LOCALNEARSETINT, 13, 55, 0,	/* F7CBA 55*/
/* 00105 */ HB_P_LINEOFFSET, 10,	/* 22 */
	HB_P_PUSHSYMNEAR, 3,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'a', 's', 't', 'c', 'l', 'i', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00133) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00133 */ HB_P_LINEOFFSET, 12,	/* 24 */
	HB_P_PUSHSYMNEAR, 4,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHBYTE, 65,	/* 65 */
	HB_P_PUSHLOCALNEAR, 7,	/* MTITULO */
	HB_P_DOSHORT, 5,
/* 00150 */ HB_P_LINEOFFSET, 13,	/* 25 */
	HB_P_PUSHSYMNEAR, 5,	/* SELECT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 14,	/* F7MSELE */
/* 00159 */ HB_P_LINEOFFSET, 14,	/* 26 */
	HB_P_PUSHSYMNEAR, 6,	/* INDEXORD */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 15,	/* F7MORDE */
/* 00168 */ HB_P_LINEOFFSET, 16,	/* 28 */
	HB_P_PUSHSYMNEAR, 3,	/* ABRIARQ */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 'a', 'c', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPTRUENEAR, 5,	/* 5 (abs: 00195) */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00195 */ HB_P_LINEOFFSET, 17,	/* 29 */
	HB_P_PUSHSYMNEAR, 7,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00214 */ HB_P_LINEOFFSET, 19,	/* 31 */
	HB_P_PUSHSYMNEAR, 9,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 60,	/* 60 (abs: 00283) */
/* 00225 */ HB_P_LINEOFFSET, 20,	/* 32 */
	HB_P_PUSHLOCALNEAR, 4,	/* MUF_F */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00250) */
/* 00233 */ HB_P_LINEOFFSET, 21,	/* 33 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 11,	/* DBSEEK */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
	HB_P_POPALIAS,
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00268) */
/* 00250 */ HB_P_LINEOFFSET, 23,	/* 35 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 11,	/* DBSEEK */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_PUSHLOCALNEAR, 4,	/* MUF_F */
	HB_P_PLUS,
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
	HB_P_POPALIAS,
/* 00268 */ HB_P_LINEOFFSET, 25,	/* 37 */
	HB_P_PUSHSYMNEAR, 12,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 8,	/* 8 (abs: 00283) */
/* 00277 */ HB_P_LINEOFFSET, 26,	/* 38 */
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_POPLOCALNEAR, 23,	/* MCID */
/* 00283 */ HB_P_LINEOFFSET, 29,	/* 41 */
	HB_P_PUSHSYMNEAR, 13,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* F7LCI */
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 17,	/* OCONSPROD */
/* 00300 */ HB_P_LINEOFFSET, 30,	/* 42 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'i', 'd', 'a', 'd', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 00328 */ HB_P_LINEOFFSET, 31,	/* 43 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'C', 'E', 'P', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 00354 */ HB_P_LINEOFFSET, 32,	/* 44 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'U', 'F', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 00379 */ HB_P_LINEOFFSET, 33,	/* 45 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 18,	/* COD_CID */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPOP,
/* 00408 */ HB_P_LINEOFFSET, 35,	/* 47 */
	HB_P_LOCALNEARSETINT, 19, 0, 0,	/* F7I 0*/
/* 00414 */ HB_P_LINEOFFSET, 36,	/* 48 */
	HB_P_LOCALNEARSETINT, 19, 1, 0,	/* F7I 1*/
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_PUSHSYMNEAR, 19,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 00455) */
/* 00432 */ HB_P_LINEOFFSET, 37,	/* 49 */
	HB_P_MESSAGE, 20, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00447 */ HB_P_LINEOFFSET, 38,	/* 50 */
	HB_P_LOCALNEARADDINT, 19, 1, 0,	/* F7I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 00420) */
/* 00455 */ HB_P_LINEOFFSET, 39,	/* 51 */
	HB_P_MESSAGE, 21, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00469 */ HB_P_LINEOFFSET, 40,	/* 52 */
	HB_P_MESSAGE, 22, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00483 */ HB_P_LINEOFFSET, 42,	/* 54 */
	HB_P_PUSHLOCALNEAR, 1,	/* MOP */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 76,	/* 76 (abs: 00568) */
/* 00494 */ HB_P_LINEOFFSET, 43,	/* 55 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 63,	/* 63 */
	'<', 'P', '>', 'e', 's', 'q', 'u', 'i', 's', 'a', ' ', '<', 'I', '>', 'n', 'c', 'l', 'u', 's', 'a', 'o', ' ', '<', 'E', 'N', 'T', 'E', 'R', '>', 'p', '/', 'A', 'l', 't', 'e', 'r', 'a', 'r', ' ', 'e', ' ', 'E', 'x', 'c', 'l', 'u', 'i', 'r', ' ', '<', 'E', 'S', 'C', '>', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 75,	/* 75 (abs: 00641) */
/* 00568 */ HB_P_LINEOFFSET, 45,	/* 57 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 64,	/* 64 */
	'<', 'P', 'G', 'U', 'P', '>', ' ', '<', 'P', 'G', 'D', 'N', '>', ' ', '<', 'P', '>', 'e', 's', 'q', 'u', 'i', 's', 'a', ' ', '<', 'I', '>', 'n', 'c', 'l', 'u', 's', 'a', 'o', ' ', '<', 'E', 'N', 'T', 'E', 'R', '>', ' ', 'C', 'o', 'n', 'f', '.', ' ', '<', 'E', 'S', 'C', '>', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 00641 */ HB_P_LINEOFFSET, 47,	/* 59 */
	HB_P_PUSHSYMNEAR, 24,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_DOSHORT, 4,
/* 00662 */ HB_P_LINEOFFSET, 48,	/* 60 */
	HB_P_LOCALNEARSETINT, 20, 0, 0,	/* F7NKEY 0*/
/* 00668 */ HB_P_LINEOFFSET, 49,	/* 61 */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 24,	/* 24 (abs: 00698) */
/* 00676 */ HB_P_LINEOFFSET, 50,	/* 62 */
	HB_P_MESSAGE, 25, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00686 */ HB_P_LINEOFFSET, 51,	/* 63 */
	HB_P_PUSHSYMNEAR, 26,	/* INKEY */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 20,	/* F7NKEY */
	HB_P_JUMPNEAR, 228,	/* -28 (abs: 00668) */
/* 00698 */ HB_P_LINEOFFSET, 53,	/* 65 */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 44,	/* 44 (abs: 00749) */
/* 00707 */ HB_P_LINEOFFSET, 54,	/* 66 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 9,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00724) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 3,	/* MEMPTY */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00735) */
/* 00726 */ HB_P_LINEOFFSET, 55,	/* 67 */
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_POPLOCALNEAR, 23,	/* MCID */
	HB_P_JUMP, 38, 13,	/* 3366 (abs: 04098) */
/* 00735 */ HB_P_LINEOFFSET, 57,	/* 69 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 23,	/* MCID */
	HB_P_JUMP, 24, 13,	/* 3352 (abs: 04098) */
/* 00749 */ HB_P_LINEOFFSET, 60,	/* 72 */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_PUSHBYTE, 73,	/* 73 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 00765) */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSE, 35, 4,	/* 1059 (abs: 01824) */
/* 00768 */ HB_P_LINEOFFSET, 61,	/* 73 */
	HB_P_PUSHSYMNEAR, 28,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 24,	/* TELA1 */
/* 00783 */ HB_P_LINEOFFSET, 64,	/* 76 */
	HB_P_PUSHSYMNEAR, 7,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 00803 */ HB_P_LINEOFFSET, 67,	/* 79 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 43,	/* 43 */
	'D', 'i', 'g', 'i', 't', 'e', ' ', 'o', ' ', 'N', 'o', 'm', 'e', ' ', 'd', 'a', ' ', 'C', 'i', 'd', 'a', 'd', 'e', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', ' ', 'p', '/', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 00855 */ HB_P_LINEOFFSET, 68,	/* 80 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 22,	/* MCOD_CID */
/* 00866 */ HB_P_LINEOFFSET, 69,	/* 81 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 23,	/* MCID */
/* 00877 */ HB_P_LINEOFFSET, 70,	/* 82 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 28,	/* MCEP_CID */
/* 00888 */ HB_P_LINEOFFSET, 71,	/* 83 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 29,	/* MUF_CID */
/* 00899 */ HB_P_LINEOFFSET, 72,	/* 84 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPMEMVAR, 29, 0,	/* MUF */
/* 00911 */ HB_P_LINEOFFSET, 73,	/* 85 */
	HB_P_PUSHSYMNEAR, 24,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	' ', 'I', 'n', 'c', 'l', 'u', 's', 'a', 'o', ' ', 'd', 'a', ' ', 'C', 'i', 'd', 'a', 'd', 'e', ' ', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_DOSHORT, 7,
/* 00966 */ HB_P_LINEOFFSET, 75,	/* 87 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	23, 0,	/* MCID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 01011) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 01016) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHBLOCK, 18, 0,	/* 18 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	23, 0,	/* MCID */
	HB_P_PUSHSYMNEAR, 34,	/* VER_CIDADE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01064 */ HB_P_LINEOFFSET, 76,	/* 88 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 29, 0,	/* 29*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	28, 0,	/* MCEP_CID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 01109) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 01114) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'c', 'e', 'p', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01149 */ HB_P_LINEOFFSET, 77,	/* 89 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 38, 0,	/* 38*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	29, 0,	/* MUF_CID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 01194) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 01199) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'u', 'f', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01233 */ HB_P_LINEOFFSET, 78,	/* 90 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 42, 0,	/* 42*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	22, 0,	/* MCOD_CID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 01278) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 01283) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'c', 'o', 'd', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01318 */ HB_P_LINEOFFSET, 79,	/* 91 */
	HB_P_PUSHSYMNEAR, 36,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 32, 0,	/* GETLIST */
/* 01340 */ HB_P_LINEOFFSET, 80,	/* 92 */
	HB_P_PUSHSYMNEAR, 37,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 27,	/* 27 (abs: 01377) */
/* 01352 */ HB_P_LINEOFFSET, 81,	/* 93 */
	HB_P_PUSHSYMNEAR, 38,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 24,	/* TELA1 */
	HB_P_DOSHORT, 5,
/* 01367 */ HB_P_LINEOFFSET, 82,	/* 94 */
	HB_P_PUSHSYMNEAR, 39,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 161, 10,	/* 2721 (abs: 04095) */
/* 01377 */ HB_P_LINEOFFSET, 85,	/* 97 */
	HB_P_LOCALNEARSETSTR, 25, 2, 0,	/* OPCAO 2*/
	'S', 0, 
/* 01385 */ HB_P_LINEOFFSET, 86,	/* 98 */
	HB_P_PUSHSYMNEAR, 40,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'I', 'n', 'c', 'l', 'u', 's', 'a', 'o', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 25,	/* OPCAO */
/* 01419 */ HB_P_LINEOFFSET, 87,	/* 99 */
	HB_P_PUSHLOCALNEAR, 25,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 123, 253,	/* -645 (abs: 00783) */
/* 01431 */ HB_P_LINEOFFSET, 88,	/* 100 */
	HB_P_PUSHSYMNEAR, 41,	/* ADIREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSE, 70, 1,	/* 326 (abs: 01764) */
/* 01441 */ HB_P_LINEOFFSET, 89,	/* 101 */
	HB_P_PUSHLOCALNEAR, 22,	/* MCOD_CID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 18,	/* COD_CID */
/* 01449 */ HB_P_LINEOFFSET, 90,	/* 102 */
	HB_P_PUSHLOCALNEAR, 23,	/* MCID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 15,	/* CIDADE */
/* 01457 */ HB_P_LINEOFFSET, 91,	/* 103 */
	HB_P_PUSHLOCALNEAR, 28,	/* MCEP_CID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 16,	/* CEP */
/* 01465 */ HB_P_LINEOFFSET, 92,	/* 104 */
	HB_P_PUSHLOCALNEAR, 29,	/* MUF_CID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 17,	/* UF */
/* 01473 */ HB_P_LINEOFFSET, 93,	/* 105 */
	HB_P_PUSHMEMVAR, 42, 0,	/* COD_OPERADO */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 43,	/* COD_OPE */
/* 01482 */ HB_P_LINEOFFSET, 94,	/* 106 */
	HB_P_PUSHSYMNEAR, 44,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01489 */ HB_P_LINEOFFSET, 95,	/* 107 */
	HB_P_PUSHSYMNEAR, 45,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01496 */ HB_P_LINEOFFSET, 96,	/* 108 */
	HB_P_PUSHSYMNEAR, 46,	/* RECNO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 26,	/* MREG */
/* 01505 */ HB_P_LINEOFFSET, 97,	/* 109 */
	HB_P_PUSHSYMNEAR, 38,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 24,	/* TELA1 */
	HB_P_DOSHORT, 5,
/* 01520 */ HB_P_LINEOFFSET, 99,	/* 111 */
	HB_P_PUSHSYMNEAR, 7,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01539 */ HB_P_LINEOFFSET, 100,	/* 112 */
	HB_P_PUSHSYMNEAR, 47,	/* DBGOTO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 26,	/* MREG */
	HB_P_DOSHORT, 1,
/* 01548 */ HB_P_LINEOFFSET, 102,	/* 114 */
	HB_P_PUSHSYMNEAR, 13,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* F7LCI */
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 17,	/* OCONSPROD */
/* 01568 */ HB_P_LINEOFFSET, 103,	/* 115 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'i', 'd', 'a', 'd', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 01596 */ HB_P_LINEOFFSET, 104,	/* 116 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'C', 'E', 'P', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 01622 */ HB_P_LINEOFFSET, 105,	/* 117 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'U', 'F', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 01647 */ HB_P_LINEOFFSET, 106,	/* 118 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 18,	/* COD_CID */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPOP,
/* 01676 */ HB_P_LINEOFFSET, 107,	/* 119 */
	HB_P_LOCALNEARSETINT, 19, 0, 0,	/* F7I 0*/
/* 01682 */ HB_P_LINEOFFSET, 108,	/* 120 */
	HB_P_LOCALNEARSETINT, 19, 1, 0,	/* F7I 1*/
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_PUSHSYMNEAR, 19,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 01723) */
/* 01700 */ HB_P_LINEOFFSET, 109,	/* 121 */
	HB_P_MESSAGE, 20, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01715 */ HB_P_LINEOFFSET, 110,	/* 122 */
	HB_P_LOCALNEARADDINT, 19, 1, 0,	/* F7I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 01688) */
/* 01723 */ HB_P_LINEOFFSET, 111,	/* 123 */
	HB_P_MESSAGE, 21, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01737 */ HB_P_LINEOFFSET, 112,	/* 124 */
	HB_P_MESSAGE, 22, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01751 */ HB_P_LINEOFFSET, 113,	/* 125 */
	HB_P_MESSAGE, 25, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 30, 9,	/* 2334 (abs: 04095) */
/* 01764 */ HB_P_LINEOFFSET, 116,	/* 128 */
	HB_P_PUSHSYMNEAR, 48,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'A', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
/* 01812 */ HB_P_LINEOFFSET, 117,	/* 129 */
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 242, 251,	/* -1038 (abs: 00783) */
/* 01824 */ HB_P_LINEOFFSET, 122,	/* 134 */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 226, 7,	/* 2018 (abs: 03849) */
/* 01834 */ HB_P_LINEOFFSET, 123,	/* 135 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 18,	/* COD_CID */
	HB_P_POPLOCALNEAR, 22,	/* MCOD_CID */
/* 01842 */ HB_P_LINEOFFSET, 124,	/* 136 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 9,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 01860) */
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 12,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 01870) */
/* 01862 */ HB_P_LINEOFFSET, 125,	/* 137 */
	HB_P_PUSHLOCALNEAR, 2,	/* MCIDA */
	HB_P_POPLOCALNEAR, 23,	/* MCID */
	HB_P_JUMPNEAR, 10,	/* 10 (abs: 01878) */
/* 01870 */ HB_P_LINEOFFSET, 127,	/* 139 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_POPLOCALNEAR, 23,	/* MCID */
/* 01878 */ HB_P_LINEOFFSET, 129,	/* 141 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_POPMEMVAR, 49, 0,	/* MCIDADE */
/* 01887 */ HB_P_LINEOFFSET, 130,	/* 142 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_POPLOCALNEAR, 27,	/* MCID_AUX */
/* 01895 */ HB_P_LINEOFFSET, 131,	/* 143 */
	HB_P_PUSHSYMNEAR, 9,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MCP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 01914) */
/* 01906 */ HB_P_LINEOFFSET, 132,	/* 144 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_POPLOCALNEAR, 5,	/* MCP */
/* 01914 */ HB_P_LINEOFFSET, 134,	/* 146 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_POPLOCALNEAR, 28,	/* MCEP_CID */
/* 01922 */ HB_P_LINEOFFSET, 135,	/* 147 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_POPMEMVAR, 29, 0,	/* MUF */
/* 01931 */ HB_P_LINEOFFSET, 136,	/* 148 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_POPLOCALNEAR, 29,	/* MUF_CID */
/* 01939 */ HB_P_LINEOFFSET, 137,	/* 149 */
	HB_P_PUSHLOCALNEAR, 1,	/* MOP */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 132, 6,	/* 1668 (abs: 03616) */
/* 01951 */ HB_P_LINEOFFSET, 138,	/* 150 */
	HB_P_PUSHSYMNEAR, 50,	/* MENSAGEM1 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 28,	/* 28 */
	'D', 'e', 's', 'e', 'j', 'a', ' ', '<', 'A', '>', 'l', 't', 'e', 'r', 'a', 'r', ' ', '<', 'E', '>', 'x', 'c', 'l', 'u', 'i', 'r', ':', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'A', ',', 'E', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 21,	/* F7OPCAO */
/* 02000 */ HB_P_LINEOFFSET, 139,	/* 151 */
	HB_P_PUSHSYMNEAR, 37,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 02030) */
/* 02012 */ HB_P_LINEOFFSET, 140,	/* 152 */
	HB_P_PUSHSYMNEAR, 38,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 24,	/* TELA1 */
	HB_P_DOSHORT, 5,
	HB_P_JUMP, 23, 8,	/* 2071 (abs: 04098) */
/* 02030 */ HB_P_LINEOFFSET, 142,	/* 154 */
	HB_P_PUSHLOCALNEAR, 21,	/* F7OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 163, 3,	/* 931 (abs: 02970) */
/* 02042 */ HB_P_LINEOFFSET, 143,	/* 155 */
	HB_P_PUSHSYMNEAR, 28,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 24,	/* TELA1 */
/* 02057 */ HB_P_LINEOFFSET, 145,	/* 157 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 61,	/* 61 */
	'D', 'i', 'g', 'i', 't', 'e', ' ', 'o', ' ', 'C', 'o', 'd', 'i', 'g', 'o', ' ', 'd', 'a', ' ', 'D', 'e', 's', 'p', 'e', 's', 'a', ' ', 'a', ' ', 's', 'e', 'r', ' ', 'A', 'l', 't', 'e', 'r', 'a', 'd', 'o', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', ' ', 'p', '/', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 02127 */ HB_P_LINEOFFSET, 146,	/* 158 */
	HB_P_PUSHSYMNEAR, 24,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	' ', 'A', 'l', 't', 'e', 'r', 'a', 'c', 'a', 'o', ' ', 'C', 'i', 'd', 'a', 'd', 'e', ' ', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_DOSHORT, 7,
/* 02180 */ HB_P_LINEOFFSET, 147,	/* 159 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	23, 0,	/* MCID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 02225) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 02230) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02261 */ HB_P_LINEOFFSET, 148,	/* 160 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 29, 0,	/* 29*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	28, 0,	/* MCEP_CID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 02306) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 02311) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'c', 'e', 'p', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02346 */ HB_P_LINEOFFSET, 149,	/* 161 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 38, 0,	/* 38*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	29, 0,	/* MUF_CID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 02391) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 02396) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'm', 'u', 'f', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02430 */ HB_P_LINEOFFSET, 150,	/* 162 */
	HB_P_PUSHSYMNEAR, 30,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 42, 0,	/* 42*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 31,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 33,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	22, 0,	/* MCOD_CID */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 02475) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 02480) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'm', 'c', 'o', 'd', '_', 'c', 'i', 'd', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 35, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 02515 */ HB_P_LINEOFFSET, 151,	/* 163 */
	HB_P_PUSHSYMNEAR, 36,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 32, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 32, 0,	/* GETLIST */
/* 02537 */ HB_P_LINEOFFSET, 152,	/* 164 */
	HB_P_PUSHSYMNEAR, 37,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 27,	/* 27 (abs: 02574) */
/* 02549 */ HB_P_LINEOFFSET, 153,	/* 165 */
	HB_P_PUSHSYMNEAR, 38,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 24,	/* TELA1 */
	HB_P_DOSHORT, 5,
/* 02564 */ HB_P_LINEOFFSET, 154,	/* 166 */
	HB_P_PUSHSYMNEAR, 39,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 19, 4,	/* 1043 (abs: 03614) */
/* 02574 */ HB_P_LINEOFFSET, 157,	/* 169 */
	HB_P_PUSHSYMNEAR, 40,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_PUSHSTRSHORT, 20,	/* 20 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'A', 'l', 't', 'e', 'r', 'a', 'c', 'a', 'o', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 25,	/* OPCAO */
/* 02609 */ HB_P_LINEOFFSET, 158,	/* 170 */
	HB_P_PUSHLOCALNEAR, 25,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 207, 253,	/* -561 (abs: 02057) */
/* 02621 */ HB_P_LINEOFFSET, 159,	/* 171 */
	HB_P_PUSHSYMNEAR, 51,	/* BLOQREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 53,	/* 53 (abs: 02681) */
/* 02630 */ HB_P_LINEOFFSET, 160,	/* 172 */
	HB_P_PUSHSYMNEAR, 48,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'A', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 147, 253,	/* -621 (abs: 02057) */
/* 02681 */ HB_P_LINEOFFSET, 163,	/* 175 */
	HB_P_PUSHLOCALNEAR, 22,	/* MCOD_CID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 18,	/* COD_CID */
/* 02689 */ HB_P_LINEOFFSET, 164,	/* 176 */
	HB_P_PUSHLOCALNEAR, 23,	/* MCID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 15,	/* CIDADE */
/* 02697 */ HB_P_LINEOFFSET, 165,	/* 177 */
	HB_P_PUSHLOCALNEAR, 28,	/* MCEP_CID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 16,	/* CEP */
/* 02705 */ HB_P_LINEOFFSET, 166,	/* 178 */
	HB_P_PUSHLOCALNEAR, 29,	/* MUF_CID */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 17,	/* UF */
/* 02713 */ HB_P_LINEOFFSET, 167,	/* 179 */
	HB_P_PUSHMEMVAR, 42, 0,	/* COD_OPERADO */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_POPALIASEDFIELDNEAR, 43,	/* COD_OPE */
/* 02722 */ HB_P_LINEOFFSET, 168,	/* 180 */
	HB_P_PUSHSYMNEAR, 44,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02729 */ HB_P_LINEOFFSET, 169,	/* 181 */
	HB_P_PUSHSYMNEAR, 45,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02736 */ HB_P_LINEOFFSET, 171,	/* 183 */
	HB_P_PUSHSYMNEAR, 7,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'l', 'i', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 02755 */ HB_P_LINEOFFSET, 172,	/* 184 */
	HB_P_PUSHSYMNEAR, 39,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02762 */ HB_P_LINEOFFSET, 174,	/* 186 */
	HB_P_PUSHLOCALNEAR, 27,	/* MCID_AUX */
	HB_P_PUSHLOCALNEAR, 23,	/* MCID */
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSE, 164, 0,	/* 164 (abs: 02933) */
/* 02772 */ HB_P_LINEOFFSET, 175,	/* 187 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 34,	/* 34 */
	'A', 't', 'u', 'a', 'l', 'i', 'z', 'a', 'n', 'd', 'o', ' ', 'o', 's', ' ', 'C', 'l', 'i', 'e', 'n', 't', 'e', 's', '.', '.', '.', 'A', 'g', 'u', 'a', 'r', 'd', 'e', 0, 
	HB_P_DOSHORT, 1,
/* 02815 */ HB_P_LINEOFFSET, 176,	/* 188 */
	HB_P_PUSHSYMNEAR, 12,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 97,	/* 97 (abs: 02919) */
/* 02824 */ HB_P_LINEOFFSET, 177,	/* 189 */
	HB_P_PUSHSYMNEAR, 52,	/* CLI */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_PUSHLOCALNEAR, 27,	/* MCID_AUX */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 76,	/* 76 (abs: 02909) */
/* 02835 */ HB_P_LINEOFFSET, 178,	/* 190 */
	HB_P_PUSHSYMNEAR, 51,	/* BLOQREG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 52,	/* 52 (abs: 02894) */
/* 02844 */ HB_P_LINEOFFSET, 179,	/* 191 */
	HB_P_PUSHSYMNEAR, 48,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'A', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 179,	/* -77 (abs: 02815) */
/* 02894 */ HB_P_LINEOFFSET, 182,	/* 194 */
	HB_P_PUSHLOCALNEAR, 23,	/* MCID */
	HB_P_PUSHSYMNEAR, 52,	/* CLI */
	HB_P_POPALIASEDFIELDNEAR, 15,	/* CIDADE */
/* 02902 */ HB_P_LINEOFFSET, 183,	/* 195 */
	HB_P_PUSHSYMNEAR, 45,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02909 */ HB_P_LINEOFFSET, 185,	/* 197 */
	HB_P_PUSHSYMNEAR, 53,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 154,	/* -102 (abs: 02815) */
/* 02919 */ HB_P_LINEOFFSET, 187,	/* 199 */
	HB_P_PUSHSYMNEAR, 44,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02926 */ HB_P_LINEOFFSET, 188,	/* 200 */
	HB_P_PUSHSYMNEAR, 54,	/* DBUNLOCKALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02933 */ HB_P_LINEOFFSET, 190,	/* 202 */
	HB_P_PUSHSYMNEAR, 7,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 02952 */ HB_P_LINEOFFSET, 191,	/* 203 */
	HB_P_PUSHSYMNEAR, 38,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 24,	/* TELA1 */
	HB_P_DOSHORT, 5,
	HB_P_JUMP, 135, 2,	/* 647 (abs: 03614) */
/* 02970 */ HB_P_LINEOFFSET, 195,	/* 207 */
	HB_P_PUSHLOCALNEAR, 21,	/* F7OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'E', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 142, 2,	/* 654 (abs: 03633) */
/* 02982 */ HB_P_LINEOFFSET, 196,	/* 208 */
	HB_P_PUSHSYMNEAR, 28,	/* SAVESCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 24,	/* TELA1 */
/* 02997 */ HB_P_LINEOFFSET, 198,	/* 210 */
	HB_P_PUSHSYMNEAR, 23,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 61,	/* 61 */
	'D', 'i', 'g', 'i', 't', 'e', ' ', 'o', ' ', 'C', 'o', 'd', 'i', 'g', 'o', ' ', 'd', 'a', ' ', 'D', 'e', 's', 'p', 'e', 's', 'a', ' ', 'a', ' ', 's', 'e', 'r', ' ', 'E', 'x', 'c', 'l', 'u', 'i', 'd', 'a', ' ', '-', ' ', '<', 'E', 'S', 'C', '>', ' ', 'p', '/', 'R', 'e', 't', 'o', 'r', 'n', 'a', 'r', 0, 
	HB_P_DOSHORT, 1,
/* 03067 */ HB_P_LINEOFFSET, 199,	/* 211 */
	HB_P_LOCALNEARSETINT, 22, 0, 0,	/* MCOD_CID 0*/
/* 03073 */ HB_P_LINEOFFSET, 200,	/* 212 */
	HB_P_PUSHSYMNEAR, 27,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 23,	/* MCID */
/* 03084 */ HB_P_LINEOFFSET, 201,	/* 213 */
	HB_P_PUSHSYMNEAR, 24,	/* BOTAO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 3, 0,	/* 3*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	' ', 'E', 'x', 'c', 'l', 'u', 's', 'a', 'o', ' ', 'd', 'e', ' ', 'C', 'i', 'd', 'a', 'd', 'e', 's', ' ', 0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_DOSHORT, 7,
/* 03140 */ HB_P_LINEOFFSET, 202,	/* 214 */
	HB_P_PUSHSYMNEAR, 55,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 03149 */ HB_P_LINEOFFSET, 203,	/* 215 */
	HB_P_PUSHSYMNEAR, 56,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 57,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_DOSHORT, 1,
/* 03175 */ HB_P_LINEOFFSET, 204,	/* 216 */
	HB_P_PUSHSYMNEAR, 55,	/* SETCOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 03183 */ HB_P_LINEOFFSET, 205,	/* 217 */
	HB_P_PUSHSYMNEAR, 40,	/* OP_SIMNAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'C', 'o', 'n', 'f', 'i', 'r', 'm', 'a', ' ', 'E', 'x', 'c', 'l', 'u', 's', 'a', 'o', ':', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 25,	/* OPCAO */
/* 03217 */ HB_P_LINEOFFSET, 206,	/* 218 */
	HB_P_PUSHSYMNEAR, 37,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 03239) */
/* 03229 */ HB_P_LINEOFFSET, 207,	/* 219 */
	HB_P_PUSHSYMNEAR, 45,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 17, 255,	/* -239 (abs: 02997) */
/* 03239 */ HB_P_LINEOFFSET, 210,	/* 222 */
	HB_P_PUSHLOCALNEAR, 25,	/* OPCAO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'S', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 5, 255,	/* -251 (abs: 02997) */
/* 03251 */ HB_P_LINEOFFSET, 211,	/* 223 */
	HB_P_PUSHSYMNEAR, 58,	/* BLOQARQ */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPTRUENEAR, 53,	/* 53 (abs: 03311) */
/* 03260 */ HB_P_LINEOFFSET, 212,	/* 224 */
	HB_P_PUSHSYMNEAR, 48,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 39,	/* 39 */
	'N', 'a', 'o', ' ', 'f', 'o', 'i', ' ', 'p', 'o', 's', 's', 'i', 'v', 'e', 'l', ' ', 'a', 'c', 'e', 's', 's', 'a', 'r', ' ', 'o', ' ', 'A', 'r', 'q', 'u', 'i', 'v', 'o', ' ', '!', '!', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMP, 201, 254,	/* -311 (abs: 02997) */
/* 03311 */ HB_P_LINEOFFSET, 215,	/* 227 */
	HB_P_PUSHSYMNEAR, 59,	/* DBDELETE */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03318 */ HB_P_LINEOFFSET, 216,	/* 228 */
	HB_P_PUSHSYMNEAR, 44,	/* DBCOMMITALL */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03325 */ HB_P_LINEOFFSET, 217,	/* 229 */
	HB_P_PUSHSYMNEAR, 45,	/* DBUNLOCK */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 03332 */ HB_P_LINEOFFSET, 218,	/* 230 */
	HB_P_MESSAGE, 60, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 61,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 42,	/* 42 */
	'D', 'E', 'L', 'E', 'T', 'E', ' ', 'F', 'R', 'O', 'M', ' ', 's', 'a', 'c', 'c', 'i', 'd', ' ', 'W', 'H', 'E', 'R', 'E', ' ', 'S', 'R', '_', 'D', 'E', 'L', 'E', 'T', 'E', 'D', ' ', '=', ' ', 39, 'T', 39, 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 03391 */ HB_P_LINEOFFSET, 219,	/* 231 */
	HB_P_MESSAGE, 60, 0,	/* EXEC */
	HB_P_PUSHSYMNEAR, 61,	/* SR_GETCONNECTION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'O', 'M', 'M', 'I', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 03415 */ HB_P_LINEOFFSET, 220,	/* 232 */
	HB_P_PUSHSYMNEAR, 38,	/* RESTSCREEN */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHBYTE, 79,	/* 79 */
	HB_P_PUSHLOCALNEAR, 24,	/* TELA1 */
	HB_P_DOSHORT, 5,
/* 03430 */ HB_P_LINEOFFSET, 221,	/* 233 */
	HB_P_PUSHSYMNEAR, 13,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* F7LCI */
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 17,	/* OCONSPROD */
/* 03450 */ HB_P_LINEOFFSET, 222,	/* 234 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'i', 'd', 'a', 'd', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 03478 */ HB_P_LINEOFFSET, 223,	/* 235 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'C', 'E', 'P', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 03504 */ HB_P_LINEOFFSET, 224,	/* 236 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'U', 'F', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 03529 */ HB_P_LINEOFFSET, 225,	/* 237 */
	HB_P_LOCALNEARSETINT, 19, 0, 0,	/* F7I 0*/
/* 03535 */ HB_P_LINEOFFSET, 226,	/* 238 */
	HB_P_LOCALNEARSETINT, 19, 1, 0,	/* F7I 1*/
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_PUSHSYMNEAR, 19,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 03576) */
/* 03553 */ HB_P_LINEOFFSET, 227,	/* 239 */
	HB_P_MESSAGE, 20, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03568 */ HB_P_LINEOFFSET, 228,	/* 240 */
	HB_P_LOCALNEARADDINT, 19, 1, 0,	/* F7I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 03541) */
/* 03576 */ HB_P_LINEOFFSET, 229,	/* 241 */
	HB_P_MESSAGE, 21, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03590 */ HB_P_LINEOFFSET, 230,	/* 242 */
	HB_P_MESSAGE, 22, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03604 */ HB_P_LINEOFFSET, 231,	/* 243 */
	HB_P_MESSAGE, 25, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 19,	/* 19 (abs: 03633) */
/* 03616 */ HB_P_LINEOFFSET, 237,	/* 249 */
	HB_P_PUSHSYMNEAR, 62,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 32, 0,	/* GETLIST */
	HB_P_JUMP, 212, 1,	/* 468 (abs: 04098) */
/* 03633 */ HB_P_LINEOFFSET, 240,	/* 252 */
	HB_P_PUSHSYMNEAR, 13,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* F7LCI */
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 17,	/* OCONSPROD */
/* 03653 */ HB_P_LINEOFFSET, 241,	/* 253 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'i', 'd', 'a', 'd', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 03681 */ HB_P_LINEOFFSET, 242,	/* 254 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'C', 'E', 'P', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 03707 */ HB_P_LINEOFFSET, 243,	/* 255 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'U', 'F', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 03732 */ HB_P_LINEOFFSET, 244,	/* 256 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 18,	/* COD_CID */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPOP,
/* 03761 */ HB_P_LINEOFFSET, 245,	/* 257 */
	HB_P_LOCALNEARSETINT, 19, 0, 0,	/* F7I 0*/
/* 03767 */ HB_P_LINEOFFSET, 246,	/* 258 */
	HB_P_LOCALNEARSETINT, 19, 1, 0,	/* F7I 1*/
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_PUSHSYMNEAR, 19,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 03808) */
/* 03785 */ HB_P_LINEOFFSET, 247,	/* 259 */
	HB_P_MESSAGE, 20, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03800 */ HB_P_LINEOFFSET, 248,	/* 260 */
	HB_P_LOCALNEARADDINT, 19, 1, 0,	/* F7I 1*/
	HB_P_JUMPNEAR, 223,	/* -33 (abs: 03773) */
/* 03808 */ HB_P_LINEOFFSET, 249,	/* 261 */
	HB_P_MESSAGE, 21, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03822 */ HB_P_LINEOFFSET, 250,	/* 262 */
	HB_P_MESSAGE, 22, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 03836 */ HB_P_LINEOFFSET, 251,	/* 263 */
	HB_P_MESSAGE, 25, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 221, 242,	/* -3363 (abs: 00483) */
/* 03849 */ HB_P_LINEOFFSET, 253,	/* 265 */
	HB_P_PUSHSYMNEAR, 63,	/* GENKEY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'c', 'i', 'd', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_JUMPFALSE, 201, 242,	/* -3383 (abs: 00483) */
/* 03869 */ HB_P_LINEOFFSET, 254,	/* 266 */
	HB_P_PUSHSYMNEAR, 13,	/* TBROWSEDB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* F7LCI */
	HB_P_PUSHLOCALNEAR, 11,	/* F7CCI */
	HB_P_PUSHLOCALNEAR, 12,	/* F7LBA */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 13,	/* F7CBA */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 17,	/* OCONSPROD */
/* 03889 */ HB_P_LINEOFFSET, 255,	/* 267 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'i', 'd', 'a', 'd', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 15,	/* CIDADE */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 03917 */ HB_P_LINE, 12, 1,	/* 268 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'C', 'E', 'P', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 16,	/* CEP */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 03944 */ HB_P_LINE, 13, 1,	/* 269 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'U', 'F', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 17,	/* UF */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 03970 */ HB_P_LINE, 14, 1,	/* 270 */
	HB_P_PUSHSYMNEAR, 14,	/* TBCOLUMNNEW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 10,	/* CID */
	HB_P_PUSHALIASEDFIELDNEAR, 18,	/* COD_CID */
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLOCALREF, 18, 0,	/* OCOLPROD */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPOP,
/* 04000 */ HB_P_LINE, 15, 1,	/* 271 */
	HB_P_LOCALNEARSETINT, 19, 0, 0,	/* F7I 0*/
/* 04007 */ HB_P_LINE, 16, 1,	/* 272 */
	HB_P_LOCALNEARSETINT, 19, 1, 0,	/* F7I 1*/
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_PUSHSYMNEAR, 19,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 27,	/* 27 (abs: 04051) */
/* 04026 */ HB_P_LINE, 17, 1,	/* 273 */
	HB_P_MESSAGE, 20, 0,	/* ADDCOLUMN */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHLOCALNEAR, 18,	/* OCOLPROD */
	HB_P_PUSHLOCALNEAR, 19,	/* F7I */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 04042 */ HB_P_LINE, 18, 1,	/* 274 */
	HB_P_LOCALNEARADDINT, 19, 1, 0,	/* F7I 1*/
	HB_P_JUMPNEAR, 221,	/* -35 (abs: 04014) */
/* 04051 */ HB_P_LINE, 19, 1,	/* 275 */
	HB_P_MESSAGE, 21, 0,	/* _HEADSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	196, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 04066 */ HB_P_LINE, 20, 1,	/* 276 */
	HB_P_MESSAGE, 22, 0,	/* _COLSEP */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	179, 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 04081 */ HB_P_LINE, 21, 1,	/* 277 */
	HB_P_MESSAGE, 25, 0,	/* FORCESTABLE */
	HB_P_PUSHLOCALNEAR, 17,	/* OCONSPROD */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 231, 241,	/* -3609 (abs: 00483) */
	HB_P_JUMP, 228, 241,	/* -3612 (abs: 00483) */
/* 04098 */ HB_P_LINE, 25, 1,	/* 281 */
	HB_P_PUSHSYMNEAR, 7,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 14,	/* F7MSELE */
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 15,	/* F7MORDE */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 04123) */
	HB_P_PUSHSYMNEAR, 8,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 15,	/* F7MORDE */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 04124) */
	HB_P_PUSHNIL,
	HB_P_POP,
/* 04125 */ HB_P_LINE, 26, 1,	/* 282 */
	HB_P_PUSHSYMNEAR, 64,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 04133 */ HB_P_LINE, 27, 1,	/* 283 */
	HB_P_PUSHLOCALNEAR, 20,	/* F7NKEY */
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 04163) */
/* 04143 */ HB_P_LINE, 28, 1,	/* 284 */
	HB_P_PUSHSYMNEAR, 65,	/* __MVRELEASE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
/* 04156 */ HB_P_LINE, 29, 1,	/* 285 */
	HB_P_PUSHLOCALNEAR, 23,	/* MCID */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 04163 */ HB_P_LINE, 31, 1,	/* 287 */
	HB_P_PUSHSYMNEAR, 65,	/* __MVRELEASE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
/* 04176 */ HB_P_LINE, 32, 1,	/* 288 */
	HB_P_PUSHSYMNEAR, 62,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPMEMVAR, 32, 0,	/* GETLIST */
/* 04191 */ HB_P_LINE, 33, 1,	/* 289 */
	HB_P_PUSHLOCALNEAR, 23,	/* MCID */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 04198 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

