/*
 * xHarbour build 0.99.70 Intl. (SimpLex)
 * Generated C source code from <SAUTORIZA.PRG>
 * Command: C:\xHarbour997\bin\harbour.exe C:\HTI\SISMASTER\SAUTORIZA.PRG /q /oc:\HTI\sismaster\SAUTORIZA.c /M /N -DxHB -DXHB_0990 -DXHB_0991 -DXHB_0992 -DXHB_0993 -DXHB_0994 -DXHB_09941 -DXHB_09950 -DXHB_09951a -DXHB_09951 -DXHB_09951b -DXHB_0996 -DXHB_09960 -DXHB_09961 -DXHB_09961B -DXHB_0997 -DXHB_09970 
 * Created: 2023.05.30 12:24:46 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "SAUTORIZA.PRG"

HB_FUNC( AUTORIZACAO );
HB_FUNC( PINPAD );
HB_FUNC( PIN_PAD );
HB_FUNC( INSERIR_OBS );
HB_FUNC( CRIP );
HB_FUNC( DCRIP );
HB_FUNC( FECHA_TELA );
HB_FUNC( TIRA_PONTOS );
HB_FUNC( SENHA_CESSO );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( OP_TELA );
HB_FUNC_EXTERN( LIMPA );
HB_FUNC_EXTERN( WVW_DRAWLABEL );
HB_FUNC_EXTERN( MENSAGEM );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( WVW_PBSETFONT );
HB_FUNC_EXTERN( WVW_PBCREATE );
HB_FUNC_EXTERN( WVW_PBENABLE );
HB_FUNC_EXTERN( DISPBOX );
HB_FUNC_EXTERN( SETPOS );
HB_FUNC_EXTERN( __GET );
HB_FUNC_EXTERN( READMODAL );
HB_FUNC_EXTERN( LASTKEY );
HB_FUNC_EXTERN( WVW_PBDESTROY );
HB_FUNC_EXTERN( WVW_LCLOSEWINDOW );
HB_FUNC_EXTERN( __KEYBOARD );
HB_FUNC_EXTERN( READKILL );
HB_FUNC_EXTERN( DEVPOS );
HB_FUNC_EXTERN( DEVOUT );
HB_FUNC_EXTERN( UPPER );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( ATENCAO );
HB_FUNC_EXTERN( ASIZE );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( STRTRAN );
HB_FUNC_EXTERN( CTOD );
HB_FUNC_EXTERN( COL );
HB_FUNC_EXTERN( STRZERO );
HB_FUNC_EXTERN( VAL );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( DTOC );
HB_FUNC_EXTERN( DATE );
HB_FUNC_EXTERN( INKEY );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 7

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SAUTORIZA )
{ "AUTORIZACAO", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( AUTORIZACAO )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "M_SET", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "PINPAD", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( PINPAD )}, NULL },
{ "MQTD_CONT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MNUM", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MOK", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MVISUAL", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MSENHA", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "OP_TELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OP_TELA )}, NULL },
{ "LIMPA", {HB_FS_PUBLIC}, {HB_FUNCNAME( LIMPA )}, NULL },
{ "WVW_DRAWLABEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_DRAWLABEL )}, NULL },
{ "MENSAGEM", {HB_FS_PUBLIC}, {HB_FUNCNAME( MENSAGEM )}, NULL },
{ "I", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "WVW_PBSETFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBSETFONT )}, NULL },
{ "WVW_PBCREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBCREATE )}, NULL },
{ "PIN_PAD", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( PIN_PAD )}, NULL },
{ "INSERIR_OBS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( INSERIR_OBS )}, NULL },
{ "WVW_PBENABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBENABLE )}, NULL },
{ "DISPBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISPBOX )}, NULL },
{ "SETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPOS )}, NULL },
{ "GETLIST", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "__GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( __GET )}, NULL },
{ "DISPLAY", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "READMODAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READMODAL )}, NULL },
{ "LASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTKEY )}, NULL },
{ "WVW_PBDESTROY", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_PBDESTROY )}, NULL },
{ "WVW_LCLOSEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WVW_LCLOSEWINDOW )}, NULL },
{ "__KEYBOARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( __KEYBOARD )}, NULL },
{ "READKILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( READKILL )}, NULL },
{ "DEVPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVPOS )}, NULL },
{ "DEVOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEVOUT )}, NULL },
{ "CRIP", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( CRIP )}, NULL },
{ "UPPER", {HB_FS_PUBLIC}, {HB_FUNCNAME( UPPER )}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "ATENCAO", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATENCAO )}, NULL },
{ "DCRIP", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DCRIP )}, NULL },
{ "ASIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASIZE )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "FECHA_TELA", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( FECHA_TELA )}, NULL },
{ "TIRA_PONTOS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( TIRA_PONTOS )}, NULL },
{ "STRTRAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRTRAN )}, NULL },
{ "SENHA_CESSO", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( SENHA_CESSO )}, NULL },
{ "CTOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOD )}, NULL },
{ "COD_OPERADO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "COL", {HB_FS_PUBLIC}, {HB_FUNCNAME( COL )}, NULL },
{ "STRZERO", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRZERO )}, NULL },
{ "VAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VAL )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "DTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOC )}, NULL },
{ "DATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DATE )}, NULL },
{ "INKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INKEY )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_SAUTORIZA )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_SAUTORIZA
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_SAUTORIZA = hb_vm_SymbolInit_SAUTORIZA;
   #pragma data_seg()
#endif

HB_FUNC( AUTORIZACAO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 4, 0,	/* 4 */
	HB_P_PUSHSYMNEAR, 1,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 2, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_PUSHMEMVAR, 2, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 2, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 2, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 2, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_PUSHMEMVAR, 2, 0,	/* M_SET */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00090) */
/* 00085 */ HB_P_LINEOFFSET, 1,	/* 5 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00090 */ HB_P_LINEOFFSET, 3,	/* 7 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00095 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( PINPAD )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 4,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 15, 0,	/* 15 */
	HB_P_LOCALNEARSETSTR, 5, 10, 0,	/* MPRG 10*/
	'S', 'A', 'U', 'T', 'O', 'R', 'I', 'Z', 'A', 0, 
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 6,	/* NPBPINPAD */
/* 00025 */ HB_P_LINEOFFSET, 1,	/* 16 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_ZERO,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHSYMNEAR, 9,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 4,	/* MQTD_CONT */
	HB_P_PUSHSYMNEAR, 5,	/* MNUM */
	HB_P_PUSHSYMNEAR, 6,	/* MOK */
	HB_P_PUSHSYMNEAR, 7,	/* MVISUAL */
	HB_P_PUSHSYMNEAR, 8,	/* MSENHA */
	HB_P_DOSHORT, 5,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_POPVARIABLE, 6, 0,	/* MOK */
	HB_P_POPVARIABLE, 5, 0,	/* MNUM */
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 00065 */ HB_P_LINEOFFSET, 3,	/* 18 */
	HB_P_PUSHLOCALNEAR, 1,	/* MSEN */
	HB_P_POPVARIABLE, 8, 0,	/* MSENHA */
/* 00072 */ HB_P_LINEOFFSET, 4,	/* 19 */
	HB_P_PUSHSYMNEAR, 10,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	' ', 'T', 'E', 'C', 'L', 'A', 'D', 'O', ' ', 'V', 'I', 'R', 'T', 'U', 'A', 'L', ' ', '[', 'P', 'I', 'N', ' ', 'P', 'A', 'D', ']', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'*', 0, 
	HB_P_DOSHORT, 7,
/* 00121 */ HB_P_LINEOFFSET, 6,	/* 21 */
	HB_P_PUSHSYMNEAR, 11,	/* LIMPA */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_DOSHORT, 4,
/* 00134 */ HB_P_LINEOFFSET, 7,	/* 22 */
	HB_P_PUSHSYMNEAR, 12,	/* WVW_DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ONE,
	HB_P_PUSHLOCALNEAR, 2,	/* MDESCRICAO */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	't', 'i', 'm', 'e', 's', ' ', 'n', 'e', 'w', ' ', 'r', 'o', 'm', 'a', 'n', 0, 
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 16,
/* 00177 */ HB_P_LINEOFFSET, 8,	/* 23 */
	HB_P_PUSHLOCALNEAR, 3,	/* MMENSAG */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00194) */
/* 00185 */ HB_P_LINEOFFSET, 9,	/* 24 */
	HB_P_PUSHSYMNEAR, 13,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MMENSAG */
	HB_P_DOSHORT, 1,
/* 00194 */ HB_P_LINEOFFSET, 11,	/* 26 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 6,	/* NPBPINPAD */
/* 00201 */ HB_P_LINEOFFSET, 12,	/* 27 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 14, 0,	/* I */
/* 00207 */ HB_P_LINEOFFSET, 13,	/* 28 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 14, 0,	/* I */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00242) */
/* 00221 */ HB_P_LINEOFFSET, 14,	/* 29 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* NPBPINPAD */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 00231 */ HB_P_LINEOFFSET, 15,	/* 30 */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 14, 0,	/* I */
	HB_P_JUMPNEAR, 229,	/* -27 (abs: 00213) */
/* 00242 */ HB_P_LINEOFFSET, 17,	/* 32 */
	HB_P_PUSHSYMNEAR, 16,	/* WVW_PBSETFONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	't', 'i', 'm', 'e', 's', ' ', 'n', 'e', 'w', ' ', 'r', 'o', 'm', 'a', 'n', 0, 
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_DOSHORT, 4,
/* 00272 */ HB_P_LINEOFFSET, 18,	/* 33 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '1', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 00311 */ HB_P_LINEOFFSET, 19,	/* 34 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '2', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 00352 */ HB_P_LINEOFFSET, 20,	/* 35 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '3', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 00393 */ HB_P_LINEOFFSET, 21,	/* 36 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '4', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'4', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPOP,
/* 00433 */ HB_P_LINEOFFSET, 22,	/* 37 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '5', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_ARRAYPOP,
/* 00474 */ HB_P_LINEOFFSET, 23,	/* 38 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '6', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_ARRAYPOP,
/* 00515 */ HB_P_LINEOFFSET, 24,	/* 39 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '7', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'7', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_ARRAYPOP,
/* 00555 */ HB_P_LINEOFFSET, 25,	/* 40 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '8', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_ARRAYPOP,
/* 00596 */ HB_P_LINEOFFSET, 26,	/* 41 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '9', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'9', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_ARRAYPOP,
/* 00637 */ HB_P_LINEOFFSET, 27,	/* 42 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '0', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_ARRAYPOP,
/* 00677 */ HB_P_LINEOFFSET, 28,	/* 43 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', ',', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 12,	/* 12 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_ARRAYPOP,
/* 00718 */ HB_P_LINEOFFSET, 29,	/* 44 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 23,	/* 23 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '=', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 13,	/* 13 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'K', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_ARRAYPOP,
/* 00760 */ HB_P_LINEOFFSET, 30,	/* 45 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_ONE,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	' ', 'L', 'I', 'M', 'P', 'A', ' ', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 16,	/* 16 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'L', 'I', 'M', 'P', 'A', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_ARRAYPOP,
/* 00808 */ HB_P_LINEOFFSET, 31,	/* 46 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_PUSHBYTE, 19,	/* 19 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'A', 'N', 'C', '.', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 17,	/* 17 */
	HB_P_PUSHSYMNEAR, 18,	/* PIN_PAD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'A', 'N', 'C', 'E', 'L', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_ARRAYPOP,
/* 00856 */ HB_P_LINEOFFSET, 32,	/* 47 */
	HB_P_PUSHSYMNEAR, 17,	/* WVW_PBCREATE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 25,	/* 25 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'O', 'B', 'S', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 19,	/* INSERIR_OBS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_PUSHLOCALREF, 6, 0,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_ARRAYPOP,
/* 00893 */ HB_P_LINEOFFSET, 33,	/* 48 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 14, 0,	/* I */
/* 00899 */ HB_P_LINEOFFSET, 34,	/* 49 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 14, 0,	/* I */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_PUSHBYTE, 14,	/* 14 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00939) */
/* 00913 */ HB_P_LINEOFFSET, 35,	/* 50 */
	HB_P_PUSHSYMNEAR, 20,	/* WVW_PBENABLE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* NPBPINPAD */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_TRUE,
	HB_P_DOSHORT, 3,
/* 00928 */ HB_P_LINEOFFSET, 36,	/* 51 */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 14, 0,	/* I */
	HB_P_JUMPNEAR, 224,	/* -32 (abs: 00905) */
/* 00939 */ HB_P_LINEOFFSET, 37,	/* 52 */
	HB_P_PUSHLOCALNEAR, 4,	/* MOP_OBS */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00961) */
/* 00947 */ HB_P_LINEOFFSET, 38,	/* 53 */
	HB_P_PUSHSYMNEAR, 20,	/* WVW_PBENABLE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* NPBPINPAD */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_ARRAYPUSH,
	HB_P_FALSE,
	HB_P_DOSHORT, 3,
/* 00961 */ HB_P_LINEOFFSET, 40,	/* 55 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 6, 0,	/* MOK */
/* 00967 */ HB_P_LINEOFFSET, 41,	/* 56 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_POPVARIABLE, 5, 0,	/* MNUM */
/* 00976 */ HB_P_LINEOFFSET, 44,	/* 59 */
	HB_P_PUSHSYMNEAR, 11,	/* LIMPA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_DOSHORT, 4,
/* 00990 */ HB_P_LINEOFFSET, 46,	/* 61 */
	HB_P_PUSHVARIABLE, 8, 0,	/* MSENHA */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 01042) */
/* 00999 */ HB_P_LINEOFFSET, 47,	/* 62 */
	HB_P_PUSHSYMNEAR, 12,	/* WVW_DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ONE,
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 16,
	HB_P_JUMPNEAR, 43,	/* 43 (abs: 01083) */
/* 01042 */ HB_P_LINEOFFSET, 49,	/* 64 */
	HB_P_PUSHSYMNEAR, 12,	/* WVW_DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ONE,
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 16,
/* 01083 */ HB_P_LINEOFFSET, 54,	/* 69 */
	HB_P_PUSHSYMNEAR, 21,	/* DISPBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_ONE,
	HB_P_DOSHORT, 5,
/* 01098 */ HB_P_LINEOFFSET, 55,	/* 70 */
	HB_P_PUSHSYMNEAR, 22,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 23, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 24,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'n', 'u', 'm', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHBLOCKSHORT, 26,	/* 26 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'1', '2', '3', '4', '5', '6', '7', '8', '9', '0', ',', '.', 'O', 'L', 'C', ' ', 0, 
	HB_P_INSTRING,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 25, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 23, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 01173 */ HB_P_LINEOFFSET, 56,	/* 71 */
	HB_P_PUSHSYMNEAR, 26,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 23, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 23, 0,	/* GETLIST */
/* 01195 */ HB_P_LINEOFFSET, 59,	/* 74 */
	HB_P_PUSHVARIABLE, 6, 0,	/* MOK */
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 01214) */
	HB_P_PUSHSYMNEAR, 27,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 01226) */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'=', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 61,	/* 61 (abs: 01287) */
/* 01228 */ HB_P_LINEOFFSET, 60,	/* 75 */
	HB_P_ZERO,
	HB_P_POPVARIABLE, 14, 0,	/* I */
/* 01234 */ HB_P_LINEOFFSET, 61,	/* 76 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 14, 0,	/* I */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 27,	/* 27 (abs: 01273) */
/* 01248 */ HB_P_LINEOFFSET, 62,	/* 77 */
	HB_P_PUSHSYMNEAR, 28,	/* WVW_PBDESTROY */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* NPBPINPAD */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 2,
/* 01262 */ HB_P_LINEOFFSET, 63,	/* 78 */
	HB_P_PUSHVARIABLE, 14, 0,	/* I */
	HB_P_INC,
	HB_P_POPVARIABLE, 14, 0,	/* I */
	HB_P_JUMPNEAR, 225,	/* -31 (abs: 01240) */
/* 01273 */ HB_P_LINEOFFSET, 64,	/* 79 */
	HB_P_PUSHSYMNEAR, 29,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01280 */ HB_P_LINEOFFSET, 65,	/* 80 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01287 */ HB_P_LINEOFFSET, 74,	/* 89 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01328) */
/* 01299 */ HB_P_LINEOFFSET, 75,	/* 90 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01312 */ HB_P_LINEOFFSET, 76,	/* 91 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 78, 2,	/* 590 (abs: 01915) */
/* 01328 */ HB_P_LINEOFFSET, 77,	/* 92 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'2', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01369) */
/* 01340 */ HB_P_LINEOFFSET, 78,	/* 93 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'2', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01353 */ HB_P_LINEOFFSET, 79,	/* 94 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 37, 2,	/* 549 (abs: 01915) */
/* 01369 */ HB_P_LINEOFFSET, 80,	/* 95 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01410) */
/* 01381 */ HB_P_LINEOFFSET, 81,	/* 96 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01394 */ HB_P_LINEOFFSET, 82,	/* 97 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 252, 1,	/* 508 (abs: 01915) */
/* 01410 */ HB_P_LINEOFFSET, 83,	/* 98 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'4', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01451) */
/* 01422 */ HB_P_LINEOFFSET, 84,	/* 99 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'4', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01435 */ HB_P_LINEOFFSET, 85,	/* 100 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 211, 1,	/* 467 (abs: 01915) */
/* 01451 */ HB_P_LINEOFFSET, 86,	/* 101 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01492) */
/* 01463 */ HB_P_LINEOFFSET, 87,	/* 102 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01476 */ HB_P_LINEOFFSET, 88,	/* 103 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 170, 1,	/* 426 (abs: 01915) */
/* 01492 */ HB_P_LINEOFFSET, 89,	/* 104 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01533) */
/* 01504 */ HB_P_LINEOFFSET, 90,	/* 105 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01517 */ HB_P_LINEOFFSET, 91,	/* 106 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 129, 1,	/* 385 (abs: 01915) */
/* 01533 */ HB_P_LINEOFFSET, 92,	/* 107 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'7', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01574) */
/* 01545 */ HB_P_LINEOFFSET, 93,	/* 108 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'7', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01558 */ HB_P_LINEOFFSET, 94,	/* 109 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 88, 1,	/* 344 (abs: 01915) */
/* 01574 */ HB_P_LINEOFFSET, 95,	/* 110 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01615) */
/* 01586 */ HB_P_LINEOFFSET, 96,	/* 111 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01599 */ HB_P_LINEOFFSET, 97,	/* 112 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 47, 1,	/* 303 (abs: 01915) */
/* 01615 */ HB_P_LINEOFFSET, 98,	/* 113 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'9', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01656) */
/* 01627 */ HB_P_LINEOFFSET, 99,	/* 114 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'9', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01640 */ HB_P_LINEOFFSET, 100,	/* 115 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 6, 1,	/* 262 (abs: 01915) */
/* 01656 */ HB_P_LINEOFFSET, 101,	/* 116 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01697) */
/* 01668 */ HB_P_LINEOFFSET, 102,	/* 117 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01681 */ HB_P_LINEOFFSET, 103,	/* 118 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 221, 0,	/* 221 (abs: 01915) */
/* 01697 */ HB_P_LINEOFFSET, 104,	/* 119 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	',', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01738) */
/* 01709 */ HB_P_LINEOFFSET, 105,	/* 120 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01722 */ HB_P_LINEOFFSET, 106,	/* 121 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 180, 0,	/* 180 (abs: 01915) */
/* 01738 */ HB_P_LINEOFFSET, 107,	/* 122 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 01779) */
/* 01750 */ HB_P_LINEOFFSET, 108,	/* 123 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01763 */ HB_P_LINEOFFSET, 109,	/* 124 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMP, 139, 0,	/* 139 (abs: 01915) */
/* 01779 */ HB_P_LINEOFFSET, 110,	/* 125 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'l', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 01801) */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'L', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 01821) */
/* 01803 */ HB_P_LINEOFFSET, 111,	/* 126 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 01811 */ HB_P_LINEOFFSET, 112,	/* 127 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMPNEAR, 96,	/* 96 (abs: 01915) */
/* 01821 */ HB_P_LINEOFFSET, 113,	/* 128 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'o', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 01843) */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'O', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 01854) */
/* 01845 */ HB_P_LINEOFFSET, 114,	/* 129 */
	HB_P_PUSHSYMNEAR, 19,	/* INSERIR_OBS */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 63,	/* 63 (abs: 01915) */
/* 01854 */ HB_P_LINEOFFSET, 115,	/* 130 */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'C', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 11,	/* 11 (abs: 01876) */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'c', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 16,	/* 16 (abs: 01893) */
	HB_P_PUSHVARIABLE, 5, 0,	/* MNUM */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'9', '9', '9', '9', '9', '9', 0, 
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 01915) */
/* 01895 */ HB_P_LINEOFFSET, 116,	/* 131 */
	HB_P_PUSHSYMNEAR, 29,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01902 */ HB_P_LINEOFFSET, 117,	/* 132 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'A', 'N', 'C', 'E', 'L', 0, 
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 01915 */ HB_P_LINEOFFSET, 119,	/* 134 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_POPVARIABLE, 5, 0,	/* MNUM */
/* 01924 */ HB_P_LINEOFFSET, 122,	/* 137 */
	HB_P_PUSHSYMNEAR, 27,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSE, 66, 252,	/* -958 (abs: 00976) */
/* 01937 */ HB_P_LINEOFFSET, 123,	/* 138 */
	HB_P_PUSHSYMNEAR, 29,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01944 */ HB_P_LINEOFFSET, 124,	/* 139 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01951 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( PIN_PAD )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 146, 0,	/* 146 */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PUSHSTRSHORT, 32,	/* 32 */
	',', '.', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'L', 'I', 'M', 'P', 'A', 'O', 'K', 'C', 'A', 'N', 'C', 'E', 'L', 'O', 'B', 'S', 'R', 'E', 'T', 0, 
	HB_P_INSTRING,
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00050) */
/* 00045 */ HB_P_LINEOFFSET, 1,	/* 147 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00050 */ HB_P_LINEOFFSET, 3,	/* 149 */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	',', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00069) */
/* 00061 */ HB_P_LINEOFFSET, 4,	/* 150 */
	HB_P_LOCALNEARSETSTR, 1, 2, 0,	/* MNUMERO 2*/
	'.', 0, 
/* 00069 */ HB_P_LINEOFFSET, 7,	/* 153 */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'A', 'N', 'C', 'E', 'L', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 43,	/* 43 (abs: 00126) */
/* 00085 */ HB_P_LINEOFFSET, 8,	/* 154 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 6, 0,	/* MOK */
/* 00091 */ HB_P_LINEOFFSET, 9,	/* 155 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 00099 */ HB_P_LINEOFFSET, 10,	/* 156 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
/* 00107 */ HB_P_LINEOFFSET, 11,	/* 157 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'9', '9', '9', '9', '9', '9', 0, 
	HB_P_POPVARIABLE, 5, 0,	/* MNUM */
/* 00121 */ HB_P_LINEOFFSET, 12,	/* 158 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00126 */ HB_P_LINEOFFSET, 14,	/* 160 */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'K', 0, 
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00164) */
/* 00138 */ HB_P_LINEOFFSET, 15,	/* 161 */
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PLUS,
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 00149 */ HB_P_LINEOFFSET, 16,	/* 162 */
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'#', 0, 
	HB_P_PLUS,
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_JUMPNEAR, 45,	/* 45 (abs: 00207) */
/* 00164 */ HB_P_LINEOFFSET, 17,	/* 163 */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'K', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 33,	/* 33 (abs: 00207) */
/* 00176 */ HB_P_LINEOFFSET, 18,	/* 164 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 6, 0,	/* MOK */
/* 00182 */ HB_P_LINEOFFSET, 19,	/* 165 */
	HB_P_PUSHSYMNEAR, 30,	/* __KEYBOARD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	13, 0, 
	HB_P_DOSHORT, 1,
/* 00193 */ HB_P_LINEOFFSET, 20,	/* 166 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_POPVARIABLE, 5, 0,	/* MNUM */
/* 00202 */ HB_P_LINEOFFSET, 21,	/* 167 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00207 */ HB_P_LINEOFFSET, 23,	/* 169 */
	HB_P_PUSHLOCALNEAR, 1,	/* MNUMERO */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'L', 'I', 'M', 'P', 'A', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00238) */
/* 00222 */ HB_P_LINEOFFSET, 24,	/* 170 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 4, 0,	/* MQTD_CONT */
/* 00230 */ HB_P_LINEOFFSET, 25,	/* 171 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 7, 0,	/* MVISUAL */
/* 00238 */ HB_P_LINEOFFSET, 27,	/* 173 */
	HB_P_PUSHSYMNEAR, 11,	/* LIMPA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_DOSHORT, 4,
/* 00252 */ HB_P_LINEOFFSET, 28,	/* 174 */
	HB_P_PUSHVARIABLE, 8, 0,	/* MSENHA */
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 00304) */
/* 00261 */ HB_P_LINEOFFSET, 29,	/* 175 */
	HB_P_PUSHSYMNEAR, 12,	/* WVW_DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ONE,
	HB_P_PUSHVARIABLE, 4, 0,	/* MQTD_CONT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 16,
	HB_P_JUMPNEAR, 43,	/* 43 (abs: 00345) */
/* 00304 */ HB_P_LINEOFFSET, 31,	/* 177 */
	HB_P_PUSHSYMNEAR, 12,	/* WVW_DRAWLABEL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ONE,
	HB_P_PUSHVARIABLE, 7, 0,	/* MVISUAL */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'A', 'r', 'i', 'a', 'l', ' ', 'B', 'l', 'a', 'c', 'k', 0, 
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 16,
/* 00345 */ HB_P_LINEOFFSET, 36,	/* 182 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_POPVARIABLE, 5, 0,	/* MNUM */
/* 00354 */ HB_P_LINEOFFSET, 37,	/* 183 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00359 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( INSERIR_OBS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 187, 0,	/* 187 */
	HB_P_PUSHSYMNEAR, 10,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'D', 'i', 'g', 'i', 't', 'e', ' ', 'a', ' ', 'O', 'b', 's', 'e', 'r', 'v', 'a', 'c', 'a', 'o', ' ', 'q', 'u', 'e', ' ', 'd', 'e', 's', 'e', 'j', 'a', 0, 
	HB_P_DOSHORT, 5,
/* 00049 */ HB_P_LINEOFFSET, 1,	/* 188 */
	HB_P_PUSHSYMNEAR, 31,	/* READKILL */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_DOSHORT, 1,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 23, 0,	/* GETLIST */
/* 00063 */ HB_P_LINEOFFSET, 2,	/* 189 */
	HB_P_PUSHSYMNEAR, 32,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 33,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'O', 'b', 's', 'e', 'r', 'v', 'a', 'c', 'a', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00091 */ HB_P_LINEOFFSET, 3,	/* 190 */
	HB_P_PUSHSYMNEAR, 22,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 23, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 24,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'm', 'o', 'b', 's', 0, 
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'@', '!', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 25, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 23, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00141 */ HB_P_LINEOFFSET, 4,	/* 191 */
	HB_P_PUSHSYMNEAR, 26,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 23, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 23, 0,	/* GETLIST */
/* 00163 */ HB_P_LINEOFFSET, 5,	/* 192 */
	HB_P_PUSHSYMNEAR, 29,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00170 */ HB_P_LINEOFFSET, 6,	/* 193 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00175 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( CRIP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 3,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 199, 0,	/* 199 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 4,	/* MLETRA */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 5,	/* MAUX */
/* 00016 */ HB_P_LINEOFFSET, 1,	/* 200 */
	HB_P_PUSHSYMNEAR, 27,	/* LASTKEY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 27,	/* 27 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00033) */
/* 00028 */ HB_P_LINEOFFSET, 2,	/* 201 */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00033 */ HB_P_LINEOFFSET, 4,	/* 203 */
	HB_P_LOCALNEARSETSTR, 6, 1, 0,	/* MSENHA 1*/
	0, 
/* 00040 */ HB_P_LINEOFFSET, 5,	/* 204 */
	HB_P_PUSHSYMNEAR, 35,	/* UPPER */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* MEXP */
/* 00051 */ HB_P_LINEOFFSET, 6,	/* 205 */
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* I 0*/
/* 00057 */ HB_P_LINEOFFSET, 7,	/* 206 */
	HB_P_LOCALNEARSETINT, 7, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 24,	/* 24 (abs: 00097) */
/* 00075 */ HB_P_LINEOFFSET, 8,	/* 207 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 2,
/* 00089 */ HB_P_LINEOFFSET, 9,	/* 208 */
	HB_P_LOCALNEARADDINT, 7, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 224,	/* -32 (abs: 00063) */
/* 00097 */ HB_P_LINEOFFSET, 10,	/* 209 */
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* I 0*/
/* 00103 */ HB_P_LINEOFFSET, 11,	/* 210 */
	HB_P_LOCALNEARSETINT, 7, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 145, 1,	/* 401 (abs: 00520) */
/* 00122 */ HB_P_LINEOFFSET, 12,	/* 211 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00152) */
/* 00136 */ HB_P_LINEOFFSET, 13,	/* 212 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 106, 1,	/* 362 (abs: 00511) */
/* 00152 */ HB_P_LINEOFFSET, 14,	/* 213 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00182) */
/* 00166 */ HB_P_LINEOFFSET, 15,	/* 214 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 76, 1,	/* 332 (abs: 00511) */
/* 00182 */ HB_P_LINEOFFSET, 16,	/* 215 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'2', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00212) */
/* 00196 */ HB_P_LINEOFFSET, 17,	/* 216 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'W', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 46, 1,	/* 302 (abs: 00511) */
/* 00212 */ HB_P_LINEOFFSET, 18,	/* 217 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00242) */
/* 00226 */ HB_P_LINEOFFSET, 19,	/* 218 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'U', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 16, 1,	/* 272 (abs: 00511) */
/* 00242 */ HB_P_LINEOFFSET, 20,	/* 219 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'4', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00272) */
/* 00256 */ HB_P_LINEOFFSET, 21,	/* 220 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 242, 0,	/* 242 (abs: 00511) */
/* 00272 */ HB_P_LINEOFFSET, 22,	/* 221 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00302) */
/* 00286 */ HB_P_LINEOFFSET, 23,	/* 222 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'J', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 212, 0,	/* 212 (abs: 00511) */
/* 00302 */ HB_P_LINEOFFSET, 24,	/* 223 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00332) */
/* 00316 */ HB_P_LINEOFFSET, 25,	/* 224 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 182, 0,	/* 182 (abs: 00511) */
/* 00332 */ HB_P_LINEOFFSET, 26,	/* 225 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'7', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00362) */
/* 00346 */ HB_P_LINEOFFSET, 27,	/* 226 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'K', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 152, 0,	/* 152 (abs: 00511) */
/* 00362 */ HB_P_LINEOFFSET, 28,	/* 227 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00391) */
/* 00376 */ HB_P_LINEOFFSET, 29,	/* 228 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 122,	/* 122 (abs: 00511) */
/* 00391 */ HB_P_LINEOFFSET, 30,	/* 229 */
	HB_P_PUSHLOCALNEAR, 4,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'9', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00420) */
/* 00405 */ HB_P_LINEOFFSET, 31,	/* 230 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 93,	/* 93 (abs: 00511) */
/* 00420 */ HB_P_LINEOFFSET, 33,	/* 232 */
	HB_P_PUSHSYMNEAR, 37,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 69,	/* 69 */
	'S', 'E', 'N', 'H', 'A', ' ', 'D', 'E', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'C', 'A', 'O', ' ', 'F', 'o', 'i', ' ', 'd', 'i', 'g', 'i', 't', 'a', 'd', 'a', ' ', 'e', 'r', 'r', 'a', 'd', 'a', ',', ' ', 'v', 'e', 'r', 'i', 'f', 'i', 'q', 'u', 'e', ' ', 't', 'e', 'n', 't', 'e', ' ', 'n', 'o', 'v', 'a', 'm', 'e', 'n', 't', 'e', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00498 */ HB_P_LINEOFFSET, 34,	/* 233 */
	HB_P_LOCALNEARSETSTR, 6, 1, 0,	/* MSENHA 1*/
	0, 
/* 00505 */ HB_P_LINEOFFSET, 35,	/* 234 */
	HB_P_PUSHLOCALNEAR, 6,	/* MSENHA */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00511 */ HB_P_LINEOFFSET, 37,	/* 236 */
	HB_P_LOCALNEARADDINT, 7, 1, 0,	/* I 1*/
	HB_P_JUMP, 104, 254,	/* -408 (abs: 00109) */
/* 00520 */ HB_P_LINEOFFSET, 38,	/* 237 */
	HB_P_LOCALNEARSETINT, 7, 0, 0,	/* I 0*/
/* 00526 */ HB_P_LINEOFFSET, 39,	/* 238 */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00549) */
/* 00539 */ HB_P_LINEOFFSET, 40,	/* 239 */
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_POPLOCALNEAR, 6,	/* MSENHA */
	HB_P_JUMPNEAR, 54,	/* 54 (abs: 00601) */
/* 00549 */ HB_P_LINEOFFSET, 42,	/* 241 */
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 6,	/* MSENHA */
/* 00563 */ HB_P_LINEOFFSET, 43,	/* 242 */
	HB_P_LOCALNEARSETINT, 7, 3, 0,	/* I 3*/
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00601) */
/* 00581 */ HB_P_LINEOFFSET, 44,	/* 243 */
	HB_P_PUSHLOCALNEAR, 6,	/* MSENHA */
	HB_P_PUSHLOCALNEAR, 5,	/* MAUX */
	HB_P_PUSHLOCALNEAR, 7,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 6,	/* MSENHA */
/* 00593 */ HB_P_LINEOFFSET, 45,	/* 244 */
	HB_P_LOCALNEARADDINT, 7, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 226,	/* -30 (abs: 00569) */
/* 00601 */ HB_P_LINEOFFSET, 47,	/* 246 */
	HB_P_PUSHLOCALNEAR, 6,	/* MSENHA */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00607 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( DCRIP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 252, 0,	/* 252 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 2,	/* MLETRA */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 3,	/* MAUX */
/* 00016 */ HB_P_LINEOFFSET, 1,	/* 253 */
	HB_P_PUSHSYMNEAR, 39,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 00026 */ HB_P_LINEOFFSET, 2,	/* 254 */
	HB_P_PUSHSYMNEAR, 39,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 00036 */ HB_P_LINEOFFSET, 3,	/* 255 */
	HB_P_LOCALNEARSETSTR, 4, 1, 0,	/* MSENHA 1*/
	0, 
/* 00043 */ HB_P_LINEOFFSET, 4,	/* 256 */
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* I 0*/
/* 00049 */ HB_P_LINEOFFSET, 5,	/* 257 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 51,	/* 51 (abs: 00116) */
/* 00067 */ HB_P_LINEOFFSET, 6,	/* 258 */
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 10,	/* 10 (abs: 00090) */
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHNIL,
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 4,	/* 4 (abs: 00094) */
	HB_P_JUMPNEAR, 18,	/* 18 (abs: 00110) */
/* 00094 */ HB_P_LINEOFFSET, 9,	/* 261 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 2,
/* 00108 */ HB_P_LINEOFFSET, 10,	/* 262 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 197,	/* -59 (abs: 00055) */
/* 00116 */ HB_P_LINEOFFSET, 11,	/* 263 */
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* I 0*/
/* 00122 */ HB_P_LINEOFFSET, 12,	/* 264 */
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00138) */
/* 00133 */ HB_P_LINEOFFSET, 13,	/* 265 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00138 */ HB_P_LINEOFFSET, 15,	/* 267 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 145, 1,	/* 401 (abs: 00555) */
/* 00157 */ HB_P_LINEOFFSET, 16,	/* 268 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00187) */
/* 00171 */ HB_P_LINEOFFSET, 17,	/* 269 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 106, 1,	/* 362 (abs: 00546) */
/* 00187 */ HB_P_LINEOFFSET, 18,	/* 270 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'0', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00217) */
/* 00201 */ HB_P_LINEOFFSET, 19,	/* 271 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'1', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 76, 1,	/* 332 (abs: 00546) */
/* 00217 */ HB_P_LINEOFFSET, 20,	/* 272 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'W', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00247) */
/* 00231 */ HB_P_LINEOFFSET, 21,	/* 273 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'2', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 46, 1,	/* 302 (abs: 00546) */
/* 00247 */ HB_P_LINEOFFSET, 22,	/* 274 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'U', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00277) */
/* 00261 */ HB_P_LINEOFFSET, 23,	/* 275 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 16, 1,	/* 272 (abs: 00546) */
/* 00277 */ HB_P_LINEOFFSET, 24,	/* 276 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00307) */
/* 00291 */ HB_P_LINEOFFSET, 25,	/* 277 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'4', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 242, 0,	/* 242 (abs: 00546) */
/* 00307 */ HB_P_LINEOFFSET, 26,	/* 278 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'J', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00337) */
/* 00321 */ HB_P_LINEOFFSET, 27,	/* 279 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'5', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 212, 0,	/* 212 (abs: 00546) */
/* 00337 */ HB_P_LINEOFFSET, 28,	/* 280 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'3', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00367) */
/* 00351 */ HB_P_LINEOFFSET, 29,	/* 281 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 182, 0,	/* 182 (abs: 00546) */
/* 00367 */ HB_P_LINEOFFSET, 30,	/* 282 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'K', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00397) */
/* 00381 */ HB_P_LINEOFFSET, 31,	/* 283 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'7', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMP, 152, 0,	/* 152 (abs: 00546) */
/* 00397 */ HB_P_LINEOFFSET, 32,	/* 284 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'6', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00426) */
/* 00411 */ HB_P_LINEOFFSET, 33,	/* 285 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'8', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 122,	/* 122 (abs: 00546) */
/* 00426 */ HB_P_LINEOFFSET, 34,	/* 286 */
	HB_P_PUSHLOCALNEAR, 2,	/* MLETRA */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'A', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00455) */
/* 00440 */ HB_P_LINEOFFSET, 35,	/* 287 */
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'9', 0, 
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 93,	/* 93 (abs: 00546) */
/* 00455 */ HB_P_LINEOFFSET, 37,	/* 289 */
	HB_P_PUSHSYMNEAR, 37,	/* ATENCAO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 69,	/* 69 */
	'S', 'E', 'N', 'H', 'A', ' ', 'D', 'E', ' ', 'L', 'I', 'B', 'E', 'R', 'A', 'C', 'A', 'O', ' ', 'F', 'o', 'i', ' ', 'd', 'i', 'g', 'i', 't', 'a', 'd', 'a', ' ', 'e', 'r', 'r', 'a', 'd', 'a', ',', ' ', 'v', 'e', 'r', 'i', 'f', 'i', 'q', 'u', 'e', ' ', 't', 'e', 'n', 't', 'e', ' ', 'n', 'o', 'v', 'a', 'm', 'e', 'n', 't', 'e', '.', '.', '.', 0, 
	HB_P_DOSHORT, 1,
/* 00533 */ HB_P_LINEOFFSET, 38,	/* 290 */
	HB_P_LOCALNEARSETSTR, 4, 1, 0,	/* MSENHA 1*/
	0, 
/* 00540 */ HB_P_LINEOFFSET, 39,	/* 291 */
	HB_P_PUSHLOCALNEAR, 4,	/* MSENHA */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00546 */ HB_P_LINEOFFSET, 41,	/* 293 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* I 1*/
	HB_P_JUMP, 104, 254,	/* -408 (abs: 00144) */
/* 00555 */ HB_P_LINEOFFSET, 42,	/* 294 */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MEXP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00578) */
/* 00568 */ HB_P_LINEOFFSET, 43,	/* 295 */
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_POPLOCALNEAR, 4,	/* MSENHA */
	HB_P_JUMPNEAR, 60,	/* 60 (abs: 00636) */
/* 00578 */ HB_P_LINEOFFSET, 45,	/* 297 */
	HB_P_LOCALNEARSETINT, 5, 0, 0,	/* I 0*/
/* 00584 */ HB_P_LINEOFFSET, 46,	/* 298 */
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* MSENHA */
/* 00598 */ HB_P_LINEOFFSET, 47,	/* 299 */
	HB_P_LOCALNEARSETINT, 5, 3, 0,	/* I 3*/
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_PUSHSYMNEAR, 36,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00636) */
/* 00616 */ HB_P_LINEOFFSET, 48,	/* 300 */
	HB_P_PUSHLOCALNEAR, 4,	/* MSENHA */
	HB_P_PUSHLOCALNEAR, 3,	/* MAUX */
	HB_P_PUSHLOCALNEAR, 5,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* MSENHA */
/* 00628 */ HB_P_LINEOFFSET, 49,	/* 301 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* I 1*/
	HB_P_JUMPNEAR, 226,	/* -30 (abs: 00604) */
/* 00636 */ HB_P_LINEOFFSET, 51,	/* 303 */
	HB_P_PUSHLOCALNEAR, 4,	/* MSENHA */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00642 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( FECHA_TELA )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 50, 1,	/* 306 */
	HB_P_PUSHSYMNEAR, 29,	/* WVW_LCLOSEWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00008 */ HB_P_LINEOFFSET, 1,	/* 307 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00013 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TIRA_PONTOS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 55, 1,	/* 311 */
	HB_P_PUSHSYMNEAR, 43,	/* STRTRAN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MPALAVRA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 1,	/* MPALAVRA */
/* 00022 */ HB_P_LINEOFFSET, 1,	/* 312 */
	HB_P_PUSHSYMNEAR, 43,	/* STRTRAN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MPALAVRA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'-', 0, 
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 1,	/* MPALAVRA */
/* 00040 */ HB_P_LINEOFFSET, 2,	/* 313 */
	HB_P_PUSHSYMNEAR, 43,	/* STRTRAN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MPALAVRA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 1,	/* MPALAVRA */
/* 00058 */ HB_P_LINEOFFSET, 3,	/* 314 */
	HB_P_PUSHSYMNEAR, 43,	/* STRTRAN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* MPALAVRA */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	',', 0, 
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 1,	/* MPALAVRA */
/* 00076 */ HB_P_LINEOFFSET, 4,	/* 315 */
	HB_P_PUSHLOCALNEAR, 1,	/* MPALAVRA */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00082 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( SENHA_CESSO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 63, 1,	/* 319 */
	HB_P_PUSHSYMNEAR, 45,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	' ', ' ', '/', ' ', ' ', '/', ' ', ' ', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 6,	/* MDATA */
	HB_P_LOCALNEARSETSTR, 7, 1, 0,	/* MQTDDIAS 1*/
	0, 
/* 00029 */ HB_P_LINEOFFSET, 2,	/* 321 */
	HB_P_PUSHVARIABLE, 46, 0,	/* COD_OPERADO */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'9', '9', '9', 0, 
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00048) */
/* 00043 */ HB_P_LINEOFFSET, 3,	/* 322 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00048 */ HB_P_LINEOFFSET, 5,	/* 324 */
	HB_P_PUSHSYMNEAR, 10,	/* OP_TELA */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_DOSHORT, 5,
/* 00066 */ HB_P_LINEOFFSET, 6,	/* 325 */
	HB_P_PUSHSYMNEAR, 32,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 33,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'D', 'a', 't', 'a', ' ', 'V', 'e', 'n', 'c', 'i', 'm', 'e', 'n', 't', 'o', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00099 */ HB_P_LINEOFFSET, 7,	/* 326 */
	HB_P_PUSHSYMNEAR, 32,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 33,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'S', 'e', 'n', 'h', 'a', ' ', 'N', 'o', 'v', 'a', '.', '.', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00132 */ HB_P_LINEOFFSET, 8,	/* 327 */
	HB_P_PUSHSYMNEAR, 32,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 33,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'S', 'e', 'n', 'h', 'a', ' ', 'A', 'n', 't', 'i', 'g', 'a', '.', '.', '.', ':', 0, 
	HB_P_DOSHORT, 1,
/* 00166 */ HB_P_LINEOFFSET, 9,	/* 328 */
	HB_P_PUSHSYMNEAR, 22,	/* SETPOS */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHSYMNEAR, 47,	/* COL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 15,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 23, 0,	/* GETLIST */
	HB_P_PUSHSYMNEAR, 24,	/* __GET */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	6, 0,	/* MDATA */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00210) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00215) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'm', 'd', 'a', 't', 'a', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_DOSHORT, 2,
	HB_P_MESSAGE, 25, 0,	/* DISPLAY */
	HB_P_PUSHMEMVAR, 23, 0,	/* GETLIST */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00243 */ HB_P_LINEOFFSET, 10,	/* 329 */
	HB_P_PUSHSYMNEAR, 26,	/* READMODAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 23, 0,	/* GETLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 7,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPVARIABLE, 23, 0,	/* GETLIST */
/* 00265 */ HB_P_LINEOFFSET, 11,	/* 330 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_POPLOCALNEAR, 1,	/* MDIG1 */
/* 00351 */ HB_P_LINEOFFSET, 12,	/* 331 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 2,	/* MDIG2 */
/* 00410 */ HB_P_LINEOFFSET, 13,	/* 332 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* MDIG3 */
/* 00469 */ HB_P_LINEOFFSET, 14,	/* 333 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 4,	/* MDIG4 */
/* 00527 */ HB_P_LINEOFFSET, 15,	/* 334 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 49,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 51,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_POPLOCALNEAR, 5,	/* MDIG5 */
/* 00614 */ HB_P_LINEOFFSET, 16,	/* 335 */
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* MDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 21,	/* 21 (abs: 00644) */
/* 00625 */ HB_P_LINEOFFSET, 17,	/* 336 */
	HB_P_PUSHSYMNEAR, 48,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* MDATA */
	HB_P_PUSHSYMNEAR, 52,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_MINUS,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 7,	/* MQTDDIAS */
/* 00644 */ HB_P_LINEOFFSET, 19,	/* 338 */
	HB_P_PUSHSYMNEAR, 32,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 33,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'S', 'e', 'n', 'h', 'a', ' ', 'N', 'o', 'v', 'a', '.', '.', '.', '.', '.', ':', ' ', ' ', 0, 
	HB_P_PUSHLOCALNEAR, 1,	/* MDIG1 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 2,	/* MDIG2 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 3,	/* MDIG3 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 4,	/* MDIG4 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 5,	/* MDIG5 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 7,	/* MQTDDIAS */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00697 */ HB_P_LINEOFFSET, 20,	/* 339 */
	HB_P_PUSHSYMNEAR, 32,	/* DEVPOS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
	HB_P_PUSHSYMNEAR, 33,	/* DEVOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'S', 'e', 'n', 'h', 'a', ' ', 'A', 'n', 't', 'i', 'g', 'a', '.', '.', '.', ':', ' ', ' ', 0, 
	HB_P_PUSHLOCALNEAR, 1,	/* MDIG1 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 3,	/* MDIG3 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 4,	/* MDIG4 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 2,	/* MDIG2 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 5,	/* MDIG5 */
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 7,	/* MQTDDIAS */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00751 */ HB_P_LINEOFFSET, 22,	/* 341 */
	HB_P_PUSHSYMNEAR, 13,	/* MENSAGEM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 35,	/* 35 */
	'P', 'r', 'e', 's', 's', 'i', 'o', 'n', 'e', ' ', 'q', 'u', 'a', 'l', 'q', 'u', 'e', 'r', ' ', 't', 'e', 'c', 'l', 'a', ' ', 'p', 'a', 'r', 'a', ' ', 'S', 'A', 'I', 'R', 0, 
	HB_P_DOSHORT, 1,
/* 00795 */ HB_P_LINEOFFSET, 23,	/* 342 */
	HB_P_PUSHSYMNEAR, 53,	/* INKEY */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_DOSHORT, 1,
/* 00803 */ HB_P_LINEOFFSET, 24,	/* 343 */
	HB_P_PUSHSYMNEAR, 41,	/* FECHA_TELA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00810 */ HB_P_LINEOFFSET, 25,	/* 344 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00815 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

